### ISSUE TITLE
coc-clangd does not recognise nested imports

### ISSUE THREAD

**Issue by snprajwal** [clangd/clangd#1005]
If I add `#include <bits/stdc++.h>` to my file and try to type
`string s;`
The autocomplete suggests and adds `#include <string>`, even though the above header file contains this in its import list

**System information**
Clangd version (from the log, or `clangd --version`): 13.0.0
clangd extension version (from `:CocInfo`): 0.12.0
Operating system: Arch Linux with kernel 5.16.2-arch1-1

**Comment by kirillbobyrev** [comment]
Please take a look at other issues mentioning `bits/stdc++.h` (e.g. https://github.com/clangd/clangd/issues/353). The problem is that this header is not a part of the C++ Standard Library but rather a part of GNU C++ extension set. We know that it might be useful in some cases, but clangd uses its own Standard Library to figure out the right includes. In principle, `#include <string>` is strongly preferred over an umbrella header such as `<bits/stdc++.h>`. You can turn off the include insertion with `clangd --header-insertion=never`.

**Comment by snprajwal** [comment]
@kirillbobyrev is there any way to pass this header file to clangd and have it use this for the suggestions?

**Comment by kadircet** [comment]
it's not just about this file being an extension. clangd's include insertion follow IWYU policy, hence if your main file doesn't depend on the header defining/declaring the symbol directly, clangd will insert the include even if it is being transitively dependent on.

No matter if clangd understands `bits/stdc++.h` or not (unless you put an `// IWYU pragma: private` directive in the headers you want to hide, which would be quite complicated for stdlib headers) you would still get that insertion. You can turn it off via `--header-insertion=never`.

Clangd will still emit diagnostic fixes when you're making use of a symbol that's not visible in current file (at all, hence causing a hard error), if it knows about your code base (i.e performed indexing). They just won't happen automatically as you're code completing, you'll need to go an address these one by one.
