### ISSUE TITLE
all-scopes-completion should consider class/struct scope

### ISSUE THREAD

**Issue by tom-anders** [clangd/clangd#1082]
If we have 
``` 
namespace Foo { enum Bar {}; }
```
then with `all-scopes-completion` enabled, `Bar` will complete to `Foo::Bar`.

However for, 
``` 
struct Foo { enum Bar {}; }
```
this doesn't work. I think it would be very useful if this was at least an opt-in feature

**Comment by HighCommander4** [comment]
I think the reason is simply trying to cut down on index size by omitting symbols that are unnecessary for providing useful functionality.

Without all-scopes-completion, such nested symbols would indeed be unnecessary in the index, because the only way you could get them as a completion result is if you're invoking the completion in the nested scope (e.g. `Foo::^`), in which case result can be obtained from the AST. All-scopes-completion breaks this assumption, so the decision needs to be reevaluated.

What we've typically done in cases like this is:

 * Take an example project (e.g. LLVM), measure index size (disk and memory) with current code.
 * Make the change to index more symbols, measure index size again.
 * Post results here to discuss whether the increase in size is reasonable for the functionality gained.

**Comment by tom-anders** [comment]
Sounds good, will have a go at it tomorrow

**Comment by tom-anders** [comment]
You're right, the patch I posted above accidentally also indexes nested classes (I noticed when I ran the unit tests today), but that wasn't my intention. I've updated the patch so that it now only applies to enums: https://reviews.llvm.org/D136925

**Comment by HighCommander4** [comment]
But do the performance numbers you cited reflect indexing nested classes? Because if they do, meaning we can index them for that cheap, I'd say we should! (If they don't, I think it would still be interesting to measure the impact of indexing those, but of course we can leave that to another bug.)

**Comment by tom-anders** [comment]
Ah yes, I did the measurements **before** I noticed this bug, so the numbers should indeed include nested classes. However, the patch actually indexes **all** class members (even methods, static fields etc.) for completion, which is probably not what we want, so that would need to be fixed first. 

However, while I think completing scoped and nested enums with `all-scopes-completion` is really useful (and consistent), even when `all-scope-completions` is enabled, I'm not that sure about nested structs/classes actually. So I'd say let's start with enums for now.

**Comment by tom-anders** [comment]
Well, this is a bit embarrassing: I forgot that I had a special case in my nvim config where normally I'd point it to my custom built `clangd` binary, but with an exception for when I'm inside the LLVM codebase, where it would load a hardcoded stable binary instead. 

So here are some updated numbers:

| | HEAD    | index all enum constants for completion | index enum constants and everything inside classes/structs |
| ------------- | ------------- | ------------|----------|
| **index size on disk**  |137 MB | 137 MB  | 143 MB |
| **clangd RAM usage**  |1757 MB | 1783 MB | 1802 MB | 

Luckily, fully indexing the enum constants still looks like it's worth it (from a memory standpoint at least)
