### ISSUE TITLE
findReferences not work with struct which name starts with "_"

### ISSUE THREAD

**Issue by zoumi** [clangd/clangd#1091]
Please describe the problem.
if I define the struct like this:
```c
typedef struct {
    int thredhold;
}GInfo;
```
I can find all findReferences to the field "thredhold" in project wide.
![Snipaste_2022-04-02_15-45-34](https://user-images.githubusercontent.com/5162901/161372738-5bcf77ba-aaa5-4218-a0c1-96ebe13464a6.jpg)

But if I define the struct like this:
```c
typedef struct _GInfo_t{
    int thredhold;
}GInfo;
```
clangd can only find findReferences to the field "thredhold" in current opened document.
![Snipaste_2022-04-02_15-27-14](https://user-images.githubusercontent.com/5162901/161372620-5f35cabb-7172-4dbe-9fd5-505276a7b7ed.jpg)

**System information**

Output of `clangd --version`:14.0.0.0

Editor/LSP plugin:vs code

Operating system:Windows 10 64bit

**Comment by zoumi** [comment]
The test code can be found at https://github.com/zoumi/test_clangd_find_references

**Comment by sam-mccall** [comment]
Names beginning with underscore followed by an uppercase letter are reserved (i.e. illegal). Clangd assumes it's an internal part of the compiler or standard library (which are the only places where is valid to use such names) and that it's not supposed to be indexed.

Is this something from a common library, or is there some other reason to use this name?

**Comment by zoumi** [comment]
It's because a private c lib used by my team is using these names. I think this code can be compiled , so "find references" should work with it too.

**Comment by zoumi** [comment]
STMicroelectronics use "__" in their library:
https://github.com/STMicroelectronics/stm32f1xx_hal_driver/blob/master/Inc/stm32f1xx_hal_rcc.h
https://github.com/STMicroelectronics/stm32f1xx_hal_driver/blob/master/Inc/stm32f1xx_hal_rtc.h

**Comment by kirillbobyrev** [comment]
Yes, the code is compiling but it doesn't comply with the C++ Standard. From cppreference (https://en.cppreference.com/w/cpp/language/identifiers):

> - the identifiers with a double underscore anywhere are reserved;
> - the identifiers that begin with an underscore followed by an uppercase letter are reserved;
> - the identifiers that begin with an underscore are reserved in the global namespace.

There's also a lot of code that relies on Undefined Behavior and it also compiles just fine; sadly, plenty of _very widely-used_ libraries rely on it.

Sure, it's a pity that some code is not supported because of that, but C++ doesn't guarantee that this code compiles at all. The reason we don't support underscores is that we don't want to increase the size of the index, down-rank non-system headers and complicate the system. We've had some discussions regarding that in the past and made a conscious decision to not support this case.

We understand that it might not fit everyone's usecases and that is sad but that's a trade-off that I think we should take.

**Comment by sam-mccall** [comment]
I wonder if we can narrow this heuristic to only apply to system headers (-isystem)
