### ISSUE TITLE
"deep hover" information

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#11]
Selecting code in clangd would be a great way to show deep info about the code, e.g.

- dump selected bits of the AST
- memory layout for struct/class types
- expanded code for macro expansions

Unclear exactly what the interaction should be. Sections of the hover result? Code actions that insert comments?

**Comment by bstaletic** [comment]
This could be an interesting feature. Especially the memory layout.
Here's a few thoughts purely from the client's point of view:

- The request that a client makes could be similar to the already available `textDocument/hover`. Instead of the request parameters containing [`TextDocumentPositionParams`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#textdocumentpositionparams), clients could replace [`Position`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#position) with [`Range`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#range).
  - In case it is more convenient, instead of "overloading" `textDocument/hover`, this can be an extension that could be named `textDocument/deepHover`.
- I don't think the response being a series of code actions that insert comments are a good idea, because after reading what user was interested in the user would likely need to remove the inserted comments.

**Comment by sam-mccall** [comment]
> I don't think the response being a series of code actions that insert comments are a good idea, because after reading what user was interested in the user would likely need to remove the inserted comments.

Indeed. The only thing this idea has going for it is that code actions are already in the protocol and many editors support them, so it'd work on day 1. But not a good long-term option.

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D62538 will expose AST dump and memory layout as code actions that trigger `showMessage`.

**Comment by t-roche** [comment]
I would really like to be able to see the memory layout of a class or struct.
And to be able to expand a cpp macro.

Are there plans to support these (D62538 added the first item as a hidden feature)? I would be happy to help.

**Comment by sam-mccall** [comment]
We have size information in Hover for classes now, and offset+size for fields.
I'm not sure adding more class layout information would add much incremental value for most users, especially because it's not obvious which protocol messages/UI to bind it to.

I think I'm going to close this, because most of the specific ideas we had here are covered.
(Dump AST is still behind -hidden-features, but that would require quite a bit of design to make it interesting to non-clang devs and useful in many editors)
