### ISSUE TITLE
clangd can not switch from header to source(when .h in inc, .c in src folder)

### ISSUE THREAD

**Issue by wutianjun5858** [clangd/clangd#1144]
clangd can not switch from header to source(when .h in inc, .c in src folder), but clangd can switch from source to header(when .h in inc, .c in src folder)

**System information**

Output of `clangd --version`: 14

Editor/LSP plugin: lspconfig clangd

Operating system: ubuntu

**Comment by HighCommander4** [comment]
Some relevant discussion in #1043. Currently, when the header and source file are in different directories, the association is made based on their contents (e.g. one file declaring a function that the other defines). There was a bug in this mechanism that was fixed in that issue; it's worth trying a weekly snapshot build from https://github.com/clangd/clangd/releases to see if that fix resolves your scenario as well.

**Comment by wutianjun5858** [comment]
> Some relevant discussion in #1043. Currently, when the header and source file are in different directories, the association is made based on their contents (e.g. one file declaring a function that the other defines). There was a bug in this mechanism that was fixed in that issue; it's worth trying a weekly snapshot build from https://github.com/clangd/clangd/releases to see if that fix resolves your scenario as well.

But compile_commands.json can switch from header to source , just compile_flags.txt can not switch from header to source

**Comment by HighCommander4** [comment]
> But compile_commands.json can switch from header to source , just compile_flags.txt can not switch from header to source

Ah, that would explain it. The "associating headers/sources based on their contents" feature depends on clangd's **index** and clangd requires `compile_commands.json` to build an index.

**Comment by kadircet** [comment]
i'll close this as WAI. without index we can only support certain filename based heuristics, and having an index without compile_commands.json would be its own issue.
