### ISSUE TITLE
How to turn off configuration of macros colors?

### ISSUE THREAD

**Issue by huixiliu** [clangd/clangd#1199]
![image](https://user-images.githubusercontent.com/49441466/176347259-d5858cf8-ac31-4ebf-9d90-6788fdfd7a28.png)

clangd will mark the code as comment in the ’#else‘ case, how can I turn off it?
for sometimes，I learn some source library，the code is hard to read which was marked as comment, and I didn't find any way to turn off if.

**Comment by HighCommander4** [comment]
What client are you using? I have some suggestions which apply to the vscode client.

If you just want to change the style (e.g. color) of the code in the inactive preprocessor branches, you can do that by adding something like the following to vscode's settings:

```
"editor.semanticTokenColorCustomizations": {
  "enabled": true,
  "rules": {
    "comment": {
      "foreground": "#AABBCC"
    }
  }
}
```

If instead you'd like syntax highlighting for the inactive branches, that's currently not implemented, but there is discussion about it in https://github.com/clangd/vscode-clangd/pull/193, and [this comment](https://github.com/clangd/vscode-clangd/pull/193#issuecomment-1038463544) links to a prototype implementation in vscode-clangd (which you can apply locally if you'd like while waiting for that PR to be resolved).

**Comment by SamB** [comment]
But surely clangd doesn't have to send the comment tokens?

**Comment by HighCommander4** [comment]
> But surely clangd doesn't have to send the comment tokens?

The idea behind sending _something_ is so that inactive regions look different in some way, so you can tell they're inactive.

The idea behind using the `comment` semantic token is so that it looks different even with a default theme. Note that customizing the `comment` semantic token as suggested above doesn't change the appearance of actual comments (which don't get a **semantic** token), so you can independently customize the appearance of inactive regions and actual comments.

The direction agreed on in https://github.com/clangd/vscode-clangd/pull/193, which has not been implemented yet, is to change inactive regions to use a dedicated protocol message (as a protocol extension) rather than semantic highlighting, that should hopefully avoid some of the confusion around this.
