### ISSUE TITLE
Inlay hints from inside a macro are shown

### ISSUE THREAD

**Issue by Trass3r** [clangd/clangd#1289]
Accidentally reported it over at the main llvm repo: https://github.com/llvm/llvm-project/issues/56588

> after 6b50f2b I noticed this bad corner case:

![image](https://user-images.githubusercontent.com/404623/179491772-1df201c2-0f11-44ce-8911-9cb69d8ba0fc.png)

> They come from inside the macro:

![image](https://user-images.githubusercontent.com/404623/179492826-6e5b8d57-5420-4882-bc15-e692b99ded31.png)

**Comment by Trass3r** [comment]
Similar example reduced from real-world code:
```cpp
#define X 2, 3, 4
int a[] = {
    1,
    X, // shown as [1]=[2]=[3]=X,
    5,
};
```

**Comment by sam-mccall** [comment]
Yup. This is not designator-specific:
```
#define X 2, 3, 4
int m(int a, int b, int c);
int n = m(X); // a:b:c:X
```

**Comment by tom-anders** [comment]
Here's another simple example where this still seems to happen:

```
void foo(int x, int y) {}

#define MYMACRO(x, y) foo(x, y)
#define MYMACRO2(x) MYMACRO(x, 2)

MYMACRO2(1); // <- Shows inlay hint for x (Good!) but also for y (Bad!)
```

**Comment by HighCommander4** [comment]
Reopening per last comment

**Comment by sam-mccall** [comment]
Thanks for the example & reduction, can repro.

Further minimized:
```
int foo(int x);
#define FOO(X) foo(X)
#define INDIRECT FOO(2)

auto x = /*spurious x:*/INDIRECT;
```

I think the new approach (find the source range corresponding to the expanded token range) is the right one, and we've probably uncovered a bug in TokenBuffer which provides that algorithm. Will take a look.

**Comment by sam-mccall** [comment]
@kadircet the bug is in https://reviews.llvm.org/D75446, but I'm having trouble (re)understanding the intuition behind that patch in order to repair it. Maybe you can help me out?

---

Minimal example for spelledForExpanded:
```
#define FOO(X) foo(X)
#define INDIRECT FOO(y)
```
Now `INDIRECT` expands to `foo(y)`, and `spelledForExpanded(y)` yields `INDIRECT` instead of `None`.

---

Current behavior:

Start and endpoints are obviously the same, they come from a mapping (`INDIRECT`) so we enter the case added by your patch. `findCommonRangeForMacroArgs` walks partway up and stops when hitting INDIRECT ("do not continue into macro bodies"), and returns the expansion of the found so far.

I'm not sure how this is meant to work - I think findCommonRangeForMacroArgs is behaving per its contract, it finds a "smallest range that contains", and we're just missing any logic on this path checking that the range we're returning doesn't contain any *other* tokens.

---

My naive ideas to fix (by rewriting because I don't understand the current logic):

 - we're trying to find paths from the expanded endpoint tokens to the file endpoint tokens, these paths are constrained
 - they can traverse to expansion locations if they don't slice the body (left endpoint must pass through the start of the macro body; right must pass through the end)
 - they can traverse to spelling of macro arg expansions if *both* endpoints pass through the same expansion

Difficulties implementing this directly: testing whether the right endpoint is the last token of an expansion or not (token ranges strike again), the ambiguity of spelling vs expansion location of macro arg expansions (traversing either is OK).

**Comment by sam-mccall** [comment]
OK, this was quite an adventure. I learned new stuff about SourceLocations, which is ... not reassuring, after such a long time!

https://reviews.llvm.org/D134618 has a fix.
The "last token" problem is addressed by keeping track of the *next* expanded token, and verifying it's *outside* the expansion.
The ambiguity problem is addressed by traversing both endpoints at once and only descending if both are inside. It turns out other macros do not complicate this, because the order of macro expansion keeps them out of our way.
