### ISSUE TITLE
callHierarchy shows caller of global var and struct\class properties 

### ISSUE THREAD

**Issue by Nietzsche21** [clangd/clangd#1308]
When I used vscode + clangd, I found call Hierarchy Only shows function's caller. However, shows caller of global var and struct\class properties is also great features for programming. Can clangd support this?

**Comment by sam-mccall** [comment]
Can you explain a little how you would use this and how it differs from find-references? What do you mean by the "caller" of a struct member?

As I understand, the main difference between call-hierarchy and find-references is that hierarchy is recursive (you can browse the callers of callers of callers...).
I can imagine this being useful for field accesses too, even if the recursive part is still restricted to functions (find functions that modify this field, and callers of those functions, and callers of **those** functions). Is that what you mean?

**Comment by Nietzsche21** [comment]
> 

Thanks for reply. I would say yes as your image. Have you used eclipse? eclipse do this as your thought.

**Comment by Nietzsche21** [comment]
> Can you explain a little how you would use this and how it differs from find-references? What do you mean by the "caller" of a struct member?
> 
> As I understand, the main difference between call-hierarchy and find-references is that hierarchy is recursive (you can browse the callers of callers of callers...). I can imagine this being useful for field accesses too, even if the recursive part is still restricted to functions (find functions that modify this field, and callers of those functions, and callers of **those** functions). Is that what you mean?

Thanks for reply. I would say yes as your imagine. Have you used eclipse? eclipse do this as your thought.

**Comment by i-garrison** [comment]
> Can you explain a little how you would use this and how it differs from find-references? What do you mean by the "caller" of a struct member?

Here is an example picture from CDT docs https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_call_hierarchy_view.htm

With just `find-references` I have to  analyze each related code path independently which requires me to somehow remember what other code paths are related.

With Eclipse CDT call hierarchy view instead I _directly_ find a subset of code paths related to reading or writing that particular variable or member, then navigate through displayed call tree to understand what happens within that context. This may look similar to how eclipse mylyn task contexts helps reducing information overload, but with Eclipse CDT call hierarchy I get required subset of all code paths _without knowing of how code is structured beforehand_. This is really a killer feature for Eclipse CDT which as far as I can see is being added to other IDEs for that reason.

We can surely improve presentation method on IDE level: current Eclipse CDT does that by scanning through indexer database, going up from variables to functions referencing them and constructing call tree - and it should be possible to do similar thing with Eclipse CDT-LSP plugin https://github.com/eclipse-cdt/cdt-lsp/issues/272

On the other hand, if related call hierarchy will be available through LSP interface adding that feature will be rather easy for all IDEs.

**Comment by i-garrison** [comment]
Hi @HighCommander4 could you please put some starting points / guidance here so anyone interested to implement this would have something to start with!

**Comment by HighCommander4** [comment]
> Hi @HighCommander4 could you please put some starting points / guidance here so anyone interested to implement this would have something to start with!

Now that I take a look, I think it may be as simple as adjusting [this condition](https://searchfox.org/llvm/rev/4145ad2bac4bb99d5034d60c74bb2789f6c6e802/clang-tools-extra/clangd/XRefs.cpp#2239-2242) to include the newly allowed types of starting declarations (fields and namespace-scope variables).

**Comment by timon-ul** [comment]
Hi @HighCommander4 I am currently looking into implementing this feature and would appreciate some more help. Just throwing out the whole if-statement you have linked seems to make it work for all intended purposes, but I assume this also allows some undesired side effects. I guess optimally I would add some more checks for 'Decl->getKind() != ?' but here I am a bit lost what exactly the right enum values are since the enum for 'Kind' is including a generated file which is not very easy to read for me.

**Comment by timon-ul** [comment]
So given my drive comes mostly from bringing clangd on parity with the Eclipse indexer's call hierarchy I noticed it is surprisingly hard to figure out what all the possible cases Eclipse allows are. I personally found you can use it on enum members which then shows you where a specific enum member is used, but when I enable 'Decl::Kind::Enum' clangd will list where any of the enums, not the specific member, are used. I am not sure if this is "good enough", quite honesty everyone I asked wasn't even aware Eclipse is able to do this. 

I would really appreciate some more opinions on what to enable the call hierarchy for.

**Comment by i-garrison** [comment]
> I would really appreciate some more opinions on what to enable the call hierarchy for.

Eclipse CDT selection could be a good start: https://github.com/eclipse-cdt/cdt/blob/main/core/org.eclipse.cdt.ui/src/org/eclipse/cdt/internal/ui/callhierarchy/CallHierarchyUI.java#L315-L352

That basically works with given identifier name, allows it to resolve to declaration or definition of enum members, functions and variables (including template declarations and definitions) but filters out scope-local variables before building call tree.

**Comment by HighCommander4** [comment]
@timon-ul `Field` and `Var` sounds reasonable to me, except for `Var` we need to limit it to member or namespace-scope variables, as local variables are not stored in the index and so the current call hierarchy implementation (which uses the index) will not find callers for them.

The limitation can be implemented as `(Decl->getKind() == Decl::Kind::Var && !cast<VarDecl>(Decl)->isLocalVar())`.

(We can envision a future enhancement of call hierarchy that uses the AST to find incoming calls for local variables as well.)

For enumerators, we should be able to include `Decl::Kind::EnumConstant`.

**Comment by timon-ul** [comment]
@i-garrison thank you very much, I wanted to eventually dig into eclipse myself but you saved me quite some time. Was very helpful.

@HighCommander4 I agree, I was already myself looking for a way to limit the scope but I was not able to yet find a way, thank  you for providing one. Otherwise regarding the enum I tried using `Decl::Kind::EnumConstant` before but it didn't work, now I just tried it again since u mentioned it and it seems like it only sometimes works? It is really weird and I will try a bit to see if I can pinpoint when and why.

**Comment by timon-ul** [comment]
Ok so this behavour is weird, but it seems consistent.

If you enable only `Decl::Kind::EnumConstant` **only the last** enum will be able to produce a call hierarchy, everything else will give no result.

If you enable only `Decl::Kind::Enum` **all except the last** enum will be able to produce a call hierarchy, BUT this will result in showing all uses of the enum type itself, not the specific kind of enum.  The last enum shows no result.

Is this a bug? Seems really odd to me.

**Comment by timon-ul** [comment]
Another thing that I was wondering if it makes sense to enable the call hierarchy on variable templates (since we have `Decl::Kind::VarTemplate`). Interestingly enough this seems to *somewhat* already be possible with just the `Decl::Kind::Var` in the code, but then it only works if you call it on the template itself and not its instantiations. I noticed the same is true for functions and was wondering if this is intended behavior? I can see arguments for it, but at least Eclipse allows you to do it on an instantiation and behaves as if it was called on the template itself (so it shows all instantiations of a template, not just the ones with the same instantiation).

**Comment by HighCommander4** [comment]
> If you enable only `Decl::Kind::EnumConstant` **only the last** enum will be able to produce a call hierarchy, everything else will give no result.
> 
> If you enable only `Decl::Kind::Enum` **all except the last** enum will be able to produce a call hierarchy, BUT this will result in showing all uses of the enum type itself, not the specific kind of enum. The last enum shows no result.
> 
> Is this a bug? Seems really odd to me.

It certainly seems odd. I would suggest filing a separate issue with a test case.

> Another thing that I was wondering if it makes sense to enable the call hierarchy on variable templates

Conceptually, a variable template seems like a valid type of declaration to invoke call hierarchy on, yes.

> (since we have `Decl::Kind::VarTemplate`). Interestingly enough this seems to _somewhat_ already be possible with just the `Decl::Kind::Var` in the code, but then it only works if you call it on the template itself and not its instantiations. I noticed the same is true for functions and was wondering if this is intended behavior? I can see arguments for it, but at least Eclipse allows you to do it on an instantiation and behaves as if it was called on the template itself (so it shows all instantiations of a template, not just the ones with the same instantiation).

The modeling of templates in the clang AST takes some getting used to. There is a `VarTemplateDecl` representing the template declaration, with a `VarDecl` inside it representing the un-instantiated variable that's being templated; additionally, there is a `VarDecl` for every instantiation.

From a user's point of view, I think the _ideal_ behaviour would be if invoking call hierarchy on the template itself found uses of all instantiations, while invoking it on an instantiation found uses only of that instantiation; but this would require storing the instantiations as distinct symbols in the index, which clangd doesn't currently do (https://github.com/clangd/clangd/issues/536).

Until we can get that, the behaviour you describe Eclipse as having (invoking it on any instantiation finds uses of all insantiations) sounds reasonable. The fact that we currently don't even do that is very likely an oversight. As with the enum constant case, I would suggest filing a new issue with a test case to track further investigation of it.

**Comment by timon-ul** [comment]
> From a user's point of view, I think the ideal behaviour would be if invoking call hierarchy on the template itself found uses of all instantiations, while invoking it on an instantiation found uses only of that instantiation;

Yeah I was actually thinking the same, because it does not 100% make sense to show a different instantiation when you do a call hierarchy on a specific one (to some degree it does I feel like but it is a bit fuzzy). 

> It certainly seems odd. I would suggest filing a separate issue with a test case.

Gladly, but just so I understand correctly, I cannot provide a test case without having this officially integrated into clangd so do you suggest I first do a pullrequest for this ticket and then create those new issues? I guess there might be some way to already now trigger this behaviour in a different way but it seems a lot more complicated at a first glance to me.

> There is a VarTemplateDecl representing the template declaration, with a VarDecl inside it representing the un-instantiated variable that's being templated; additionally, there is a VarDecl for every instantiation.

So here I am a bit lost. Overall the question for me is, do I need `Decl::Kind::VarTemplate` or not. Reading your comment I would assume I do, for the case of calling a hierarchy on the declaration of the template to find all its instantiations. But as I mentioned I do not. So I am really confused what to make of this.

**Comment by HighCommander4** [comment]
> > It certainly seems odd. I would suggest filing a separate issue with a test case.
> 
> Gladly, but just so I understand correctly, I cannot provide a test case without having this officially integrated into clangd so do you suggest I first do a pullrequest for this ticket and then create those new issues? I guess there might be some way to already now trigger this behaviour in a different way but it seems a lot more complicated at a first glance to me.

Yeah, why don't we start with a PR for the cases that are working well (e.g. `Field`).

Then you could follow that up with a draft PR for `EnumConstant` with a test case that fails, and we can discuss it further there. (I'm happy to help debug it.)

> > There is a VarTemplateDecl representing the template declaration, with a VarDecl inside it representing the un-instantiated variable that's being templated; additionally, there is a VarDecl for every instantiation.
> 
> So here I am a bit lost. Overall the question for me is, do I need `Decl::Kind::VarTemplate` or not. Reading your comment I would assume I do, for the case of calling a hierarchy on the declaration of the template to find all its instantiations. But as I mentioned I do not. So I am really confused what to make of this.

Sorry, the reason my post was vague on that point is that I'm not sure myself!

It's possible that `Decl::Kind::Var` might be enough because as mentioned there is a `VarDecl` wrapped inside every `VarTemplateDecl`.

Let's start with just `Var` (no `VarTemplate`), and then we can look at any test cases involving variable templates that still don't work and take it from there.

**Comment by timon-ul** [comment]
Before I open a PR I wanted to ask about how I should go about this. Should I add a UnitTest (or any other kind of Test) to my additions? Because quite frankly the code used for Tests in clangd confuse me and I feel a bit lost (for example in the callHierarchy unit test the use of `$` in the string literals, I thought that is supposed to be cpp code, why is that allowed?). So I would appreciate some kind of documentation how to write these tests. 

This also ties into me not being 100% sure what you mean when you say "test case that fails". Do you mean an actual test that fails or sample code that does not produce the desired output? Because again I would need to read up on how to write tests. 

Lastly, regarding debugging clangd. I tried this before and failed miserably...I will try again but I might need some help how to set this up. I have read in a forum thread that you use rr to debug clangd but I struggeled to get that running too. Mainly it felt like the instructions are not clear enough for me. I have little experience with setting up these kind of things myself and usually had the luxury of having others set these things up for me (but I am willing to learn!).

**Comment by HighCommander4** [comment]
> Before I open a PR I wanted to ask about how I should go about this. Should I add a UnitTest (or any other kind of Test) to my additions?

Yes please, a unit test in [CallHierarchyTests.cpp]I(https://searchfox.org/llvm/source/clang-tools-extra/clangd/unittests/CallHierarchyTests.cpp) would be great.

> Because quite frankly the code used for Tests in clangd confuse me and I feel a bit lost (for example in the callHierarchy unit test the use of `$` in the string literals, I thought that is supposed to be cpp code, why is that allowed?). So I would appreciate some kind of documentation how to write these tests.

Good question. The strings like [this](https://searchfox.org/llvm/rev/927559d27d5bfe97ad668a562489d732b8bc246f/clang-tools-extra/clangd/unittests/CallHierarchyTests.cpp#60-73) that appear in the unit tests are passed to a helper class called `Annotations`, which represents source code with some annotations added to it. You can read about the class [here](https://searchfox.org/llvm/rev/927559d27d5bfe97ad668a562489d732b8bc246f/llvm/include/llvm/Testing/Annotations/Annotations.h#21-52).

The annotations allow specifying points in the code (e.g. to indicate the place where call hierarchy should be invoked), as well as giving names to certain ranges of characters in the code (so we can make assertions about the results of the call hierarchy operation).

Let me know if you have further questions, I'm happy to answer them.

> This also ties into me not being 100% sure what you mean when you say "test case that fails". Do you mean an actual test that fails or sample code that does not produce the desired output? Because again I would need to read up on how to write tests.

In general, for filing an issue, a piece of sample code is sufficient.

In this case, since you're working on the clangd code anyways, an actual test case would be even better. Certainly, it would help me help you faster, because I can just check out the draft PR and start debugging the test case :) And we'll need the test case anyways for when we fix the issue and want to merge the fix.

> Lastly, regarding debugging clangd. I tried this before and failed miserably...I will try again but I might need some help how to set this up. I have read in a forum thread that you use rr to debug clangd but I struggeled to get that running too. Mainly it felt like the instructions are not clear enough for me. I have little experience with setting up these kind of things myself and usually had the luxury of having others set these things up for me (but I am willing to learn!).

My most important piece of advice is to start by having a unit test to debug :) This is much easier than trying to debug a "live" clangd instance (i.e. a clangd process being controlled by an LSP client in an editor), which has a lot more going on.

A unit test can be debugged fairly straighforwardly by stepping through it with gdb (or your debugger of choice, e.g. lldb, Visual Studio, etc.)

What platform are you on? rr only works on Linux, but if you are on Linux, I highly recommend it; it's basically gdb with the superpower of also being able to run backwards (so e.g. you can break at a point that was hit earlier than your current breakpoint, and go back to that point).

**Comment by timon-ul** [comment]
> My most important piece of advice is to start by having a unit test to debug :) This is much easier than trying to debug a "live" clangd instance (i.e. a clangd process being controlled by an LSP client in an editor), which has a lot more going on.

I see, that was indeed what I was trying to do and struggled a lot with.

> A unit test can be debugged fairly straighforwardly by stepping through it with gdb (or your debugger of choice, e.g. lldb, Visual Studio, etc.)

Makes sense, I am actually working with lldb usually so this should be no issue.

> What platform are you on?

Currently I am working on redhat 9, I managed to install rr before, just had trouble using it with a "live" clangd instance. Will look and see if I can manage to debug tests with it instead. 

Otherwise my next step will be looking at writing a unit test for `Field` and `Var`.

**Comment by timon-ul** [comment]
I have now added a first pullrequest `Field` and `Var` as mentioned, not sure if I was able to follow the process properly, since it is my first time contributing to a public repository. 

Otherwise I was wondering about the next step. I think I now can easily write a unit test for `EnumConstant` that fails, but can I only execute that Test somehow? So far I only know `cmake --build $LLVM_ROOT/build --target check-clangd` to execute tests which first will try to build and then execute all tests which seems a bit overkill to me.

**Comment by HighCommander4** [comment]
> I think I now can easily write a unit test for `EnumConstant` that fails, but can I only execute that Test somehow? So far I only know `cmake --build $LLVM_ROOT/build --target check-clangd` to execute tests which first will try to build and then execute all tests which seems a bit overkill to me.

In the build directory, you can run:

```
tools/clang/tools/extra/clangd/unittests/ClangdTests --gtest_filter=FixtureName.TestName
```

You can also do wildcard patterns (need single quotes):

```
tools/clang/tools/extra/clangd/unittests/ClangdTests --gtest_filter='FixtureName.*'
```

**Comment by timon-ul** [comment]
I started looking into the whole `EnumConstant` case and it seems to be a bit more complicated than I anticipated. All tests in CallHierarchyTests.cpp are testing the output of `prepareCallHierarchy(...)` but it seems like here it still works as expected. When testing any of the enums it returns the expected caller, while when actually used as LSP it returns an empty tree (except for the last enum). It does not look transparent to me for now where this discrepancy happens, I will keep looking but am grateful for any ideas.

**Comment by HighCommander4** [comment]
> I started looking into the whole `EnumConstant` case and it seems to be a bit more complicated than I anticipated. All tests in CallHierarchyTests.cpp are testing the output of `prepareCallHierarchy(...)` but it seems like here it still works as expected. When testing any of the enums it returns the expected caller, while when actually used as LSP it returns an empty tree (except for the last enum). It does not look transparent to me for now where this discrepancy happens, I will keep looking but am grateful for any ideas.

I'm happy to poke around a bit. It would be great to share your work in progress as a starting point.

**Comment by timon-ul** [comment]
> I'm happy to poke around a bit. It would be great to share your work in progress as a starting point.

Sure, I have created a new branch on my fork with my test https://github.com/timon-ul/llvm-project/tree/extend-call-hierarchy-enum . If I create a new cpp file with exactly the content of the test cpp code and try to get the call hierarchy the same way as in the test, so on the definition, it does not work on `heads`. If you were to try to get a call hierarchy for `heads` on where it is used instead, it works.

**Comment by HighCommander4** [comment]
I'm going to consider this issue resolved by https://github.com/llvm/llvm-project/pull/113900, since what is described in the issue title (global variables and struct/class properties) has been addressed by the patch.

We can pursue enum constants and variable templates in separate issues.

**Comment by HighCommander4** [comment]
> We can pursue enum constants and variable templates in separate issues.

I filed #2203 for enum constants. Will leave it up to whoever is interested in pursuing it to file a follow-up for variable templates.
