### ISSUE TITLE
Add an option to specify a workspece-level config file

### ISSUE THREAD

**Issue by daiyousei-qz** [clangd/clangd#1336]
Would you guys accept a patch that adds an option to the clangd binary so that, user could specify a path to a workspace config yaml file? This config file stands between the in-tree configs and the global config.

Motivation: The same codebase is shared by two different workspaces with different build targets. Adding this option could allow each workspace to have different clangd settings. For my case, it's the (multiple) compile database files since the same source files are compiled with different flags in different workspaces.

**Comment by HighCommander4** [comment]
cc @kadircet, there was some previous discussion of this in #845

In my opinion, such an option would make sense and be useful.

**Comment by daiyousei-qz** [comment]
Yeah, [#845](https://github.com/clangd/clangd/issues/845) looks like requesting quite a similar feature. The only difference is that I don't look for completely shutting down the global user config in the presence of workspace-level config. So, I believe it is much easier to implement.

**Comment by sam-mccall** [comment]
Can you be more concrete about what you're trying to achieve?

Do you want different settings for the same source file in different editing sessions? (If so, what settings and why?)
Or do you want to specify different compilation databases for different files in a way that doesn't map neatly to directory hierarchy? (And can you give an example of this)

The solution you're proposing isn't *impossible*, but we get to do it ~once. "Just make the config system more complicated" is an even more expensive version of "just add a setting" - clang-tidy is an example of how bad that can get.

**Comment by sam-mccall** [comment]
You've mentioned "workspace" a few times, it'd be great to be more specific of what you mean by this. (It doesn't seem to be "the directory containing the source code", is it "a build tree/configuration", or something specific to an editor?

(Depending on the requirements, this may already be covered by `If` in config, may be cheaply covered by adding more conditions to `If`, may be best handled by symlinking

**Comment by HighCommander4** [comment]
Linking the associated proof-of-concept patch: https://reviews.llvm.org/D136033

**Comment by sam-mccall** [comment]
Hmm, if the "workspace" is meant to be vscode's workspace concept, maybe we should consider just searching the workspace directories from the `initialize` request, where that concept has leaked into LSP already. At least we wouldn't need to add a new flag and require the user to sticky-tape this all together.

It would still be good to see some concrete examples of what this is for.

**Comment by daiyousei-qz** [comment]
> Hmm, if the "workspace" is meant to be vscode's workspace concept, maybe we should consider just searching the workspace directories from the `initialize` request, where that concept has leaked into LSP already. At least we wouldn't need to add a new flag and require the user to sticky-tape this all together.
> 
> It would still be good to see some concrete examples of what this is for.

Say I have project A and B, both of which relies on a common code base C that is rather large so it couldn't just be duplicated. Because A and B are very different project and have different configurations, it would be great if we could configure the code base C with different clangd settings, depending on the opened project (A/B).

**Comment by daiyousei-qz** [comment]
To clarify, yes I meant vscode workspace. Searching from the workspace directories should also work, but it could cause priority problems. If a multi-root workspace is opened and each root directory has its own config file, we'll have to determine which file comes first.

**Comment by daiyousei-qz** [comment]
Actually, maybe instead of adding a new concept of workspace configuration, we could reuse the user configuration. So we could override the default user config file's location with some flags like "--user-config"?

**Comment by sam-mccall** [comment]
> Say I have project A and B

I'm not trying to be argumentative, but this isn't concrete. I don't think we should try to solve a problem if you're not willing to say what the problem is. This description gives enough detail to verify that your proposal solves it, but is too vague to evaluate alternatives. (Obviously no need to share any proprietary details, but...)

It sounds like C is a library. Are you developing the library or just using it? (for example, do you edit implementation files, just browse headers, or somewhere in between? Relevant because of possible overlap with TUScheduler::HeaderIncluderCache)

What are the main reasons that editing C in some generic config is worse than doing so in a way that depends what config you have open? e.g. does C have a lot of `#ifdef`s that mean different code is parsed in different configurations? (Relevant because as proposed there will be only one index for C, shared between both configurations).

> Because A and B are very different project and have different configurations

Roughly how are the projects different, how are the configurations different?

Relevant because e.g. if these these configuration differences are things common between users, we want to prefer solutions where the config can be checked in, that works the same way across editors, etc.

**Comment by HighCommander4** [comment]
> Relevant because as proposed there will be only one index for C, shared between both configurations

Not if you also use `--compile-commands-dir=<workspace>` in the clangd invocation, right?

**Comment by sam-mccall** [comment]
> > Relevant because as proposed there will be only one index for C, shared between both configurations
> 
> Not if you also use `--compile-commands-dir=<workspace>` in the clangd invocation, right?

Indeed, but now you need `A/compile_commands.json` to contain commands for all of `C`. Whether this is reasonable or not depends on what these things actually are.

(I'm really tempted by the idea of just reading `.clangd` from the workspace root if nothing closer matches - this would finally achieve AIUI the `--compile-commands-dir` + VSCode workflow without needing fiddly flag configuration. I think the main downside is we break users who are want to customize just that tree. A different name would solve this, `.clangd.workspace` file or something? but yuck...)

**Comment by daiyousei-qz** [comment]
Sorry for the confusion here. I think you could roughly think A=clangd, B=clang-tidy, C=clang.

> What are the main reasons that editing C in some generic config is worse than doing so in a way that depends what config you have open? e.g. does C have a lot of #ifdefs that mean different code is parsed in different configurations? (Relevant because as proposed there will be only one index for C, shared between both configurations).

Yes, C is a library that I'm developing. And I might need edit files across A, B and C. Because A and B have different targets, C is masked with many different `#ifdef`s. Compiling A provides a `#define PROJECT_A 1` and B is the same. Unfortunately, I don't have a build system that could generate the `compile_commands.json` for me. So, I have to use script to collect compilation flags from temp files after building targets and then merge them. Having a per-project config file could help me to specify different compilation database for different build targets instead of blindly merging all of them each time even though only one target is rebuilt. I have around 5 independent build targets :(

> Relevant because e.g. if these these configuration differences are things common between users, we want to prefer solutions where the config can be checked in, that works the same way across editors, etc.

Yeah, I agree. Using flags might not be as accessible. Though, considering there have been two issues (#845 and #1023) requesting this, it might be helpful at least to whom has access to editors that support customizing flags? For editors that don't support this, at least nothing harmful should happen. But any better solutions are welcome. :)

> Not if you also use --compile-commands-dir=<workspace> in the clangd invocation, right?

Yes, this is what I'm currently using. I'm currently periodically and manually update my `compile_commands.json` and I'm looking for ways to automate that.

> (I'm really tempted by the idea of just reading .clangd from the workspace root if nothing closer matches - this would finally achieve AIUI the --compile-commands-dir + VSCode workflow without needing fiddly flag configuration. I think the main downside is we break users who are want to customize just that tree. A different name would solve this, .clangd.workspace file or something? but yuck...)

That's also a valid solution, at least for me. But if the multi-root workspace has folder F1, F2, F3, where only F3 is the source tree. Considering if F1 and F2 both have config files in them, which config should come first and take priority for sources in F3? I'm not sure if arbitrarily choosing one is okay.

**Comment by daiyousei-qz** [comment]
Any update on this? Here's some proof-of-concept implementation on both approaches:
1. add an option --user-config: https://github.com/llvm/llvm-project/compare/main...daiyousei-qz:llvm-project:add-workspace-config-option
2. read from LSP initialize folders: https://github.com/llvm/llvm-project/compare/main...daiyousei-qz:llvm-project:read_config_from_ws_lsp (containing debug code and need polish, I just copied those paths from lsp request in its original order into config provider)

**Comment by florianhumblot** [comment]
I can add a use-case to this:
It is currently possible to set Inlay-hint settings in the .clangd file in your project root or in your home folder as a global clangd config. 
We're working in docker containers which don't have a guaranteed consistent home directory (since the development containers may be different for each project) and we'd like to check-in certain settings in the .clangd file but not others.

i.e. when using clangd as a language server for vscode for a cross-compiled project (compiling with arm-none-eabi-gcc) we need to disable the `-mthumb-interwork` flag to prevent errors from clang (not something we can change in the compile_commands, or we'd need two) but we have users that like the inlay hints and other users that don't. 

Making it so we can have a second user-specified config that gets merged (or takes precedence) over the default checked-in config file would make our lives easier :) 

(for our use-case I think that both options proposed by @daiyousei-qz would work)

**Comment by daiyousei-qz** [comment]
@sam-mccall @HighCommander4 Any suggestions on how should we move forward on this?

**Comment by HighCommander4** [comment]
I think giving clangd a command-line option to load a config file at a specific path would be simple and flexible. We don't need to give it a name like "workspace config" or try to constrain how it should be used. Users have diverse needs, and they can use it in different ways:

 * If users want to use it as a replacement for the default user config, e.g. because they don't like the location of the default user config, or can't rely on it (as in @florianhumblot's case above), or they don't like the ways available to customize that location (e.g. having to set environment variables like `$XDG_CONFIG_HOME`), they can do that.
 * If users want to use it in combination with the default user config, e.g as a "workspace-level" config (like in your scenarios), they can do that too.
 * If users want to specify multiple config files for some reason, they should be able to do that too by specifying the flag multiple times (config files would be applied in order of appearance).
 * Users who prefer to minimize per-invocation config (command-line args) don't need to use it at all!

This is just my personal opinion, I'm not any sort of authority here. It's Sam you need to convince :)

**Comment by HighCommander4** [comment]
@daiyousei-qz In the meantime, perhaps you might find this project interesting: https://github.com/eclipse-cdt-cloud/clangd-contexts

It seems to aim to solve similar issues to what you described above.

**Comment by daiyousei-qz** [comment]
Closing this as dup of https://github.com/clangd/clangd/issues/845
