### ISSUE TITLE
A way to interactively ask the user for input for a command

### ISSUE THREAD

**Issue by KKoovalsky** [clangd/clangd#1415]
Consider a `Command`, which is within a response of `document/codeAction` request made by the client. A simple example may be the `ExtractFunction` tweak command (https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp). The name of the extracted function is hard-coded to `extracted`, and there is no standard way, defined by the LSP specification, to resolve that interactively. Since the `ExtractFunction` tweak also supports method extraction, from within an out-of-line method definition, the user must perform a little more keystrokes to not only rename the method definition, but also the declaration, which resides in another file.

Could we come up with a non-standard solution which will allow performing an interactive operation to provide the name of the function? There are already some solutions in other LSPs: https://github.com/microsoft/language-server-protocol/issues/1164#issuecomment-1328930377. Here, the maintainer of the Dart VS Code extension introduced one more field within the `Command->arguments` field. The field is called `arguments` too. The optional `data` field of the `CodeAction` is used, where the `parameters` field is introduced to allow the client performing the interactive action. The client announces to the server through `ClientCapabilities->experimental`, that it is able to handle some specific kinds of interactive action.

Would it be hard to introduce a feature like this?

**Comment by kadircet** [comment]
> The name of the extracted function is hard-coded to extracted, and there is no standard way, defined by the LSP specification, to resolve that interactively. 

For such cases you can actually use the `Rename` functionality. but in general you're right. unfortunately such an interactive "command execution" workflow is something we've desired and looked for in the past as well.

> Would it be hard to introduce a feature like this?

Surely it can be done as an "extension", but it would imply not only the server but clients also needs to agree and implement this extension. For clangd we have a vscode plugin that we maintain in a "best-effort" manner, hence we can't really invest much resources into implementing such extensions and adoption by other LSP clients (for other editors) are questionable, as most lack the UI for such interactions (and implementing it just for the sake of clangd wouldn't really be a high priority task for most maintainers).

So from our side the only feasible way would be to implement such features after it is somewhat standardized or there are proposals adopted by other LSP clients. This wouldn't be really complicated on the server side (especially for code actions, since it's already a two step action and we've infra in clangd-server side to propagate parameters from second request) but more of an issue on the client side (all the extra UI elements and state propagation).

Hence closing this for now, please do re-open if there are any changes on the LSP/clients.
