### ISSUE TITLE
clangd complains about some intrinsic gcc headers but compiles fine

### ISSUE THREAD

**Issue by ezoiljy** [clangd/clangd#1432]
I have the exact same problem with issue #1203 but I also have the issue of https://github.com/clangd/vscode-clangd/issues/425 so I have no choice but to use `--query-driver`. My problem is how to stop clangd from complaining?

**Comment by HighCommander4** [comment]
My first suggestion would be to double-check that the first workaround from [this comment](https://github.com/clangd/clangd/issues/1394#issuecomment-1328676884) doesn't work, since that would avoid needing `--query-driver`. Have you tried installing the `g++-12` package? What happens when you do that?

Otherwise, if you're stuck with `--query-driver`, my best suggestion would be to suppress diagnostics as discussed in [this comment](https://github.com/clangd/clangd/issues/1203#issuecomment-1177245341), for example by creating a `.clangd` file in your project's root directory containing:

```
Diagnostics:
  Suppress: builtin_definition
```

**Comment by ezoiljy** [comment]
Thanks. The g++-12 solution works for me. Although it caused a missing 'stddef.h' error, it turns out that I did not install clangd properly (I use the binary of a new release but did not copy the regarding header files into the right place)
