### ISSUE TITLE
Ignore the user clangd configuration file when there is .clang-tidy or compile_commands.json

### ISSUE THREAD

**Issue by v1nh1shungry** [clangd/clangd#1434]
A compile_commands.json can tell the C++ standard and warning options. But a user clangd configuration file can override them. Say the project's compile_commands.json tells that the C++ standard is C++11, but the user clangd configuration file tells there is a `-std=c++20` in the `CompileFlags`, clangd then doesn't produce diagnostics if I use C++20 features.

I usually just run `nvim main.cpp` to check a quick thought. And I use a user clangd configuration file to provide clangd with compile options in such a standalone mode. I don't know how to provide compiler flags and clang-tidy checks when editing a single C++ file without a user clangd configuration file. But it is annoying that the user clangd configuration file will affect the projects with compile_commands.json provided by something like CMakeLists.txt. And I don't think this makes sense.

I'd appreciate it if anyone has a better idea to solve the problem without modifying clangd.

**Comment by HighCommander4** [comment]
One idea might be to have a directory (like say `~/scratch`) where you put loose files like `main.cpp` that are not part of any project (and do not put any projects with `compile_commands.json` in that directory tree), and put things like `-std=c++20` into a `.clangd` file in that directory (rather than the user config).

**Comment by v1nh1shungry** [comment]
> One idea might be to have a directory (like say `~/scratch`) where you put loose files like `main.cpp` that are not part of any project (and do not put any projects with `compile_commands.json` in that directory tree), and put things like `-std=c++20` into a `.clangd` file in that directory (rather than the user config).

This sounds like a not-bad solution.

While I insist on

> But it is annoying that the user clangd configuration file will affect the projects with compile_commands.json provided by something like CMakeLists.txt. And I don't think this makes sense.

feel free to close this issue if you think the current version is better.

Thanks!

**Comment by sam-mccall** [comment]
Fundamentally it's hard to make the config file apply when there's no compile_commands.json etc, because the config file defines how to search for compile_commands.json.

**Comment by v1nh1shungry** [comment]
> Fundamentally it's hard to make the config file apply when there's no compile_commands.json etc, because the config file defines how to search for compile_commands.json.

Maybe it's better to dismiss the corresponding config options? For example, if there is .clang-tidy then ignore the `Diagnostics.ClangTidy` option. If there is a compile_commands.json then ignore the `CompileFlags.CompilationDatabase` option.

**Comment by sam-mccall** [comment]
Sure, this request isn't *impossible* to satisfy.

What I'm saying is that when evaluating a feature, we consider costs/benefits, and the costs of this feature are high because it requires a substantial redesign.

The benefits seem modest: we remove some modest friction from a workflow that isn't overwhelmingly common (based on reports).

We do make small changes to bring modest improvements all the time, but as this requires a large change i think we shouldn't attempt it.

**Comment by v1nh1shungry** [comment]
Got it. I respect your concern. Thanks for the reply!

**Comment by sam-mccall** [comment]
Thanks, likewise! Sorry not have better news
