### ISSUE TITLE
Clangd does not resolve include, in spite of correct include path being present in compile command

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#147]
I am trying out clangd in a large codebase for the first time.

It works fine for many files, but for some files, clangd fails to resolve many #includes (and consequently many symbols) in the file.

I am using vscode as the client, and when I open an affected file, in the Output view I see the expected:

```
I[<timestamp>] Updating file <filepath> with command [<directory>] <command>
```

The `<directory>` and `<command>` there look correct, and the `<command>` contains the expected `-I` directives.

If I go to `<directory>` in a terminal and run `<command>`, it succeeds (no diagnostics about unresolved includes or anything else).

If I edit `<command>` to replace the compiler path with the clang executable from the same installation as clangd, it still succeeds (no diagnostics about unresolved includes and no errors of any kind; I do get a couple of warnings this time).

So, I don't understand why clangd is failing to resolve the includes. Any suggestions for how I can diagnose this further?

**Comment by kadircet** [comment]
Hi Nathan,

Are those includes from project itself, or headers coming from toolchain/built-in like stddef, iostream etc. ?

Figuring out includes are rather handled by HeaderSearch in clang. You can try digging into that component. Apart from that, we could have a look if you could provide a repro. It should be enough to mimic directory structure and a compile_flags.txt.
That approach should also help you in case you want to dig it yourself.

**Comment by HighCommander4** [comment]
Taking another look, I see that the includes that can't be resolved are the ones that are located in the same directory as the source file and included via a simple `#include "Filename.h"`, rather than ones in directories specified by `-I` flags. This suggests that the problem is related to clangd's handling of the "current directory" when processing a command.

I will try to prepare a repro.

**Comment by kadircet** [comment]
If that's the case, you shouldn't be seeing diagnostics saying "file not found", the problem with relative includes was coming up when we wanted to insert a header after a completion. Also we've send fixes for that, but might've missed something.

Apart from that clangd should be able to parse the file correctly.

**Comment by HighCommander4** [comment]
Ok, here is a minimal repro: [clangd-issue-147.zip](https://github.com/clangd/clangd/files/3587821/clangd-issue-147.zip)

Steps to repro:

  1. Extract the zip file into `/tmp`.
  2. Run `code /tmp/clangd-issue-147/src` (with `clangd` present in the `PATH`).
  3. Open `Foo.cpp`. Observe that `#include Foo.h` is not resolved.

The unusual thing about this project setup which is likely related to the problem is that, to improve build speeds, source files in the source directory are aggregated into "unified source files" in the build directory which `#include` the original source files, and it's these unified source files which are compiled.

**Comment by kadircet** [comment]
Yes, this is a known issue and requires a lot to be changed in clangd, you can see a similar issue in #45 . Even though files are self-contained in your case, we still can't find the include because clangd overrides main file contents of the compiler invocation with the current file you are editing.

So we are telling the compiler that it is gonna compile the translation unit `build/Unified1.cpp` with file contents:
```cpp
#include "Foo.h"
....
```

And it fails because Foo.h doesn't exist in any include directories provided or the same directory as `build/`. You can try:
- putting those unified files in src directory, this will help resolve includes relative to current directory
- changing the name field to "unified1.cpp" in compile_commands.json, this will result in clangd inferring compile commands for "foo.cpp" from "unified1.cpp" while making necessary file{name,path} changes.
then clangd should (mostly) work as long as you keep your header/source files self-contained.

**Comment by vbs100** [comment]
Maybe same problem so I add here and want to know how to config the clangd/vscode-clangd.

when I use it to learn boost, it fail as:
"'boost/intrusive/list.hpp' file not found with <angled> include; use "quotes" instead"

when I change <angled> include to "quotes" include 
#include <boost/intrusive/list.hpp>
#include "boost/intrusive/list.hpp"
then it fails with 
"'boost/intrusive/detail/config_begin.hpp' file not found" 
the line in boost/intrusive/list.hpp.

source code:
https://www.boost.org/doc/libs/1_71_0/doc/html/intrusive/usage.html#intrusive.usage.usage_both_hooks

system: 
win7 x64/vsode/vscode-clangd/mingw64

compile_flags.txt:
--target=x86_64-w64-mingw32
-std=c++17
-I d:\cpp\boost_1_71_0

**Comment by kadircet** [comment]
does the compile_flags.txt you mention also governs the d:\cpp\boost_1_71_0 directory ?

Also in which file you are seeing those errors exactly? Directory layout plays an important role in these cases, so we could provide more info if you can specify that.

**Comment by vbs100** [comment]
> does the compile_flags.txt you mention also governs the d:\cpp\boost_1_71_0 directory ?
> 
> Also in which file you are seeing those errors exactly? Directory layout plays an important role in these cases, so we could provide more info if you can specify that.

hi kadircet,

my workspace is d:\test, compile_flags.txt is in this directory
I have try copy d:\cpp\boost_1_71_0\boost to d:\test and use -I . in compile_flags.txt , but it still can't find the included header.

when I use angled include the error exist in the source file, and when I use quote include , it can locate the  boost/intrusive/list.hpp,  but fail at list.hpp because the first include line is 
#include \<boost/intrusive/detail/config_begin.hpp\>
then log with "'boost/intrusive/detail/config_begin.hpp' file not found"

**Comment by kadircet** [comment]
Actually reading this again, clangd would actually work for this example if the filename mentioned in the compile_commands.json was for Unified1.cpp, rather than Foo.cpp. Current database:

```
[
  {
    "directory": "/tmp/clangd-issue-147/build",
    "command": "clang++ -c -o /dev/null Unified1.cpp",
    "file": "/tmp/clangd-issue-147/src/Foo.cpp"
  }
]
```

Hence clangd assumes this entry indeed belongs to `src/Foo.cpp` and don't try to interpolate the entry for `src/Foo.cpp`. If the `File` said `build/Unified1.cpp` instead, we would transfer the command to apply to Foo.cpp and everything would work.

Is this compilation database generated by some default build system like cmake?

**Comment by HighCommander4** [comment]
> Is this compilation database generated by some default build system like cmake?

In my case, no, it's generated by a custom python script.

We've already modified the script to generate entries that look like this:

```
  {
    "directory": "/tmp/clangd-issue-147/build",
    "command": "clang++ -c -o /dev/null /tmp/clangd-issue-147/Foo.cpp",
    "file": "/tmp/clangd-issue-147/src/Foo.cpp"
  }
```

I understand that the following would also work:

```
  {
    "directory": "/tmp/clangd-issue-147/build",
    "command": "clang++ -c -o /dev/null Unified1.cpp",
    "file": "/tmp/clangd-issue-147/build/Unified1.cpp"
  }
```

but I'm not sure what the advantage would be. (In particular, if there are include-what-you-use errors in `Foo.cpp` due to implicit dependencies on declarations from previously-included `.cpp` files in `Unified1.cpp`, they would show up with either approach.)

**Comment by kadircet** [comment]
> but I'm not sure what the advantage would be. (In particular, if there are include-what-you-use errors in Foo.cpp due to implicit dependencies on declarations from previously-included .cpp files in Unified1.cpp, they would show up with either approach.)

You are totally right, I was just trying to say that working with unity builds vs working with non-self-contained files are two different problems, and clangd can actually work with unity builds even when there's only a single entry in compile_commands.json for the jumbo translation unit. If I am not missing something this issue is particularly about that, and clangd is currently working in those cases. So I actually came here to close the issue :)

The problems related to non-self-contained files should be tracked by #45 instead. Please re-open if you disagree and there are other things we can do about this issue (i.e. clangd not working with unity builds even when individual files are self contained).

**Comment by HighCommander4** [comment]
I think you're right, there isn't anything to change in clangd here other than #45. Thanks.
