### ISSUE TITLE
clangd-indexer asserts with "We assume that the input buffer has a null character at the end"

### ISSUE THREAD

**Issue by Patosga** [clangd/clangd#158]
I am trying to index my project in an attempt to make clangd faster. At `[275/1125]` I get the following error:

```clangd-indexer: /home/user/drive/llvm/llvm-project/clang/lib/Lex/Lexer.cpp:87: void clang::Lexer::InitLexer(const char*, const char*, const char*): Assertion `BufEnd[0] == 0 && "We assume that the input buffer has a null character at the end" " to simplify lexing!"' failed.
[276/1125] Processing file ....cpp
 #0 0x00005555aa6711d5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/user/drive/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:532:0
 #1 0x00005555aa671268 PrintStackTraceSignalHandler(void*) /home/user/drive/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:593:0
 #2 0x00005555aa66f121 llvm::sys::RunSignalHandlers() /home/user/drive/llvm/llvm-project/llvm/lib/Support/Signals.cpp:68:0
 #3 0x00005555aa670b8c SignalHandler(int) /home/user/drive/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:384:0
 #4 0x00007fd4346cb890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #5 0x00007fd433580e97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #6 0x00007fd433582801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #7 0x00007fd43357239a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #8 0x00007fd433572412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)```

**Comment by kadircet** [comment]
The recommended indexing method is `background-index` nowadays, which can be enabled by passing `-background-index` into clangd. That aside, indexing won't really make clangd faster. What are you trying to achieve exactly?

**Comment by Patosga** [comment]
I wanted to make a comparison between `background-index` and `clangd-indexer`. 

I am very new to the tool and I am trying to find out the best configuration for me. I find `clangd` to struggle a little bit with the dimension of my project and wanted to create the index only once. I guess `clangd --compile-commands ... --background-index` is all I need? 

I believe the results of `--background-index` go into `/.clangd` and that that has almost the same effect as what I was trying to achieve with  `clangd-indexer`?

Pardon my ignorance.

**Comment by kadircet** [comment]
well if you want speed you should definitely go with `background-index`, because it builds incrementally(will only index files that have changed since last indexing) whereas `clangd-indexer` will run from scratch every time.

As for a comparison they both improve the quality of code navigation and completion, but background-index is a lot more automated compared to clangd-indexer. With the latter you must trigger indexing every now and then, and also tell clangd about where the index file is.

> I believe the results of --background-index go into /.clangd and that that has almost the same effect as what I was trying to achieve with clangd-indexer?

Yes, but you shouldn't care about where the index shards go into. Clangd will find and load them automatically if you've passed `--background-index`
