### ISSUE TITLE
[vscode client] Should package.lock.json be under version control?

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#161]
Every time I build clangd-vscode locally, the `package-lock.json` file is modified.

I assume it's undesirable for me to submit modifications to this file as part of a patch to clangd-vscode, unless my patch actually introduces a new dependency or increases the required version of one.

But in that case, should this file be under version control in the first place? Or are the local modifications unexpected, indicating a problem with my workflow? (I run `npm install` followed by `npm run package`.)

**Comment by ilya-biryukov** [comment]
It's a common practice to submit `package-lock.json` file to ensure everyone who builds the package gets the same versions of its dependencies.

See https://stackoverflow.com/a/44210813.

I'm not sure why it gets updated for you, don't have a high level of expertise with JS tools.

**Comment by hokein** [comment]
It turns out that we forgot to update the `package-lock.json` when updating the `package.json`.

I don't know how much value of keeping it in the repository, though the best practice is to commit this file in the code repo. I found that the change of this file is usually large and create a lot of noise when seeing the diff.

**Comment by hokein** [comment]
I have updated the `package-lock.json`, now there should be no local modifications after you run `npm install`.
