### ISSUE TITLE
bugprone-unchecked-optional-access crashes clangd

### ISSUE THREAD

**Issue by KonstruktiveInterferenz** [clangd/clangd#1878]
The code snippet below causes the clangd binary fetched by the clangd VSCode extension to hang or crash when using the **bugprone-unchecked-optional-access** check.

This happens with the version 16 and 17 of the clangd-binary used by the VSCode extensions under Windows as well as under Linux.

Sometimes the binary simply crashes or it hangs while using 100% CPU.

The original code was quite extensive and the version below is the smallest set of code where the issue could be reproduced. Taking one of the lines (not doing anything useful) away caused the issue to disappear.

~~~cpp
#include <optional>

namespace ns {
  struct Class
  {
    static bool staticMethod(bool i);
  };
}

namespace ns {

bool Class::staticMethod(bool i) {

  auto lambda = []() -> std::optional<bool> { return {}; };

  for (auto t : "") {
  }

  auto someOptional = lambda();
  auto someChars = "T";
  auto someNumber = 12;

  if (someOptional) {
  }

  if (someNumber == 0) {
  }

  for (std::size_t j = 0; j < 2U; ++j) {
  }

  return true;
}

}
~~~

**Comment by HighCommander4** [comment]
This is an upstream bug in the checker implementation. https://github.com/llvm/llvm-project/issues/55530 is on file for it. I'm going to close this as a duplicate, but you may want to consider posting your reduced testcase to that issue, in case it helps investigate it.

In clangd 18 this checker will be blacklisted due to its instability.

In earlier versions of clangd, by adding the following to `.clangd`:

```yaml
Diagnostics:
  ClangTidy:
    Remove: bugprone-unchecked-optional-access
```
