### ISSUE TITLE
Clangd sometimes can't display typedef documents

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#189]
```c++
// foo
struct foo {};

// typedef foo
typedef foo typedef_foo;

// typedef named struct
typedef struct bar {} typedef_bar;

// typedef unnamed struct
typedef struct {} typedef_unnamed;

// using named struct
using using_foo_bar = struct foo_bar {};

// using unnamed struct
using using_unnamed = struct {};


int main() {
    foo a; // works fine.
    typedef_foo b; // works fine.
    bar c; // works fine.
    typedef_bar d; // document not displayed when hovering.
    typedef_unnamed e; // document not displayed when hovering.
    using_foo_bar f; // works fine.
    foo_bar g; // works fine.
    using_unnamed h; // works fine.
}
```

**Comment by sam-mccall** [comment]
Clang's heuristic is basically "take the comment before the decl, unless there's something in between". The "something" is supposed to be a decl, PP directive, stmt etc but it's any character in `";{}#@"` and it's the { that's tripping us up here.

Removing `{}` would result in this comment applying to `x`:
```// doc comment
void foo() {}
typedef int x;```

(Interestingly `typedef struct bar typedef_bar` has the opposite effect: `bar` gets no docs and `typedef_bar` gets them. This is because the `{}` is gone, but `getDeclLocForCommentSearch` prevents locations being generated for declarations inline in declarators...)

**Comment by sam-mccall** [comment]
It seems fine to me to always use the `typedef` (or `using`) keyword as the location for comment lookup purposes here.

**Comment by tauchris** [comment]
@sam-mccall ,  could you take a quick look at https://bugs.llvm.org/show_bug.cgi?id=44143, which is a regression caused by the changes made for this issue?  I'm happy to implement and test a fix, but I don't yet understand that code well enough to know where it should go.

It seems there are two different issue-reporting systems -- did I make a noob mistake and choose the wrong one?  :-/
