### ISSUE TITLE
Display the type of template parameter when hovering over the template function

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#190]
```c++
template <typename T> void foo(T t);

int main() {
    foo(5); // hovering on foo
}
```

1. Current behaviour
![image](https://user-images.githubusercontent.com/10697249/68380880-a21b4700-018b-11ea-8c74-844a2f055f53.png)
2. Expected behavior
```c++
template <> void foo<int>(int t)
```

**Comment by kadircet** [comment]
Clangd would do that for explicit template specializations, why do you think it would be better to show implicit instantiation rather than the template decl in such cases?

**Comment by lh123** [comment]
> Clangd would do that for explicit template specializations, why do you think it would be better to show implicit instantiation rather than the template decl in such cases?

I think we show both the implicit instantiation, and the template decl.

Because display the actual type of template parameter can help template meta-programming.

maybe relative: #58

**Comment by lh123** [comment]
It seems that case 1 has been implemented.
![image](https://user-images.githubusercontent.com/10697249/71246749-462f0b00-2352-11ea-994d-d3d57ae104d4.png)

I think signature help also need modify.
![image](https://user-images.githubusercontent.com/10697249/71246767-52b36380-2352-11ea-8576-eca65086788c.png)

**Comment by kadircet** [comment]
the signature help behavior is actually intentional.

it might be helpful in such simple cases to show instantiation, but can become annoying easily if the instantiation is long/nested. For example string -> std::basic_string<char>.

it is somewhat related to https://github.com/clangd/clangd/issues/229, as it might require us to come up with a way to "pretty print" those types.
after that it should be mostly OK to print instantiations in signature help as well.

**Comment by kadircet** [comment]
Closing this as the hover behaviour is implemented now and the signature help behaviour is kept as-is due to reasons mentioned above.
