### ISSUE TITLE
go-to-definition: the symbol definition is incorrectly overridden when a new file containing the same definition is opened

### ISSUE THREAD

**Issue by ariel-miculas** [clangd/clangd#206]
Reproduction (I'm using vim with the YouCompleteMe plugin compiled with clangd):
Open a file, navigate to the symbol definition using `GoToDefinition` (the correct file is opened (`file_1`), the one indexed using the compilation database).
Go back, navigate to the symbol definition using ctags (it opens the definition in another file, `file_2`).
Go back, navigate to the symbol definition with `GoToDefinition`.
Expected behavior: open the definition in `file_1`, since that's the indexed file, present in the compilation database.
Observed behavior: it opens the definition in `file_2`, which is not indexed and not part of the project.

clangd version 9.0.0 (tags/RELEASE_900/final)

**Comment by kadircet** [comment]
clangd has 2 different indexes, one gathered by indexing entries in compilation database, and the other gathered by indexing the files you are currently editing.

The second one is used to overlay the first one, as it is fresher and we don't associate that index data  with a compilation database. Therefore it overrides the definition even if irrelevant to the project.

Adding this association logic would require a lot of work, and this problem should occur pretty rarely(as users don't have a way provided by clangd to open those files). We might consider dropping symbols in such cases though.

**Comment by kingarley** [comment]
* Have you considered returning all the definitions found for a symbol?
* Is there a way to interact with these 2 indexes, or are they internal to clangd?

**Comment by kingarley** [comment]
Here's my intended use case, so you can understand my problem and you can judge whether the current behavior can be classified as an issue:
I have some source files in `/path_1/source_dir`. These get copied in `/path_2/build_dir` by the build system. The build system also generates the compilation database.

I want to be able to navigate to the definition of `symbol_a` in `source_dir`. For this purpose, I use `ctags`. This is convenient since I need to do the changes to the source file in `source_dir`.

I also want to be able to navigate to the definition of `symbol_a` in the `build_dir`. For this, I want to use `clangd`'s feature of being able to parse the compilation database and to use `go-to-definition`.

However, I cannot use `go-to-definition` reliably because if I navigate to the definition of `symbol_a` using ctags, subsequent `go-to-definition` commands won't open the definition in `build_dir`, they will open the definition in `source_dir`. That's the current behavior based on my observations and explained by the overlay functionality that you've described.

Is there any workaround so that `clangd`'s `go-to-definition` will always get me to the definition in `build_dir`?
