### ISSUE TITLE
Cannot disable BlockEnd inlay hints

### ISSUE THREAD

**Issue by soumen-ghosh** [clangd/clangd#2250]
My project level settings.json is like following:

    "C_Cpp.intelliSenseEngine": "disabled",
    "C_Cpp.formatting": "clangFormat",
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.clang_format_fallbackStyle": "Microsoft",
    "C_Cpp.clang_format_path": "<path to `clang-format` binary>",
    "clangd.path": "<path to `clangd` binary>",
    "clangd.arguments": [
        "-log=verbose", 
        "-pretty", 
        "--background-index", 
        "--background-index-priority=low",
        "--clang-tidy",
        "--enable-config",
    ],
In the .clangd file at project level, I have added followings:

InlayHints:
  Enabled: Yes
  **BlockEnd: No**
  Designators: No
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 0

However, I am still getting inlay hints at block end for C++ files. What am I missing?

I am using VS Code from windows with remote connection. I have clangd extension installed and clangd version in remote machine is 19.1.0

**Comment by HighCommander4** [comment]
One think to check: perhaps you have a **user config file** (see https://clangd.llvm.org/config.html#files for the paths) which contains `BlockEnd: Yes`?

User config takes precedence over project config as described [here](https://clangd.llvm.org/config.html#loading-and-combining-fragments), so that could explain it.
