### ISSUE TITLE
Background index does not store reference counts

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#23]
I have a background index of LLVM and the count of references for `std::unique_ptr` is always 0.
Not sure about the exact details, but it's clear our design does not allow to store reference counts properly.
In particular, we aim to store each symbol in the slab, corresponding to the file for the symbol declaration, so we don't have a way to increment the reference counts when processing translation units that don't write the corresponding slab.

**Comment by ilya-biryukov** [comment]
@kadircet suggested we could reconstruct the reference counts while loading the reference slabs.
This should work, maybe we should even go further and stop serializing the reference counts altogether, relying on the references to reconstruct it instead?

**Comment by kadircet** [comment]
Removing this field would require some changes in clangd-indexer, since it only has one refslab for whole project rather than one refslab per file. But it is still doable, we can go over occurences of each symbol and count number of different files. It would cause some increase in loading time though.

**Comment by kadircet** [comment]
https://reviews.llvm.org/D59481

**Comment by kadircet** [comment]
fixed with rL360344
