### ISSUE TITLE
go-to-def not work when using trailing-return-type

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#250]
```c++
template <typename T, typename U>
auto add(const T &t, const U &u) -> decltype(t + u);
//             ^  ^        ^  ^              ^ go-to-def and rename doesn't work.
```

**Comment by kadircet** [comment]
this is not just about trailing return types but basically any expression inside `decltype`.

Looks like DecltypeTypeLoc is missing the sourcerange information for its expression and parentheses(there are fixmes around about that as well https://github.com/llvm-mirror/clang/blob/master/include/clang/AST/TypeLoc.h#L1887).

We can either try and fix that, or patch it up in clangd specifically to update endpoint for decltypetypelocs.

minimal repro:

```
int a
decltype([[^a]]) b;
```

selects vardecl, instead of the declrefexpr inside decltype.
