### ISSUE TITLE
Add support for inline parameter hints

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#313]
Some IDEs have a feature called "inline parameter hints", where the client renders annotations showing parameter names inline in function calls.

Screenshot to illustrate:

![image](https://user-images.githubusercontent.com/1751085/77122266-8fefc600-6a13-11ea-9834-58d5930250be.png)

It would be really neat if clangd supported this (as an extension at first, until this gets added to LSP).

**Comment by Trass3r** [comment]
There is an LSP proposal: https://github.com/microsoft/language-server-protocol/issues/956

**Comment by HighCommander4** [comment]
I've been working on an implementation of this.

**Comment by HighCommander4** [comment]
I have some initial patches up for review:

 * Server side: https://reviews.llvm.org/D98748
 * Client side (vscode): https://github.com/clangd/vscode-clangd/pull/168

**Comment by HighCommander4** [comment]
The server-side support has now landed, in case anyone's interested in trying it out in vscode by applying the client-side patch locally, or developing client support for a different editor.

**Comment by HighCommander4** [comment]
Just wanted to post an update that the latest clangd trunk contains support for both parameter hints and type hints, and the latest vscode client has the client-side support required to use them as well.

The feature currently requires opt-in via the `--inlay-hints=true` command-line parmeter to clangd.

Any feedback is welcome.

**Comment by Curve** [comment]
Hey, just wanted to let you know that the inlay hints work amazing!

Except for some special use cases, for example for explicitly instantiation, this will mess up the inlay hints as shown here:

![image](https://user-images.githubusercontent.com/37805707/133829009-ab854fa7-fd4f-4c71-a48c-64c0cf18cb9b.png)
![image](https://user-images.githubusercontent.com/37805707/133829040-83bae14d-9ad4-4088-8544-7cda676aa627.png)

However moving the instantiation above the actual implementation will fix the problem:
![image](https://user-images.githubusercontent.com/37805707/133829107-0de5c189-9dcf-49ca-82d5-7cd6537e9e84.png)

**Comment by HighCommander4** [comment]
@Curve thanks for the report! Proposed fix [here](https://reviews.llvm.org/D110051)

**Comment by shahamran** [comment]
Hi. Really enjoying inlay hints, thanks :)
I have a small suggestion: when passing arguments as (non-const) reference, it's useful to have an inlay hint that makes this apparent. CLion does it, that's how I got the idea.
Example:
```cpp
class Foo {};

void update(const Foo &fooIn, Foo &fooOut) {
  return;
}

int main() {
  Foo fooIn, fooOut;
  update(fooIn, fooOut);
  // expected:
  // update(fooIn, &:fooOut);
  //               ^ (inlay hint)
  return 0;
}
```

**Comment by HighCommander4** [comment]
@shahamran: While we don't have an inlay hint for it, we did recently add a semantic highlighting modifier for arguments passed by non-const reference, see #839.

**Comment by Curve** [comment]
> @Curve thanks for the report! Proposed fix [here](https://reviews.llvm.org/D110051)

Thanks for the quick response!

I also want to mention that I really like the idea of @shahamran, it would be great addition

**Comment by sam-mccall** [comment]
@HighCommander4 I think it's time we exposed this properly, in time for clangd 14:
 - expose the capability without a flag
 - commit to keeping interface compatibility
 - commit to keeping this for several release cycles after a standard one becomes available
 - document the protocol extension
 - expose the option in the vscode extension and others

I wanted to push for having the protocol standardized first but it seems like this isn't going to be stable until VSCode people make a call (even if I do a bunch more TS stuff).

**Protocol-wise:**
In addition to rust's protocol (range, kind, label) and ours (matches rust), there's now [one in typescript-language-server](https://github.com/typescript-language-server/typescript-language-server#typescriptinlayhints-experimental-supported-from-typescript-v442) which is (position, kind, text) plus some cruft.

- **range vs position**: I'd propose both. I think it's very unlikely that range gets standardized as part of inlay hints per se - VSCode doesn't have it, tsserver doesn't have it, feedback from https://github.com/microsoft/language-server-protocol/pull/1249#issuecomment-829988269 is that this is a different feature (and I doubt it'll be as high-priority). And the "display left/right" issue is unresolved. Nevertheless exposing both keeps our options open, make it easy to adapt clients that know either rust's or TS's protocol, etc.
- **label vs text**: label. it's a silly distinction, but I think "label" is much more likely to be standardized because VSCode seems settled on it.
- **category vs kind**: kind. I think category is a more precise name but all the impls use kind.
- **kind values**: If we're not going to be totally compatible with rust-analyzer or back-compatible with our current version, I think we should drop the `Hint` suffix as typescript does. So `"Type"`, `"Parameter"` etc.
- **response object**: InlayHint[]. TS wraps their response in an object which is sensible forward-compat but I expect we'll move to a standard protocol before this is an issue, so keep it simple.

So this would leave:

```
clangd/inlayHints : InlayHintsParams => InlayHint[]
InlayHintsParams {
  textDocument: TextDocumentIdentifier
  range?: Range
  only?: string[]
}
InlayHint {  
  label: string
  position: Position
  range?: Range
  kind: string
}
```

Alternatively we could try harder to stay compatible with our current thing, which would mean "label" rather than "text" and keeping the bulkier "kind" values.

WDYT?

**Comment by HighCommander4** [comment]
@sam-mccall sounds reasonable. A bit unfortunate that standardizing the protocol is taking a while, but I agree there's value in making this available to users by default, and we've done something similar with semantic highlighting. (Though it has caused some lingering confusion, with some users asking even today why `clangd.semanticHighlighting` doesn't control semantic highlighting today. Not sure if there's a good way around that...)

I'm on vacation for another week or so, but I'm happy to whip up a patch afterwards. Do you know what the expected timeframe is for llvm 14 branching?

**Comment by sam-mccall** [comment]
@HighCommander4 I'm happy to put together a patch if you're on board in general. Branch is likely the [4th week of january](https://reviews.llvm.org/D95114) apparently.

Agree the semantic highlighting is a bit of a cautionary tale, but not a disaster. I don't know how long we'd be waiting and I'm not sure I have the right skills to make it go faster :-)

I went for a walk and thought more, and I think it's not worth breaking even the VSCode client in order to rename label/kinds. We can do that when we ship the standard thing. So "text" and "ParameterHint" etc still, but add "position" in addition to "range".

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D116699 will apply those changes and turn the flag on by default.

I've marked it as closing this bug because at that point we'll have server support and client support (in vscode) both on by default. Three cheers to @HighCommander4!

---

There's one more thing I'd like to do before the 14 cut: give users the ability to turn on/off the feature and particular categories in the config file. Config is per-file and dynamic whereas capabilities are global and set on startup, so this would mean we always advertise the capability and then (quickly) return no hints if the feature is turned off.

**Config idea (terse)**
```
<empty>                       # default categories on
InlayHints: No                # off
InlayHints: Yes               # all categories on
InlayHints: parameter         # one category
InlayHints: [parameter, type] # listed categories

# Problem: no syntactic space for other options
# Problem: disable a category only by listing all others
# Problem: if you do that, then newly added categories not be enabled
```

**Config idea (verbose)**
```
<empty>                                             # default categories on
InlayHints: { Enable: No }                          # off
InlayHints: { Enable: Yes }                         # default categories on
InlayHints: { Enable: Yes Kind: parameter }         # one category
InlayHints: { Enable: Yes Kind: [parameter, type] } # listed categories

# Problem: a bit verbose/reundant
# Problem: same problems as terse with disabling options
```

**Config idea (tidy-like)**
```
<empty>                                                # default categories on
InlayHints: { Disable: '*' }                           # off
InlayHints: { Enable: '*' }                            # all categories on
InlayHints: { Disable: '*' Enable: parameter }         # one category
InlayHints: { Disable: '*' Enable: [parameter, type] } # listed categories
InlayHints: { Enable: parameter }                      # default + one category
InlayHints: { Disable: parameter }                     # default - one category

# Problem: verbose in most cases
# Problem: explicitly listing categories is very ugly
```

**Config idea (negative)**
```
# Terse version
<empty>                               # all categories on
InlayHints: {Hide: Yes}               # off
InlayHints: {Hide: parameter}         # all - one category
InlayHints: {Hide: [parameter, type]} # all - listed categories

# Problem: any newly-added category must be on by default
# Problem: select category only by listing all others
```

**Comment by Trass3r** [comment]
Why not just a `-` prefix to disable, like in clang-tidy checks config?

**Comment by sam-mccall** [comment]
> Why not just a - prefix to disable, like in clang-tidy checks config?

Well, personally I always found the clang-tidy glob-list cryptic and hard to reason about: it's a complicated model (same as tidy-like) but with magic syntax. Concretely in YAML, `-` is a special character, which leads to:

```
# enables bar
foo:
  - bar

# disables bar
foo:
  -bar
```

Actually I think I missed the most obvious option:

**Config idea (categories are keys)**
```
InlayHints:
  Enabled: Yes       # yes is default, no disables everything
  Parameter: Yes     # adjust per-category default
  Type: No
# Problem: no way to enable _all_ categories?
```
This is not pretty readable and leaves room to add more config at the feature level and at the category level.
(Which seems maybe useful looking at [resharper options](https://i.stack.imgur.com/ZKPHw.png))

**Comment by sam-mccall** [comment]
> range vs position: I'd propose both. I think it's very unlikely that range gets standardized as part of inlay hints per se - VSCode doesn't have it

I'm way less certain than I was yesterday: https://github.com/microsoft/vscode/commit/e32cdfd97c65a5b07af98d05009fd0743e30d4e9

**Comment by kadircet** [comment]
Regarding config ideas, i feel like the `categories are keys` option is looking more promising. The only problem is enabling/disabling all (depending on what we chose as the default) as you mentioned.

So what about making `Enabled` act like the default for all kinds of inlay hints (and probably rename it to `All` or something) and then users can enable/disable the specific kinds of inlay hints they want (this option sounds quite similar to tidy-like config idea, but I think it's a lot more expressive and readable)

**Comment by sam-mccall** [comment]
Sounds like we're getting closer :-)

I think if we can we should (eventually) have most categories on by default, but have some (either marginal or in-development) off by default.
So probably turn-everything-on and turn-everything-off are **both** interesting non-default states.

> So what about making Enabled act like the default for all kinds of inlay hints (and probably rename it to All or something)

Definitely an idea. The downsides I see are:

- I think you do have to rename it, but I can't think of a name will read as naturally as `Enabled`. (The main use case is disabling the feature, I think)
- If you disable the feature at some scope, it'd be nice to be able to turn it on again at another scope without the side-effect of enabling a bunch of categories.
- `All` is not quite the same as the other keys, but not independent of them like `Enabled` is. At least for me this feels a bit confusing.

Still overall it's probably an improvement.

**Comment by tom-anders** [comment]
Minor nitpick about the documentation (Should I open a new issue for this?):

`kind : string: The type of hint being provided, e.g. "ParameterHint".` 

This is not correct, the enum identifier (`InlayHintKind`) is in fact called "ParameterHint", but the value contained in the JSON response is actually "parameter" (see conversion in Protocol.cpp:1323). In general, I think the documentation should also include all possible types anyway.

**Comment by sam-mccall** [comment]
@tom-anders good catch, I misread the code. Fixed to mention both correct values.

It's still "e.g." because I'm sure we'll add more kinds. Maybe we can try to keep the doc in sync, but it'll be best-effort. Clients can do something nice with the standard values, but should be prepared to handle kinds not named there and do something sensible (drop them, render them with some default styling, ...)

**Comment by peterwford** [comment]
What's the intended method to disable this? Just upgraded to clangd 14 and now my code is unreadable...

From the comments above I guessed that passing `--inlay-hints=false` would work, but they're still there. Context is using clangd in VSCode, and I'm passing that to `clangd.arguments` in workspace settings.

**Comment by Curve** [comment]
> What's the intended method to disable this? Just upgraded to clangd 14 and now my code is unreadable...
> 
> From the comments above I guessed that passing `--inlay-hints=false` would work, but they're still there. Context is using clangd in VSCode, and I'm passing that to `clangd.arguments` in workspace settings.

As far as I'm aware the intended way is to disable the feature in the ide, so in vscode.
I can't check it right now but vscode may have a setting to disable inlay hints

**Comment by poyaoc97** [comment]
<img width="191" alt="Screen Shot 2022-04-05 at 9 35 46 PM" src="https://user-images.githubusercontent.com/32849523/161766188-dbbe8e1b-d338-4672-80c5-e9ac50fa4cd3.png">
There is a toggle.

**Comment by HighCommander4** [comment]
> this makes code so verbose and noisy it's easy to get lost in reading code, how to disable this?

See https://clangd.llvm.org/config.html#inlayhints, or in vscode toggle them off per previous comment
