### ISSUE TITLE
Check of header file order cannot be displayed on the client.

### ISSUE THREAD

**Issue by chengxinyuyyt** [clangd/clangd#314]
1  we find that check about header files cannot be displayed on the client.

for example: [llvm-order-check]  which clang-tidy can check it but clangd can not display it.

2  From the log of clangd， we also find that the line number of warning is not correct when it comes  to header files.

**Comment by kadircet** [comment]
I didn't get a chance to dig thoroughly but most likely place we are filtering those diags are in: https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/Diagnostics.cpp#L534

which is probably because of this diag is issued before we start parsing the main file(inside `ReplayPreamble`). Hence `StoreDiags` doesn't get a `BeginSource` call yet, therefore doesn't have `LangOpts`.

**Comment by kadircet** [comment]
sent out https://reviews.llvm.org/D83178 for review
