### ISSUE TITLE
recovery-ast not working in initializer of auto variable

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#330]
I'm trying out `--recovery-ast=true`. First of all, it's really neat!

One thing I noticed is that recovery does not seem to work for expressions in the initializer of an `auto` variable, even if it works for the same expression in other contexts.

For example:

```c++
int foo();

void bar() {
  foo(3);  // go-to-def on "foo" works fine
}
```

but:

```c++
int foo();

void bar() {
  auto x = foo(3);  // go-to-def on "foo" does not work
}
```

**Comment by hokein** [comment]
Yeah, we have a FIXME for that, the initializer is missing. In general, clang drops all ill-formed initializers. the recovery-expression is built in parsing stage, but is discarded in the Sema analysis. 

Another improvement is that we should preserve the type for recovery expression (if possible), so that `auto` can be deduced to `int` for the above case.
