### ISSUE TITLE
Broken build with CLANGD_ENABLE_REMOTE

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#351]
```
-- Version: 0.0.0
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Error: install(EXPORT "ClangTargets" ...) includes target "clangdRemoteIndex" which requires target "RemoteIndexProtos" that is not in the export set.
CMake Error: install(EXPORT "ClangTargets" ...) includes target "clangdRemoteMarshalling" which requires target "RemoteIndexProtos" that is not in the export set.
CMake Generate step failed.  Build files cannot be regenerated correctly.
ninja: error: rebuilding 'build.ninja': subcommand failed
```

Apart from the remote/grpc related vars, my cmake setup is:

```
#!/bin/bash
cmake -G Ninja \
  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_ASSERTIONS=On \
  -DCMAKE_LINKER=/usr/bin/ld.lld \
  -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld-9 \
  -DCMAKE_C_COMPILER=/usr/bin/clang-9 \
  -DCMAKE_CXX_COMPILER=/usr/bin/clang++-9 \
  -DCMAKE_CXX_FLAGS=-gmlt \
  -DLLVM_CCACHE_BUILD=On \
  -DLLVM_APPEND_VC_REV=Off \
  ~/src/llvm-project/llvm
```

**Comment by kirillbobyrev** [comment]
Ahh, I think this has to do with static linking since I use dynamic libraries. We discussed transitive dependencies in CMake this week and I probably did something that doesn't work in static mode. I'll look into this.

**Comment by kirillbobyrev** [comment]
I tried many approaches, but it essentially comes to replicating some pieces of what `add_clang_library` is doing. Hence, all the workarounds I did were heavily relying on some of `add_clang_library` internals _and_ generic LLVM's CMake variables. Since they can change, I think this is too hacky, so the best way is to fix it is to actually use `add_clang_library`. This is quite unfortunate because it forces `Index.proto` into a separate directory and makes the subdirectory structure if `index/remote` even more bizzare, but this still seems like the best solution.

[D78885](https://reviews.llvm.org/D78885) up for review.
