### ISSUE TITLE
Quickfix to include missing header

### ISSUE THREAD

**Issue by lucasdf** [clangd/clangd#355]
Hello!
When I have a function with a missing header, I can see the `diagnostics` warning realated to `implicit-function-declaration`, but there is no quickfix or code-action to include the missing header.

Since clangd seems to provide this, is there something that must be done in `coc-clangd` to make it available? Or should this be working already, and there may be something I need to adjust in my configuration?

Simple example:
```
int main(int argc, char *argv[]){
  printf("testing");
}
```

Listing the available code actions doesn't include anything related to `clangd`.

**Comment by kadircet** [comment]
yes looks like this is a clang generated warning without a fixit attached. moved into clangd repo, as it has nothing t o do with coc.

**Comment by sam-mccall** [comment]
Clang emits several diagnostics that should have an include-insertion fix, but don't:

 - note_include_header_or_declare
 - err_implied_std_initializer_list_not_found
 - err_need_header_before_typeid
 - err_need_header_before_ms_uuidof
 - err_omp_implied_type_not_found
 - err_module_unimported_use_header
 - err_module_unimported_use_global_module_fragment
 - err_implied_coroutine_type_not_found
 - err_implicit_coroutine_std_nothrow_type_not_found
 - err_implied_comparison_category_type_not_found

(maybe there are others)

The problem is these are emitted by Sema, and there's no facility accessible to Sema for determining where to insert the header. It makes sense to emit them somehow. Some options:

 - pull the tooling/Inclusion library into Sema, Lex, etc, or decide it's OK to depend on where it is
 - have very limited heuristics in Sema to position these includes, and have higher layers adjust them
 - emit special fixit hints from sema without locations attached, and have higher layers adjust them

I quite like the idea of #2. I think it'd be fine to do something like:
1. find the feasible region (after header guards, until first non-directive non-comment)
2. insert after the first include, or at the start of the region if there's none

**Comment by sam-mccall** [comment]
I never got around to doing this well in Sema, not completely sure it's a good idea (it'll affect clang's diagnostic output). Bolting it onto include-fixer is easy though: https://reviews.llvm.org/D114667
