### ISSUE TITLE
-Wunused-member-function is reported incorrectly

### ISSUE THREAD

**Issue by hyd-dev** [clangd/clangd#363]
`clangd` reports `-Wunused-member-function` for the following code:
```c++
#include <memory>

namespace {

struct deleter {
    void operator()(int* ptr) const noexcept { // -Wunused-member-function
        delete ptr;
    }
};

} // namespace

void f() {
    std::unique_ptr<int, deleter>(new int);
}
```
When compiling, `clang++` does not report `-Wunused-member-function`. `clang-tidy` and `clang-check` also don't rerpot the warning.

When using Google Test's `TEST()` macro, the same thing happens:
```c++
#include <gtest/gtest.h>

namespace {

TEST(Something, something) { // -Wunused-member-function
    // ...
}

} // namespace
```

**Comment by sam-mccall** [comment]
At its core this is the same as #137.

The root cause is that we don't parse the bodies of functions in headers - in this case the unique_ptr destructor. This is for performance reasons: it saves a lot of time parsing and also avoids instantiating a lot of templates. The tradeoff is accuracy, we miss certain types of diagnostics and occasionally generate spurious diagnostics like this one.

I can't think of a great workaround for this other than turning off -Wunused entirely :-\
The skip-function-bodies optimization is pretty important: it roughly halves clangd CPU usage and latency, with even more dramatic results in some cases (https://reviews.llvm.org/D41495)

**Comment by hyd-dev** [comment]
Truning off -Wunused-member-function is applicable for me, but I can't find a way to do that only for clangd. Clangd doesn't have a command line option like `--extra-arg` in clang-tidy. I still want to find out unused member function when compiling.

**Comment by hyd-dev** [comment]
Can `--extra-arg` be added to clangd? Or can clangd (or the underlying clang library) not report this warning by default when not parsing function bodies in headers? Missing this warning is better than reporting it spuriously.

**Comment by hyd-dev** [comment]
I think clangd/libclang-cpp can suppress -Wunused-member-function when the class is passed to an uninstanced template.

**Comment by sam-mccall** [comment]
> Can --extra-arg be added to clangd

We're looking at adding configuration that will let you do the equivalent (probably by adding args to a file like `~/.config/clangd`). It's still in the design phase though.

> Or can clangd (or the underlying clang library) not report this warning by default when not parsing function bodies in headers?

Well, it doesn't report them by default - only when `-Wunused` or similar is in compile_commands.json. I understand this is generated by your build system and you want the flag enabled there. You could use a tool to filter these arguments out of compile_commands. (Until clangd has options to help you)

> Missing this warning is better than reporting it spuriously.

This is really a question of opinion and tradeoffs , I think - losing the warning for non-templated code would be a shame.

> I think clangd/libclang-cpp can suppress -Wunused-member-function when the class is passed to an uninstanced template.

This actually seems pretty hard to do accurately, to me... patches welcome though.

**Comment by hokein** [comment]
So a chromium guy hit a similar [issue](https://groups.google.com/a/chromium.org/g/chromium-dev/c/ILIYgyZmBjE/m/Y61Q7UgKBAAJ).

Reproduce case (with `"clangd.fallbackFlags": ["-Wall",  "-Werror"]`):

```
// t.h
namespace {
void foo() {} // intend to not inline
}

void ff() {
    foo();
}

// t.cc
#include "t.h"
```

Open t.cc, it will prompt up `In included file: unused function 'foo'` diagnostic on the #include line.

We skip function bodies when building the preamble, so the `foo()` is not recognized as used. It seems that all **unused** diagnostics from the preamble region are unreliable, maybe we can drop them instead of annoying people?

**Comment by sam-mccall** [comment]
@hokein Rather than preamble region you're talking about in included files, right?

We already only promote *errors* from included headers into the main file[1], so `-Werror` is the trigger here. I think we should just not respect `-Werror` for this purpose (i.e. only show includes from other files that were *orginially* errors). WDYT?

[1] https://github.com/llvm/llvm-project/blob/4b53495c4ba2ba410f6383f9c57593e838ec0d57/clang-tools-extra/clangd/Diagnostics.cpp#L127

**Comment by hokein** [comment]
> Rather than preamble region you're talking about in included files, right?

Yeah, exactly.

> We already only promote errors from included headers into the main file[1], so -Werror is the trigger here. I think we should just not respect -Werror for this purpose (i.e. only show includes from other files that were orginially errors). WDYT?

this sounds good to me, let me prepare a patch.

**Comment by sam-mccall** [comment]
This can now be done with config:

```
CompileFlags:
  Add: -Wno-unused-member-function
```
