### ISSUE TITLE
Performacne: VSCode vs CLion using clangd

### ISSUE THREAD

**Issue by juxeii** [clangd/clangd#379]
Hi,
this is a question/feedback regarding uses of clangd in vscode and clion.
I have now experience with both IDEs and have used clangd also in both(with latest clion including clangd out of the box; vscode needs an extension).

How come that there are really big difference regarding code-navigation and indexing.
We have quite a big code base and when it comes to indexing and code browsing, clion takes the clear lead so far.

It indexes the files at startup once and then goto-comands are executed in an instant.
With vscode its almost the opposite: it also indexes files(with --background-index) but it has to compile each file I view to provide code insight and browsing.
This always take a long time and I'm wondering what are the technological differences when it comes to indexing between the two IDEs(not even mentioning cpptools where goto-commands take almost 1 minute and are not even cached).
I would really like to use vscode because of its nice user experience in general, but this is a showstopper for now :(

**Comment by sam-mccall** [comment]
Fundamentally this is because clangd is designed around using the clang parser, including for indexing. This means each CPP file gets parsed along with all its transitively included files, and we're redundantly parsing header files over and over.

Possible ways out of this are:
 - using clang's modules infrastructure to force reuse of parsed headers (maybe even if the project doesn't build with modules, at the cost of some accuracy. @gislan is looking into modules.
 - using a fast textual index or pseudoparser-based index, and then later reparsing more accurately after using this index to identify candidates. Fundamentally I believe this is what CLion does. We don't have active work in this area.

**Comment by juxeii** [comment]
Thx for this info.
I will regularly try new versions of clangd and see if the situation improves.
