### ISSUE TITLE
Showing completions from previously removed header, it's annoying.

### ISSUE THREAD

**Issue by zlianon** [clangd/clangd#394]
**Logs**
https://gist.github.com/zlianon/40e74b0194f88c582edca5f16a99b6a8

**System information**
Output of `clangd --version`: `clangd version 11.0.0-++20200513052626+1370757dd01-1~exp1~20200513153230.40`
Editor/LSP plugin: `Neovim` / `coc.nvim`
Operating system: `Ubuntu 20.04 (Docker)`

Before removing `<iostream>` header
```cpp
#include <iostream>

int main() {
    std::cou // completion works as expected  
}
```
After removing `<iostream>` header
```cpp
int main() {
    std::cou // still gets completion from <iostream> header
}
```

**Comment by sam-mccall** [comment]
This is by design: clangd shows results from headers that have been used in your project, whether they're included in the current file or not. If they're not, it can insert them for you when you accept the suggestion.
Results from headers that are included should generally be ranked higher than ones from other headers.
