### ISSUE TITLE
How can I get all the completion items once?

### ISSUE THREAD

**Issue by hy172574895** [clangd/clangd#396]
I am writting a client of LSP. 
So many Servers of LSP always return false when completing,
such as {"isIncomplete": **false**,"items": [.....]}.

Is there any property defined in LSP can set clangd to always returns full list of completion items?
For now, my client can works well with clangd, but it conflict with my filter algorithm.

**Comment by kadircet** [comment]
The expected behaviour from clients is to keep asking for completions in case of `isIncomplete: True`. As completion prefix gets larger with each keystroke, hopefully this will eventually become `false`.

Clangd leverages this flag to keep latency low, in a large codebase there can be thousands of possible completion items available, transmitting all of those via json would imply huge serialization/deserialization penalties.

If you still want to fetch everything you can play with `--limit-results` command line flag of clangd. It defaults to 100, you can set it to 0 for no limit, but as i mentioned above this might impact latency quite a lot. Also note that clangd won't return random 100 results, it will return top 100.

**Comment by hy172574895** [comment]
w

> The expected behaviour from clients is to keep asking for completions in case of `isIncomplete: True`. As completion prefix gets larger with each keystroke, hopefully this will eventually become `false`.
> 
> Clangd leverages this flag to keep latency low, in a large codebase there can be thousands of possible completion items available, transmitting all of those via json would imply huge serialization/deserialization penalties.
> 
> If you still want to fetch everything you can play with `--limit-results` command line flag of clangd. It defaults to 100, you can set it to 0 for no limit, but as i mentioned above this might impact latency quite a lot. Also note that clangd won't return random 100 results, it will return top 100.

Thank you so much.  You help a lot.
