### ISSUE TITLE
clang-tidy diagnostics are missing

### ISSUE THREAD

**Issue by mspik** [clangd/clangd#411]
**Description**
When using clangd in my environment I observe in different scenarios missing clang-tidy diagnostic results.
Minimal example for `performance-unnecessary-value-param`:
```cpp
#include <string>
#include <memory>

struct Test{
  Test(std::string a);
  std::unique_ptr<std::string> ptr;
};

Test::Test(std::string a) {
  ptr = std::make_unique<std::string>(a);
}
```
Executing clang-tidy gives following results:
```bash
➤ clang-tidy --checks="performance-unnecessary-value-param" main.cpp
16 warnings generated.
/tmp/main.cpp:9:24: warning: the parameter 'a' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
Test::Test(std::string a) {
                       ^
           const      &
Suppressed 15 warnings (15 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```
on the contrary, clangd reports nothing in this case.
Clangd executed with: `clangd --log=verbose --clang-tidy --clang-tidy-checks=performance-unnecessary-value-param`
```bash
>>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///tmp/main.cpp","version":0}}
```

**Investigation**
I did some digging in llvm code, and I think the problem could somehow be related to ast tree parsing. Inside `ExprMutationAnalyzer.cpp` there's `findFunctionArgMutation`
- clang-tidy -> it returns nullptr and `Matches` in `findFunctionArgMutation` is empty
- clangd -> it returns valid pointer and `Matches` in `findFunctionArgMutation` has a size of 1 (few lines below it returns via `return Exp;`)

This behavior has an overall effect on `UnnecessaryValueParamCheck::check` method:
- `Analyzer.isMutated(Param)` is equally true and it returns when used with clangd, or
- `Analyzer.isMutated(Param)` is equally false and it continues execution when used with clang-tidy

How can I continue from this point? Could it be related to some different initialization of the `ClangTidyContext`?

**System information**
Output of `clangd --version`:
```bash
~ ➤ clangd --version
clangd version 11.0.0 (https://github.com/llvm/llvm-project.git 5a230a19ad0fa52bd7aa2169b2f0abc6b2bc47df)
```
Editor/LSP plugin:
`emacs, lsp-mode`
Operating system:
`Linux pc 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux`

**Comment by sam-mccall** [comment]
In the normal clang-tidy case, the analysis follows the variable into the function where the arg is forwarded (std::make_unique) - see line 416. It sees the construction of `Test` inside, and that it could be a const string& instead of a string&.

Clangd doesn't parse the bodies of functions in headers for performance reasons, so the analysis can't see the body of std::make_unique and bails out on line 403 (!body()).

**Comment by sam-mccall** [comment]
So there's *almost* nothing we can do here: the skip-function-bodies optimization is too valuable to lose, and when we realize we want this function body it's far too late to go back.

However, for the specific case of `make_unique` I think it makes sense to parse the body: it's widely used and very small. It would make this check work, as well as diagnostics when bad args are passed to make_unique. Filed #412 for this.

Closing since I don't think this bug is otherwise actionable.
