### ISSUE TITLE
How can I change the format behavior of '{}' ?

### ISSUE THREAD

**Issue by BSDxxxx** [clangd/clangd#430]
When I use format function, I got:
```
int func(){
  print("a");
  return 0;
}
```
But I wish it could be:
```
int func()
{
  print("a");
  return 0;
}
```
Can you please show me the configration if it's possible to be changed? (I'm new to clang).

**Comment by BSDxxxx** [comment]
@kirillbobyrev Appreciate your help!
I still have few puzzles wish you could generously tell me:
1.  I'm using `coc-clangd`, it handles the bottom part for user, and can be configed by `coc-settings.json`, I don't know how to combine it with the options you mentioned above.
2. Where is `.clang-format`? Am I supposed to create it under my project folder?

**Comment by BSDxxxx** [comment]
@kirillbobyrev Thks, I have tried create `.clang-format` under project folder, it works well.
Still wonder could clangd option be configured in `coc-settings.json`.

**Comment by sam-mccall** [comment]
No, it can't be set under coc-settings.json.

Best practice is to check in the .clang-format file so that it will be used by the `clang-format` tool, `clangd` etc for all developers who work on the project.

To set a global default when no `.clang-format` file is found, you can use the `-fallback-style` flag to clangd. This can only be one of the builtin styles (LLVM, Google, etc). We'll soon add support for a clangd config file which will allow specifying a full style as a fallback style.
