### ISSUE TITLE
Include completion fails at the end of file

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#433]
+ clangd version:  clangd version 11.0.0 (https://github.com/llvm/llvm-project.git 3badd17b6989621b5aa2732800f697dabbda034d)
+ OS: Windows 10

I think this issue still exists. @HighCommander4

![image](https://user-images.githubusercontent.com/10697249/84476669-0e7d9c00-acc1-11ea-89ea-3a7ea9ada167.png)

_Originally posted by @lh123 in https://github.com/clangd/clangd/issues/38#issuecomment-643115928_

**Comment by HighCommander4** [comment]
You're right, I see the same issue (global completion instead of include completions).

I think what happened when I was testing #38, is that I typed in `#include "llvm/Sup` manually. When I type the `"` character, my editor auto-inserts a matching closing quote, so the actual test case I was testing was:

```
#include "llvm/Sup^"
```

(not the presence of the closing quote), which works fine.

**Comment by kadircet** [comment]
I can't seem to reproduce this, neither on LLVM or a dummy project.

Could you please share clangd logs ?

**Comment by njames93** [comment]
It reproduces if the file has no code in and the include brackets are unbalanced and followed by eof

**Comment by kadircet** [comment]
Interesting I thought I had fixed this one... Well good thing is, this means at least I know the fix :D

Sent out https://reviews.llvm.org/D95419

**Comment by njames93** [comment]
Works like a charm now on my end, thanks.
