### ISSUE TITLE
BackgroundIndex and StaticIndex - Clangd in Visual Studio Code

### ISSUE THREAD

**Issue by aallrd** [clangd/clangd#479]
Hello,

This is not a bug report, I am looking for clarification/help on the usage of the clangd index in Visual Studio Code.

I am trying to use clangd in Visual Studio Code to provide insight into my C++ project.
The project has over 30k+ files and I have generated its full compilation database using [intercept-build](https://github.com/rizsotto/scan-build).

When loading the project in Visual Studio Code, the `clangd` server is started with the `--compile-commands-dir=` flag set to the location of the project's compilation database and with the `--background-index` flag to index the project code in the background.
I can see from Visual Studio Code that the BackgroundIndex process is running and that all the 30k+ files are queued for analysis.
This is however a very long and CPU intensive task as you can imagine from the number of files, and also a task from which I would like to re-use/distribute the output as much as possible.

I tried therefore to pre-compute this index "offline" as a nightly job in order to be able to directly download a working and ready to use copy of the clangd index for my project.
I have been successfully using the `clangd-indexer` on my project's compilation database to create a StaticIndex file:
```
clangd-indexer -extra-arg="-Wno-everything" --executor=all-TUs compile_commands.json > clangd.dex
```
However, feeding this StaticIndex file to `clangd` with the flag `-index-file=clangd.dex` does not prevent the background indexation of the 30k+ files to be triggered when I open Visual Studio Code.

My Visual Studio Code `clangd.arguments` in the end are:
```
  "clangd.arguments": [
    "-index-file=/root/clangd.dex",
    "--clang-tidy",
    "--clang-tidy-checks=modernize-*",
    "--header-insertion=iwyu",
    "--suggest-missing-includes",
    "--all-scopes-completion",
    "--log=info",
    "--compile-commands-dir=/root"
  ]
```

Am I misunderstanding something in how the StaticIndex and the BackgroundIndex are working? Are they complementary?
Is there a way to achieve what I am trying to do?

My next step would be to try to archive and re-use the `.clangd/index` folder generated by the background indexer.
Does it make sense to share/re-use the data in this folder? How could `clangd` be triggered to produce this `.clangd/index` folder offline without Visual Studio Code?

Thank you for your help.

**System information**
Output of `clangd --version`: clangd version 11.0.0
Editor/LSP plugin: Visual Studio Code / llvm-vs-code-extensions.vscode-clangd 0.16.0
Operating system: RHEL 7.6

**Comment by kirillbobyrev** [comment]
Hi! Your setup looks very good and you're doing everything correctly, I think the missing step here would be passing `--background-index=false` to `clangd.arguments` because it is enabled by default even if the static index is provided.

I think we should make it clear in the help message that providing `-index-file` does not disable background index.

Nit: some flags you pass are "on" by default (`--clang-tidy`, `--header-insertion=iwyu`, `--suggest-missing-includes`, `--all-scopes-completion`, `--log=info`); nothing wrong with it bust just in case you wanted to keep your config minimalistic you could cut those :)

As for re-using `.clangd/index`, this is an interesting question and unfortunately, I don't know how to answer it correctly. Maybe @hokein or @kadircet could provide more info?

Also, AFAIK `.clangd` is now reserved for Clangd config file (should be included in 11.0 IIRC) but honestly I'm not sure what the new cache directory name is (`.clangd-cache`?). I should look into that and we should also document this somehow. This should probably be in release notes but I can't find those. (If it isn't already included we should probably make this explicit)

**Comment by kadircet** [comment]
> This is however a very long and CPU intensive task as you can imagine from the number of files, and also a task from which I would like to re-use/distribute the output as much as possible.

Unfortunately any artifacts produced by either background or static index are not shareable among other machines unless you've got exact filesystem layout, as the artifacts contain absolute paths. we are working on a remote-index support for big projects so that indexing can be done separately and results can be used among multiple users through a server. but it is not ready yet.

Currently your best bet is background-indexing, it should take roughly the same time as a static index build, but the nice thing about background-index is, it is incremental. So once you index your whole project, afterwards it will only index files that are changed. Whereas static-index is a big monolithic one, you would need to index the whole project from scratch every time.

> However, feeding this StaticIndex file to clangd with the flag -index-file=clangd.dex does not prevent the background indexation of the 30k+ files to be triggered when I open Visual Studio Code.

Unfortunately the artifacts produced by static-index and background-index are not compatible in any form. So you cannot reuse them, even if they were built on the same computer (let alone using index build on a different machine). As Kirill mentioned, if you want to only make use of static-index you should disable background-indexing, otherwise all you'll get is some baseline up until background-indexing catches up.

**Comment by aallrd** [comment]
Hello,

Thank you all for your explanations and feedback.

From what you explained I will stick with the background-indexing solution instead of the static one, in order to benefit from the incremental feature.
My current build/development setup enforces the same project location to be used across servers so maybe sharing the artifacts could be possible in my case (same filesystem layout, same absolute paths).

So it leaves me with two questions then:
- The background-indexing cache is stored under `.clangd/index` right? As mentioned by @kirillbobyrev this folder seems to be reserved for `clangd` configuration files, do you think it's possible to archive it and re-use it on another server?
- How can I manually trigger the clangd background-indexing process in order to run it as a nightly job? Currently it only starts when opening a source file in Visual Studio Code.

Thank you for your help.

**Comment by kadircet** [comment]
> My current build/development setup enforces the same project location to be used across servers so maybe sharing the artifacts could be possible in my case (same filesystem layout, same absolute paths).

if the absolute paths are the same then you should hopefully be able to use artifacts produced on a different machine (modulo STL/built-in headers, in the worst case you might end up indexing them once but they are usually lightweight to index)

> The background-indexing cache is stored under .clangd/index right? As mentioned by @kirillbobyrev this folder seems to be reserved for clangd configuration files, do you think it's possible to archive it and re-use it on another server?

this is not something you should worry until you start using clangd-11. after that the artifacts directory will change from `.clangd/index` to `.cache/clangd/index`. in either case these should be relative to compilation database (i.e. either to compilation_database.json or the path you specify with `--compile-commands-dir`).

> How can I manually trigger the clangd background-indexing process in order to run it as a nightly job? Currently it only starts when opening a source file in Visual Studio Code.

unfortunately there's no easy way of doing this yet. you can in theory grab communication between vscode and clangd using `-input-mirror-file=input-mirror.txt` flag. then you can pass that to standalone clangd, e.g.

```
cat input-mirror.txt - | clangd -log=verbose #any extra args you want to pass
```

and then watch clangd's output for `BackgroundIndex: building version .* when background indexer is idle` to know when the indexing is complete.

**Comment by kirillbobyrev** [comment]
> > The background-indexing cache is stored under .clangd/index right? As mentioned by @kirillbobyrev this folder seems to be reserved for clangd configuration files, do you think it's possible to archive it and re-use it on another server?
> 
> this is not something you should worry until you start using clangd-11. after that the artifacts directory will change from `.clangd/index` to `.cache/clangd/index`. in either case these should be relative to compilation database (i.e. either to compilation_database.json or the path you specify with `--compile-commands-dir`).
> 

I originally brought this up because it seems that @aallrd already _is_ using clangd 11 :)

> System information
> Output of clangd --version: clangd version 11.0.0
> Editor/LSP plugin: Visual Studio Code / llvm-vs-code-extensions.vscode-clangd 0.16.0
> Operating system: RHEL 7.6

As @kadircet mentioned, one of the problems for index portability is path difference (e.g. `/home/kirillbobyrev/...` vs `/home/kadircet/...`) and symbols outside of the project itself (system installed libraries, standard library headers, etc) and I'm actually working on solving this problem for our use cases right now. If I understand your use case correctly you would probably be interested in the upcoming remote index feature which will make it possible to have one machine over the network that will periodically build the index via `clangd-indexer` and then serve it to every client that doesn't want to spend compute power on indexing but would like to have a relatively up-to-date index. It is highly experimental right now but I expect it to be usable in the near future (1-2 months). We don't have much documentation on it yet (aside from building instructions in [`llvm/llvm-project/clang-tools-extra/clangd/index/remote/`](https://github.com/llvm/llvm-project/tree/master/clang-tools-extra/clangd/index/remote)) but I've already set up GitHub Actions [project](https://github.com/kirillbobyrev/indexing-tools) for indexing LLVM which is the first project we'd like to test this feature on. We'll do more announcements as the remote index feature matures, so this might be something that you'll find useful

**Comment by aallrd** [comment]
Hello,
I am getting back to this thread to share how I finally ended up generating the offline clangd index based on @kadircet's suggestions:

__start-clangd-indexer.sh__:
```
#!/usr/bin/env bash

set -ex

function terminate {
  kill -9 "${CLANGD_PID:-}"
  rm -f /tmp/clangd-input
  rm -f clangd.log
}

trap terminate EXIT

__stdin="/tmp/clangd-input"
rm -f ${__stdin} || true
mkfifo ${__stdin}

tail -f ${__stdin} | /usr/local/bin/clangd \
  --log=verbose \
  --compile-commands-dir=/src_root \
  --background-index \
  --all-scopes-completion \
  --clang-tidy \
  --clang-tidy-checks=modernize-*,misc-* \
  --header-insertion=iwyu \
  --suggest-missing-includes \
  > clangd.log 2>&1 &

CLANGD_PID=$!

echo "Waiting for clangd (${CLANGD_PID}) server to start..."
sleep 5
echo "Sending LSP input to clangd server..."
echo "" > ${__stdin} # initializing stdin
cat input.clangd.txt > ${__stdin}

echo "Waiting for clangd (${CLANGD_PID}) background indexer to complete..."
( tail -f -n0 clangd.log & ) | grep -qP "BackgroundIndex: building version .* when background indexer is idle"

echo "Done"

exit 0
```


__input.clangd.txt__ (not exactly it because it contains source code):
```
Content-Length: 3072

{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":32468,"clientInfo":{"name":"vscode","version":"1.47.3"},"rootPath":"/src_root","rootUri":"file:///src_root","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"editsNearCursor":true},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"semanticHighlightingCapabilities":{"semanticHighlighting":true}},"window":{"workDoneProgress":true}},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"trace":"off","workspaceFolders":[{"uri":"file:///src_root","name":"project"}]}}Content-Length: 52

{"jsonrpc":"2.0","method":"initialized","params":{}}Content-Length: 1458

{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp","languageId":"cpp","version":1,"text":"..."}}}Content-Length: 155

{"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp"}}}Content-Length: 254

{"jsonrpc":"2.0","id":2,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":[]}}}Content-Length: 153

{"jsonrpc":"2.0","id":3,"method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp"}}}Content-Length: 38

{"jsonrpc":"2.0","id":0,"result":null}Content-Length: 256

{"jsonrpc":"2.0","id":4,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp"},"range":{"start":{"line":22,"character":2},"end":{"line":22,"character":2}},"context":{"diagnostics":[]}}}Content-Length: 184

{"jsonrpc":"2.0","id":5,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp"},"position":{"line":25,"character":45}}}Content-Length: 184

{"jsonrpc":"2.0","id":6,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///src_root/lib/mysource.cpp"},"position":{"line":25,"character":44}}}
```
I got the __input.clangd.txt__ file after adding the `-input-mirror-file=input-mirror.txt` to clangd in Visual Studio Code as suggested.
Thank you for your help on this request.

I am indeed using Clangd 11, and the index folder is still `.clangd/index` on my side.

@kirillbobyrev I would definitely be interested in this remote index feature :) I'll keep watching the project for the future developments.
