### ISSUE TITLE
Find all references doesn't find ALL references

### ISSUE THREAD

**Issue by gkoulin** [clangd/clangd#516]
Following the guidance of https://clangd.llvm.org/features.html#find-references

Find all references only finds references within currently opened files. It does not find all of the references project wide. 

**System information**
clangd version 10.0.0 
vscode-clangd 0.1.6
macOS 10.14.6

**Comment by kadircet** [comment]
do you have a `compile_commands.json` in your project root telling clangd what "all" files in your project are?

if not, you unfortunately need to have that, otherwise clangd currently cannot figure out all the files you have open and will only index the files you are working on.

if you have a compile_commands.json, please share clangd logs so that we can take a more detailed look.

**Comment by gkoulin** [comment]
Hi

Yeah `compile_commands.json` fixes it!

Thanks
