### ISSUE TITLE
compile_flags.txt not doing anything?

### ISSUE THREAD

**Issue by HendrikMennen** [clangd/clangd#518]
I probably did something wrong but after trying for very long I hope someone can help me here.
I simply want librarys inside the arduino folder to be included so I can use them like this.
I know I could use a path instead but I want it to be similar to the NIOS2 eclipse version where the sample is like this.
Arduino.h is located inside the arduino folder and when using `clang++ -I arduino NIOSDuino.cpp` it works.
![Unbenannt](https://user-images.githubusercontent.com/25281882/92378929-dc84a600-f106-11ea-9d97-a67bba48c205.PNG)

my compile_flags.txt
```
-Iarduino
```

I also tried generating a compile_commands.json from my MakeFile using https://github.com/nickdiego/compiledb
but it doesn't work at all or gets ignored.

Using the .clangd file as described on the website didn't work for me aswell.

**Comment by kadircet** [comment]
Have you also restarted clangd (or your editor) after putting compile_flags.txt (or compile_commands.json) into project root? Clangd won't pick up changes to these files after it has started.

For additional diagnosis, please share the clangd logs so that we can understand what's going on. See http://clangd.llvm.org/troubleshooting.html#gathering-logs for details.

> Using the .clangd file as described on the website didn't work for me aswell.

This is only available starting with clangd-11, again if you are using a recent enough clangd we still need the logs to diagnose further.

**Comment by HendrikMennen** [comment]
Okay it just started working for some reason I don't know what I did wrong before. Thank you for your help

**Comment by HendrikMennen** [comment]
> Clangd won't pick up changes to these files after it has started.

why is that? If you create or import a new project nothing will work until you restart? Is there no way to dynamically reload changes in Compile_Commands.json?

**Comment by kadircet** [comment]
Just to be clear, by restart I imply just restarting your editor(or clangd sepcifically, if your plugin/editor permits).

As for hot reload of changes to compile commands, it is something in our roadmap, but we haven't got to it yet.

**Comment by HendrikMennen** [comment]
Yes I know I added an option to reload the LS in my IDE which works fine but reloading compile_commands would be still nice.
