### ISSUE TITLE
Unable to distingish overloads in breadcrumbs or outline

### ISSUE THREAD

**Issue by reporter123** [clangd/clangd#520]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

![image](https://user-images.githubusercontent.com/684470/92417067-e67ec700-f14f-11ea-8c63-6fb56ab871b8.png)

![image](https://user-images.githubusercontent.com/684470/92417136-378ebb00-f150-11ea-9710-dd6d676de59c.png)

These pictures illustrates how vscode-clangd snd ccls handle member function symbols.
vscode-clangd only shows the name of the function which is not enough in the case of a overloaded function. ccls provides parameter and return value information which the only way to tell these functions apart.

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

class x {
    void y(int e){}
    void y(){}
}

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): 10.0.1-++20200708122807+ef32c611aa2-1~exp1~20200707223407.61
clangd extension version: 0.1.7
Operating system: Linux-x64

**Comment by HighCommander4** [comment]
Transferred to the clangd repo as the issue here is on the server side. The `documentSymbols` response that is used for outline and breadcrumbs does not include the method signatures.

**Comment by hokein** [comment]
looks like we don't populate the `detail` field of `DocumentSymbol`, we should populate the function signature in this case.

**Comment by iammorjj** [comment]
Hi!
I want to try to solve this issue.
Built the project and ran check-clangd tests. Now I'm exploring the codebase.
Is it better to start by writing tests?

**Comment by kadircet** [comment]
Hi @iammorjj, first of all thanks for taking your time!

Yes, usually starting by writing small unittests to ensure the output looks like what we want is a good practice.
After writing tests, you can even send them out for review to ensure we are all on the same page, before diving into implementation.
Another good step before diving into the implementation is usually describing the solution you have in mind, so that
relevant people can provide guidance if there are some concerns you've skipped over about the other systems. That
way you can save some cycles in the code review and make sure you don't spend time on implementing a semi-working solution.

**Comment by iammorjj** [comment]
Hello again,
I put some tests, correct me if something is wrong. Comments contain expected data. (https://github.com/iammorjj/llvm-project/commit/84c039289cbb44fbd82817ebde1e316f5c3896c3)
I guess 'detail' field is always empty because we miss it [in this part of code](https://github.com/iammorjj/llvm-project/blob/f0659248b907cf22514a549aac3fa11f95608097/clang-tools-extra/clangd/FindSymbols.cpp#L152). Continuing research😃

**Comment by kadircet** [comment]
Yes! This looks sensible to me, the one thing you might wanna tweak is in `DocumentSymbol`, we probably don't want ot populate detail with symbol name again. You can use `getSignautre` helper we have in clangd to just fetch the signature and display that instead.

Also I would add some templated functions to the tests, to ensure behaviour on those are still sensible.

As an additional enhancement we might want to add `-> RetType` to our signature representations, but that can be done separately.

Thanks for working on this!
