### ISSUE TITLE
Cannot enable clangd on standard c++ header files in VSCode, such as iostream

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#57]
Cannot enable clangd on standard c++ header files in VSCode, such as iostream.

**Comment by sam-mccall** [comment]
@ilya-biryukov you understand VSCode, could you take a look when you get a chance?

I believe we should get reasonable compile commands now for such files, so I suspect they're the vscode extension just isn't deciding clangd should be active for these files.

**Comment by hokein** [comment]
For these extension-less files, vscode doesn't think them as C++ files
- if you open only an `iostream` file in vscode, the vscode-clangd extension will not activated. The extension is activated 1) automatically on c-familary language files or 2) manually by triggering the `clangd-vscode.activate` command;

- even the vscode extension is activated, the extension thinks `iostream` is not a `cpp` file, because we are using the file extensions (`.h`, `.cpp`, etc) to decide whether clangd should be active for these files.

We could extend our vscode extension to detect these C++ files based on the shebang on the first line like `-*- C++ -*-` . A better alternative might be that vscode should support detecting these files (`atom` already does it).

**Comment by lh123** [comment]
Microsoft C ++ plugin can automatically identify these types of files.
>The Microsoft C++ plugin seems to use "files.associations" to implement this feature.
```json
{
    "files.associations": {
        "array": "cpp",
        "*.tcc": "cpp",
        "iostream": "cpp"
    }
}
```

**Comment by hokein** [comment]
I'd prefer a more general way rather than maintaining a long whitelist of files in our extension. I have filed a feature request to vscode (https://github.com/microsoft/vscode/issues/75506).

Currently, you could workaround it by adding `files.associations` to your personal `settings.json` file, the latest `vscode-clangd` v0.0.14 should work with it.

**Comment by hokein** [comment]
Actually, vscode provides [`contributes.language.firstLine`](https://code.visualstudio.com/api/references/contribution-points#language-example) feature, we could use it to detect such files. Supported in r363554, and will be available in next extension release (v0.0.15).

**Comment by sam-mccall** [comment]
The magic comment isn't a very general solution either, we probably want
several heuristics. Don't c++ standard headers often get installed in a
directory with `include/c++` or /use/include etc in the path?

**Comment by hokein** [comment]
> The magic comment isn't a very general solution either, we probably want
several heuristics. 

I think the magic comment should cover most cases well (at least C++ standard headers, and LLVM's `.def` files).   

> Don't c++ standard headers often get installed in a directory with `include/c++` or /use/include etc in the path?

The location of C++ standard headers maybe different on different platforms (mac, linux).

I think we can reiterate this if we figure out the magic comment is not enough.

**Comment by cpsauer** [comment]
Adding a voice to this one: I just ran into this with Eigen, a popular linear algebra library. 
No extensions on the headers, no magic comment, no C++ in the path :/

Not sure I have a great fix, but a couple heuristics that might work for identifying no-extension files:
Paths listed in compile_commands
Lines starting with #include

**Comment by HighCommander4** [comment]
@cpsauer I would suggest filing a new issue, as this one is about standard library headers and that does seem to have been fixed.
