### ISSUE TITLE
Language server crash on mouse-over symbol

### ISSUE THREAD

**Issue by decimad** [clangd/clangd#633]
Hi,

I'm experiencing some undesired crashes and slow performance when hovering over certain symbols for extended information.
I committed the work-in-progress code to reproduce the crashes in https://github.com/decimad/meta.
The toplevel directory must be in the include path. The file https://github.com/decimad/meta/blob/master/meta/detail/tree_verification.hpp exhibits the problematic behaviour:
* when hovering over "descend_left_t" in line 23 the language server crashes reproducibly
* when hovering over "are_same_v" in line 22 the language server takes a considerable amount of time to respond for such a rather "simple" problem

**Comment by decimad** [comment]
So this is a stack overflow due to an unterminated recursion, VisitDependantNameType seems to be caught in a circular path (alway being called on the same DNT).
![grafik](https://user-images.githubusercontent.com/2931955/103183393-6cb34a80-48b2-11eb-9732-54055f223bad.png)

**Comment by decimad** [comment]
As I cannot interpret any of the values/functions that the debugger presents to me, I replaced the partial specialization by requires-clause of 'meta::detail::descend_left' with a traditional partial specialization by defaulted template argument, which circumvents the crash/endless recursion.

**Comment by HighCommander4** [comment]
Thanks for the report.

> I committed the work-in-progress code to reproduce the crashes in https://github.com/decimad/meta.

Could you provide info on how to configure the project for clangd as well? I tried `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .` but it did not generate a `compile_commands.json`.

**Comment by decimad** [comment]
Hey,
oh right, this is normally a header-only-library. I added a standalone build target to the cmake scripts with https://github.com/decimad/meta/commit/941fe7886af7961704427981037f94e4ef2da222 that should help you generating a compile_commands.json.
Unfortunately the sources matured too in the meantime, thereby the location of the reproduction. One of the the updated crashing locations would be the token "descend_deep_left_t" in meta/detail/tree_verification.hpp:23.

**Comment by HighCommander4** [comment]
Thanks for the update, I was able to generate a `compile_commands.json` now.

There is something a bit weird about the generated `compile_commands.json`: it contains both `-std=gnu++20`, and later in the same command, `-std=gnu++1z`. The later occurrence of the flag takes precedence, causing clangd to process the code in C++17 mode, and therefore not recognize the concepts.

Anyways, this was easy enough for me to fix by manually editing the `compile_commands.json` to remove the `-std=gnu++1z`. With that, clangd crashes for me as soon as I open tree_verification.hpp. I will investigate further.

**Comment by decimad** [comment]
Hrmm, I wonder if that has to do with the `set_property(TARGET verification PROPERTY CXX_STANDARD 20)`, sorry for that, I will poke around to find the reason.
Your experience is different to mine, as I can at least work with the file, if I resist the tempation to place the cursor above one of the problematic constructs. Perhaps you're not working on head of master, or using a different client?

**Comment by HighCommander4** [comment]
The crash I get is from the same recursion as in your screenshot, but it happens when computing semantic highlightings (which is triggered automatically when you open a file). I'm using vscode; perhaps you're using a client that does not support semantic highlighting.

**Comment by decimad** [comment]
Oh, I disabled that feature, since it somehow led to inconsistent highlighting (rather large subparts not highlighted at all). I will readdress this once the more urgent problems are sorted out.

**Comment by HighCommander4** [comment]
Here is a reduced testcase that triggers the crash:

```c++
template <typename T>
concept Leaf = false;

template <typename Tree>
struct descend_left {
  using type = typename descend_left<typename Tree::left>::type;  // <--
};

template <Leaf Tree>
struct descend_left<Tree> {
  using type = typename Tree::value;
};
```

The recursion occurs when computing the semantic highlighting for (or hover information for) the `type` token at the end of the indicated line.

**Comment by HighCommander4** [comment]
The recursion occurs while performing the `allTargetDecls()` operation on the AST node for the mentioned `type` token.

The purpose of this operation is to return the declaration(s) referred to by this node. The usual clang APIs cannot resolve this reference because it's dependent, so we use heuristics we added in clangd to say "let's look for a member named `type` in the primary template definition of `descend_left`". (This is why using conventional partial specializations rather than concepts avoids the recursion -- with conventional partial specializations, the primary template is empty and does not contain a member named `type`.) We thus find the `using type` using-declaration on the same line.

This, in and of itself, is fine. The problem is that when finding a typedef, `allTargetDecls()` looks at the typedef's underlying type and includes that in the set of target declarations. In this case, the typedef's underlying type is the thing we started with, so we get into the infinite recursion.

**Comment by HighCommander4** [comment]
While thinking about how to fix this, I checked the behaviour of `allTargetDecls()` on a simpler testcase:

```c++
struct C {
  using type = int;
};
struct B {
  using type = C::type;
};
struct A {
  using type = B::type;
};
A::type waldo;
```

Here, if we call `allTargetDecls()` on `type` on the last line, we get three results: `A::type`, `B::type`, and `C::type` (the latter two with the `Underlying` flag set).

Is this desirable in the first place? Or should we only be going one "hop" (that is, if we already have a result with the `Underlying` flag set and that happens to be a typedef-decl, don't look at _its_ underlying type in turn)? That would give us just two results, `A::type` and `B::type`.

I ask this because it affects how we solve this recusion issue:
 * If we decide the multi-hop behaviour is not desirable in general, then the recursion problem just goes away.
 * If we decide the multi-hop behaviour _is_ desirable, we need to add some sort of recursion guard (either a depth limit, or a "declarations we've already seen" check) for the dependent case.

**Comment by HighCommander4** [comment]
> Here, if we call `allTargetDecls()` on `type` on the last line, we get three results: `A::type`, `B::type`, and `C::type` (the latter two with the `Underlying` flag set).
> 
> Is this desirable in the first place? Or should we only be going one "hop" (that is, if we already have a result with the `Underlying` flag set and that happens to be a typedef-decl, don't look at _its_ underlying type in turn)? That would give us just two results, `A::type` and `B::type`.

I've thought about this, and I think we _do_ want the multi-hop behaviour for typedefs.

While many users of `allTargetDecls()` (including go-to-def, hover, and semantic highlighting) do not care about results with the `Underlying` flag set, there are some that do, and for at least one of them, type hierarchy, the multi-hop behaviour seems useful. If we consider a variant of the code example from the previous comment where the ultimate underlying type is a class type, it's useful to be able to invoke type hierarchy on that class type from any level of alias.

(There are, however, opportunities to make the callers that don't care about `Underlying` results more efficient. Rather than gathering all results and then discarding the ones with this flag set, we could avoid computing them in the first place.)

>    * If we decide the multi-hop behaviour _is_ desirable, we need to add some sort of recursion guard (either a depth limit, or a "declarations we've already seen" check) for the dependent case.

A recursion guard turns out to be straightforward to add. I will submit a patch that adds one to solve this bug.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D94382)
