### ISSUE TITLE
Filter reserved identifiers from namespace std in completions.

### ISSUE THREAD

**Issue by njames93** [clangd/clangd#635]
Would it be possible to filter out from completions identifiers from std:: that begin with _. 
These identifiers are reserved by the standard and typically should not be referred to outside of the implementation.

Currently when I type in `std::ve^` I get:
-`vector<typename _Tp, typename _Alloc>`
-`vector(...)`
-`_Vector_base(...)`

Arguably `_Vector_base(...)` Shouldn't be suggested as its not defined to be in the std, it just happens to be how vector is implemented in libstdc++.
Obviously vector is just one example, this behaviour appears all over the place in the standard library.

**Comment by kirillbobyrev** [comment]
Hm, I like the idea but I'm not entirely sure how to detect unwanted entities. One approach could be ignoring names like `_*` and `*_impl` in the static index (otherwise it might hurt people who actually work on these things and have those open in a tab) or do some post-filtering. This seems relatively innocent (although maybe unexpected sometimes) to avoid hiding it behind the flag.

Another, probably more transparent option, might be basically enumerating known "hidden" standard library implementation types. This way it's easier to discover this behavior for someone unaware of the strategy described above and also probably safer (I don't know how often developers utilize the same naming & "hiding" strategy outside of Standard Library, Boost and Abseil). Speaking of Boost & Abseil, maybe it makes sense to consider looking through them, too, in order to find similar patterns.

**Comment by njames93** [comment]
That's why I suggested just those names in the std namespace. The std makes no mention afaik of using a symbol from its namespace that begins with an underscore apart from placeholders which are r`_\d+`. 

It should probably be hidden behind a flag for those people working on standard library implementations.

Growing this to support boost, abseil etc should be under their own flags probably. 
I'm against the idea of making this fully generic using regex over the qualified symbol as that requires getting the qualified name which is somewhat expensive.

**Comment by sam-mccall** [comment]
I've been looking at stdlib indexing and ran into this issue. https://reviews.llvm.org/D115301 is an attempt.

**Comment by HighCommander4** [comment]
I think this can be closed; the patch linked in the previous comment has merged a while ago.
