### ISSUE TITLE
Make header insertion style configurable (quotes or brackets)

### ISSUE THREAD

**Issue by bloertscher** [clangd/clangd#670]
Currently header insertions are always in quotes, e.g. `"foo/bar.h"`. It would be great to have a configuration or command-line option to allow header insertions to use brackets, e.g. `<foo/bar.h>`.

**Comment by njames93** [comment]
I'm not 100% sure on the specifics but it uses a heuristic to determine whether or not to use `<name>` vs `"name"`.
Off the top of my head it goes something like this:
clangd will use your include directories and figure out 'the best' relative include path to use. 
If that relative include is relative to a system include path it will give use angle brackets, otherwise quotes.

**Comment by bloertscher** [comment]
Gotcha, that makes sense. However, if a project has an existing style (e.g. always use angle brackets), it would still be nice to be configurable. However, it's an easy enough `sed` fix that maybe it's not worth adding in the complexity.

**Comment by sam-mccall** [comment]
For the record, clangd's heuristic is "use `<>` for system directories, use `""` for others".

System directories are the default detected search paths (`/usr/include` etc), and those specified by `-isystem`.

Generally you can change the behavior by changing `-I` to `-isystem` in compile_commands.json. This probably means changing your build system, but naively it seems like such a change makes sense if you're treating these as system libraries. #1247 is the current feature request for overriding this.
