### ISSUE TITLE
Cannot find header files when editing ASIO in Visual Studio Code

### ISSUE THREAD

**Issue by MCMocoder** [clangd/clangd#689]
Clangd cannot find header files in the folder asio/include when editing asio.

Output of `clangd --version`:clangd version 11.0.0
Editor/LSP plugin:Visual Studio Code
Operating system:macOS 11.1 Big Sur

**Comment by kadircet** [comment]
Do you have a compilation database telling clangd to look at `asio/include` as an include directory? see https://clangd.llvm.org/installation.html#project-setup for details. If you believe you've set your project correctly, please include clangd logs so that we can help more, see https://clangd.llvm.org/troubleshooting.html#gathering-logs for gathering logs.
