### ISSUE TITLE
Semantic highlightings not recomputed when included file changes

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#699]
**Steps to reproduce**

1. In a source file, add a call to a non-existent function. A diagnostic appears, as expected.
2. In a header file included by the source file, add a declaration of that function.
3. Switch back to the source file.

**Expected results**

The diagnostic disappears **and** the function name is given a semantic token.

**Actual results**

The diagnostic disappears, but the function name remains without a semantic token until something else (e.g. an edit to the source file) triggers a re-highlight.

**Comment by sam-mccall** [comment]
> this might have the nasty side effect of clients throwing away all the existing highlighting

I don't think it will. The nature of the `semanticTokens` request is that clients need to be able to keep using old highlightings while new ones are pending for the experience to work at all well, with a little state machine in there. Therefore it's extremely unlikely a client would clear highlighting immediately when receiving `refresh` rather than just marking the buffer as dirty and/or firing off the request.

Please do send a patch if this seems easy!

> we'll send a full response after every preamble rebuild, rather than a delta

I'm not sure why. If:

 - the client requests a delta
 - their previousResultId matches the last response we sent
 - (few/no tokens have changed so the delta-encoding actually does something useful)

we'll send a small delta rather than the full token list. The diff is done pretty far up the stack in ClangdLSPServer, internally every request computes the full token list anyhow.

**Comment by kadircet** [comment]
> Please do send a patch if this seems easy!

sent out https://reviews.llvm.org/D97548
