### ISSUE TITLE
clangd.11.0.0 crashed due to the miss of glib2.18

### ISSUE THREAD

**Issue by jievince** [clangd/clangd#722]
```
[Error - 9:47:58 AM] Connection to server is erroring. Shutting down server.
[Error - 9:47:58 AM] Connection to server got closed. Server will not be restarted.
/home/vesoft/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/vesoft/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd)
[Error - 9:47:58 AM] Connection to server is erroring. Shutting down server.
```
I have `glibc.x86_64   2.17-323.el7_9` installed on my centos 7.9, so which version of clangd can work well with glibc 2.17?

**Comment by njames93** [comment]
2.18 or later is required. Of the top of my head no version of clangd works with anything prior.

**Comment by sam-mccall** [comment]
Right, our binary releases don't support glibc <2.18.
(The reason is thread_local support, the mechanism used for destructors on newer systems was first introduced in 2.18)

It's possible to build from source, and presumably the vendor could provide packages. I don't believe the llvm releases support old glibc either.

Unfortunately this isn't something we're likely to change, though we do attempt to avoid increasing this requirement.

**Comment by jievince** [comment]
I feel so sad
