### ISSUE TITLE
gcc, modules, build2, emacs and clangd

### ISSUE THREAD

**Issue by ram535** [clangd/clangd#758]
# Description of the problem
I build the latest version of gcc to try modules of the C++20 standard.
I also install gcc in a custom location. I add this to the env variables.
```
export CXX="g++"
export CC="gcc"
export PATH="$HOME/bin/gcc-trunk/bin:$PATH"
export MANPATH="$HOME/bin/gcc-trunk/share/man:$MANPATH"
export INFOPATH="$HOME/bin/gcc-trunk/share/info:$INFOPATH"
export LD_LIBRARY_PATH="$HOME/bin/gcc-trunk/lib64:$HOME/bin/gcc-trunk/lib:$LD_LIBRARY_PATH"
```
I also download the latest version of `build2` that have support for modules. It only support modules for the `gcc` compiler at the moment.

gcc and build2 have no problems compiling the sample code below.

`clangd` throw this errors.
main.cxx
```
[clang] Unknown argument: '-fmodule-mapper=main.o.d?@' (0:0)
[clang] Module 'hello' not found (0:0)
```
hello.mxx
```
[clang] Unknown argument: '-fmodule-mapper=main.o.d?@' (0:0)
[clang] Header file <string_view> (aka '/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/string_view') cannot be imported because it is not known to be a header unit (2:7)
[clang] Header file <iostream> (aka '/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/iostream') cannot be imported because it is not known to be a header unit (3:7)
[clang] Use of undeclared identifier 'std' (8:19)
[clang] Use of undeclared identifier 'std' (10:4)
[clang] Use of undeclared identifier 'std' (10:45)
```
It seems `clangd` it looking for the header files in the system installed version of gcc(old version).

# Sample code
```
// hello.mxx

export module hello;

import <string_view>;
import <iostream>;

export namespace hello {
  void  say_hello (const std::string_view& name)  {
    std::cout << "Hello, " << name << '!' << std::endl;
  }
}
```

```
// main.cxx

import hello;

int main () {  hello::say_hello ("World");}
```
```
# buildfile

cxx.std = experimental
cxx.features.modules = true

using cxx

assert $cxx.features.modules "no modules support for $cxx.signature"

mxx{*}: extension = mxx
cxx{*}: extension = cxx

exe{hello}: {cxx mxx}{*}
```

# Compiling the sample code
```
$ b config.cxx=g++
c++ ../../bin/gcc-trunk/include/c++/12.0.0/h{string_view}
c++ ../../bin/gcc-trunk/include/c++/12.0.0/h{iostream}
c++ mxx{hello}      
c++ cxx{main}          
ld exe{hello}     
$ ./hello 
Hello, World!
```

# Generate compile_commands.json using build2
To generate the `compile_commands.json` file you need to install [compiledb](https://pypi.org/project/compiledb/).
```
$ b -vn clean update |& compiledb
$ cat compile_commands.json 
[
 {
  "directory": "/home/last/Desktop/foo",
  "arguments": [
   "g++",
   "-std=c++2a",
   "-fmodules-ts",
   "-fmodule-mapper=main.o.d?@",
   "-o",
   "main.o",
   "-c",
   "-x",
   "c++",
   "/home/last/Desktop/foo/main.cxx"
  ],
  "file": "/home/last/Desktop/foo/main.cxx"
 }
]

```

# System information

Linux Mint 19.3 (Ubuntu 18.04 LTS)
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-03-09
[lsp-mode](https://github.com/emacs-lsp/lsp-mode) version 7.0.1
[gcc](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git) 12.0.0 20210422
clangd version 11.1.0
[build2](https://build2.org/community.xhtml#stage) 0.14.0-a.0.7a96e3b0a4bb

# Screenshots
![image](https://user-images.githubusercontent.com/9011002/115952555-6e290400-a49b-11eb-8d14-37ebad2ff9ca.png)
![image](https://user-images.githubusercontent.com/9011002/115952614-ceb84100-a49b-11eb-97c2-f974263949b2.png)

**Comment by RishabhRD** [comment]
I tried the same thing today. Seems like clang doesn't support fmodules-map thing. Also it seems like clangd doesn't read the bmi files generated by compiling modules automatically. Also generating compile_commands.json after writing each module would be hard. I don't know if LSP and build system can convey some messages to each other to make this thing automated.

**Comment by kadircet** [comment]
sorry for lack of attention here, i mostly avoided it because there's no nice answer.

first of all module format is not something stable or portable, it might become incompatible between different versions of the same compiler (e.g. clang-11 vs clang-12), let alone using those across compilers (clang vs gcc vs msvc etc).

moreover the implementation in clang seems to be lacking support for `-fmodule-mapper`, as you've also noticed (pretty clear from `[clang] Unknown argument: '-fmodule-mapper=main.o.d?@' (0:0)`). hence clang can't really figure out necessary source files to compile for building a module called `hello`. these are usually specified by modulemap files, clang supports specifying them via `-fmodule-map-file`.

so all in all, unfortunately there's nothing much to do here apart from:
- waiting for clang to get module-mapper support, some discussions in [here](https://lists.llvm.org/pipermail/cfe-dev/2020-May/065487.html)
- somehow tell build2 to specify module map files explicitly (in compile commands), rather than spawning a module mapper.
