### ISSUE TITLE
clang-tidy use-after-use no work

### ISSUE THREAD

**Issue by findNextStep** [clangd/clangd#759]
show both in mac and linux

other bug can show warning but use-after-move no give warning

i copy code from clang-tidy webpage for test see [unhandled-self-assignment](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-unhandled-self-assignment.html) and [use-after-move](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html)

the test code like below
```cpp
#include <iostream>
#include <string>
#include <vector>
class T {
  int *p;

public:
  T(const T &rhs) : p(rhs.p ? new int(*rhs.p) : nullptr) {}
  ~T() { delete p; }

  T &operator=(const T &rhs) {
    delete p;
    p = new int(*rhs.p);
    return *this;
  }
};
int main() {
  std::string str = "Hello, world!\n";
  std::vector<std::string> messages;
  messages.emplace_back(std::move(str));
  std::cout << str;
}
```
and show 
![image](https://user-images.githubusercontent.com/26270464/115993132-ffb38580-a603-11eb-8337-67f729f9e7b3.png)
clangd --version : clangd version 13.0.0 (https://github.com/llvm/llvm-project 5144f730a8a8a4c7c7984ff945187a9aa83c91ac)

with vscode

**Comment by kirillbobyrev** [comment]
`bugprone-use-after-move` check is not enabled by default, hence no warning. You can enable it by either

- enabling this check in the configuration file (see [documentation](https://clangd.llvm.org/config.html#clangtidy))
- adding `.clang-tidy` to your project and adding it to the list of enabled checks

Please let me know if this doesn't work and feel free to reopen the issue in that case!

**Comment by njames93** [comment]
@kirillbobyrev I think that check is actually disabled in clangd as it was causing instabilities when enabled

**Comment by kirillbobyrev** [comment]
Ah, okay, I see it now, thanks! I guess this was recent because I tried with the previous stable release (Clangd 11.0.0).

Sorry for the misiniformation @findNextStep, I guess you would have to use CLang-Tidy directly for that one, see https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/TidyProvider.cpp#L199-L216

**Comment by mika-fischer** [comment]
IMO. the fact that clangd alters the clang-tidy config the user has sepcified without telling him so is really dangerous.

It took me a long time to figure out that this check is unconditionally disabled in clangd while eveything else seems to be working.

Maybe clangd should just refuse to work unless the user:
- changes the .clang-tidy config to not include bugprone-use-after-move
- explicitly disables this check in clangd config

This would be much less surprising and give the user an opportunity to use other means to ensure that this check is actually run...

**Comment by sam-mccall** [comment]
I'm sorry you were surprised by this behavior.

What do you mean by "refuse to work"?
I don't think most users would agree that it's **less surprising** if diagnostics and code completion stop working in their editor because someone else wanted to enable a feature in clang-tidy.

**Comment by mika-fischer** [comment]
Maybe refuse to work is too strong. A prominent warning would also be nice, although it might be difficult to get it in front of the user.

But for me, this would have been better:
- Oh clangd refuses to start with error "Please disable bugprone-use-after-move because it causes crashes by adding this in .clangd"
- OK, need to find another plugin to do this check for me
- Install clang-tidy plugin with just this one check

Anyway, I've fixed this for me now. Just thought it's be nice to saving others from going on wild goose chases to figure out why they wrote bugs, they *know* clang-tidy can warn them about, but doesn't when used via clangd.

**Comment by findNextStep** [comment]
> I'm sorry you were surprised by this behavior.
> 
> What do you mean by "refuse to work"? I don't think most users would agree that it's **less surprising** if diagnostics and code completion stop working in their editor because someone else wanted to enable a feature in clang-tidy.

maybe we need to show warning and give a fix up by add use configuration in extension?

**Comment by zwuis** [comment]
Disabling `bugprone-use-after-move` is understandable but I think it sbould be documented.

**Comment by HighCommander4** [comment]
> Disabling `bugprone-use-after-move` is understandable but I think it sbould be documented.

I agree. We have a brief sentence at https://clangd.llvm.org/features#clang-tidy-checks which says "Not all checks work within clangd.", but it would be nice to list the checks or categories of checks that don't work.

Would you mind filing an issue at https://github.com/llvm/clangd-www/issues/ so we don't forget?
