### ISSUE TITLE
Progress indicator always spinning, showing "indexing: 0/1"

### ISSUE THREAD

**Issue by konradsa** [clangd/clangd#768]
I am using clangd 0.1.11 together with clangd 12 release version. I have a problem in Vscode where the progress indicator is constantly spinning, showing "indexing: 0/1". As far as I can tell though, clangd is idle and not indexing anything. I looked at the clangd Output log, and didn't really see any errors there. How can I debug what is causing this and how to stop this?

**Comment by kadircet** [comment]
`indexing: 0/1` is printed for background-indexing, hence it shouldn't block main clangd thread. this probably means clang(d) is probably taking quadratic/exponential time while trying to index a particular file in your compile_commands.json.

You can pass `--log=verbose` into clangd, then in the logs you should see
```
Indexing $FILE (digest:=$DIGEST)
Indexed $FILE ($A symbols, $B refs, $C files)
```

In your case you should see an `Indexing` without a matching `Indexed` line. Afterwards you can try sharing the contents of that file so that we can try to figure out why is indexing taking so long on that one. Or you can try it yourself to minimize that file by deleting parts of code while keeping indexing time long.
