### ISSUE TITLE
clangd not work in first time even if background index has finsh

### ISSUE THREAD

**Issue by findNextStep** [clangd/clangd#772]
when open a new file. There is an index time that cannot be ignored for clangd parse new file event if background index is over, so It's a very painful thing to view code with clangd between multiple files

[how ccls work when background index over and view code between multiple files](https://www.jianguoyun.com/p/DVy6kDoQx4m7CRjZ-_ED)

[how clangd work when background index over and view code between multiple files](https://www.jianguoyun.com/p/DTGkthcQx4m7CRjd-_ED)

**Comment by findNextStep** [comment]
```json
  "clangd.arguments": [
    "--background-index",
    "--compile-commands-dir=build/Debug",
    "-j=10",
    // "--folding-ranges",
    "--clang-tidy",
    "--query-driver=/usr/bin/clang++",
    "--all-scopes-completion",
    "--completion-style=detailed",
    "--function-arg-placeholders",
    "--header-insertion=iwyu",
    "--pch-storage=disk",
  ],
```
this is clangd config

clangd and ccls use same complie_commands.json

**Comment by kadircet** [comment]
unless you provide more specific information there's very little we can do. this sounds like you'd like clangd to have less warmup time and that's something we are constantly working on.

Feel free to re-open with more specific information like traces and logs (they include operation latencies) if you think there are particular slow pieces so that we can take a detailed look at those components.

**Comment by findNextStep** [comment]
it is not warmup time too long

after background-index over, clangd still take time when open a file instead of use cache

what i expect is if i enable background index and the index is over( in vscode , show like indexing 999/999![image](https://user-images.githubusercontent.com/26270464/117526191-0ecc0780-aff6-11eb-930b-e91a7d9fe952.png)) then i can open a file in complie_commands.json and use clangd feature  immediately. but now clangd take time to "reindex" and before "reindex" is over I can do almost nothing

**Comment by njames93** [comment]
When you open a file, the delay is because clangd needs to build a preamble for that file which involves parsing all the includes of the file.

**Comment by kadircet** [comment]
unfortunately clangd doesn't have such a cache. we have an index for the whole project, but it is not as useful when you are looking for symbols that are not visible outside the mainfile (e.g. the index doesn't contain implementation details, since one needs to be within that particular file to interact with those and clangd will index active files separately). we can try to approximate the behaviour by indexing all or just showing public symbols until warmup of the file but those are both problematic solutions (the first requires huge extra storage and memory, also makes serving slower. the latter would work poorly as index age increases, which is the case for huge monolithic codebases). Instead we are working on some pseudo-parsing approaches that might resolve these problems with better tradeoffs.

OTOH, workspacesymbols requests should be working out of the box purely relying on the index data. So you can give it a try instead of document symbols. i think this was triggered via ctrl+t on vscode.
