### ISSUE TITLE
"--malloc-trim" flag cause clangd to immediately crash

### ISSUE THREAD

**Issue by bokunodev** [clangd/clangd#778]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).
- my Sublime-LSP config
```JSON
"clangd":
{
	"command":[
		"clangd",
		"-j=2",
		"--malloc-trim", // cause crash
		"--log=verbose",
		"--pch-storage=disk",
		"--background-index",
		"--header-insertion=iwyu",
	],
	"enabled": true
}
```

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.
- sublime console didn't show me anything.

**System information**
Output of `clangd --version`:
`clangd version 13.0.0 (https://github.com/llvm/llvm-project be23d5e81439e701c67c767b06fe4c7afcde6af9)`

Editor/LSP plugin:
Sublime-LSP

Operating system:
Arch linux

**Comment by kadircet** [comment]
malloc-trim is already on by default so you don't need to specify it.

the reason you are seeing the crash is probably because `malloc-trim` is not available on the specific clangd binary you are using, hence clangd is dying at startup with an `unknown command line flag` failure. You can check sublime-lsp docs to figure out where the logs go. Without the logs there's little we can do. Also please mention how you've build the binary (cmake configuration, or where you've downloaded it)

**Comment by bokunodev** [comment]
you are right.
i have two clangd installed. one bundled with clang  and one from github release.
