### ISSUE TITLE
Simplify Inlay Hints

### ISSUE THREAD

**Issue by songzhi** [clangd/clangd#824]
Inlay hints can easily reach unacceptable length and contains a lot of useless type hints.

```c++
#include <vector>
#include <memory>
#include <tuple>
#include <string>

int main() {
  std::tuple<std::unique_ptr<int>, std::unique_ptr<double>, std::unique_ptr<std::string>> v;
  auto x = std::move(v);
}
```

![image](https://user-images.githubusercontent.com/18499849/126426055-fc033e58-c453-4415-b712-da258ea0764b.png)

**Comment by HighCommander4** [comment]
Thanks for filing. This is a very good point which I have noticed as well.

I can think of two ways to improve this, which can be pursued independently:

 1. Do not print default template arguments. There was previous work done on this in #106 which can be re-used.
 2. In a future version of the inlay hints protocol, hints may be "expandable", such that the initial hint can be `tuple<...>`, and then you can click on the `...` if you want to fill in its contents.

**Comment by songzhi** [comment]
I'm a [rust analyzer](https://github.com/rust-analyzer/rust-analyzer) user, too. Your ideas are already implemented in RA. I guess it's implementation may be inspireful.

Another idea is, the parameter inlay hints is pretty useful now, how about split the `--inlay-hints` flag into 2 flags, so we could show the parameter inlay hints only.

**Comment by kadircet** [comment]
A simpler solution we can tackle in the meanwhile is, just dropping the annotation if it is longer than a certain threshold. We have other ways of letting the user know of such information like hover and expand auto code action. So if they really want to know about a type in particular they can explicitly ask about it and in the meantime we get to not annoy people in general.

WDYT @HighCommander4 ?

**Comment by HighCommander4** [comment]
A length threshold sounds reasonable to me. (No reason we can't combine it with other mitigations, `SuppressDefaultTemplateArgs` in particular sounds like an easy win either way.)

**Comment by HighCommander4** [comment]
Apologies for the delay, I was away for a while.

[Here](https://reviews.llvm.org/D108972) is a patch to add a length limit for type hints.

I'm also looking into the idea of not printing default template arguments. Turns out the printing policy option to do that, `SuppressDefaultTemplateArgs`, is already set by default, however... it has no effect if `PrintCanonicalTypes` is also set. We set `PrintCanonicalTypes` because, for structured bindings that use the tuple protocol, the non-canonical type is something like `tuple_element<Index, Tuple>::type`, which is (1) fairly useless to begin with, and (2) shortened to just `type` because we set `SuppressScope`, making it completely useless. Will have to think about how to reconcile this.

**Comment by HighCommander4** [comment]
> Will have to think about how to reconcile this.

What I did for now is restrict the use of `PrintCanonicalTypes` to structured bindings only. I don't expect that to actually change behaviour for other type hints (other than starting to respect `SuppressDefaultTemplateArgs`, as desired), because the types for the other hints come from `DeducedType`, which doesn't currently store the sugared type anyways.

[Patch here](https://reviews.llvm.org/D108975).

**Comment by HighCommander4** [comment]
The two patches mentioned have now been merged. I do plan to work on some further improvements here, so I will leave the issue open.

@kadircet, a question about one of your [review comments](https://reviews.llvm.org/D108972#2981893):

> We think folding the arguments & dropping qualifiers until hint fits under the limit would be the most ideal

Could you expand on the "dropping qualifiers" part? Do you mean shortening `const T` to `T`, and/or `T&` to `T`?

I recognize that dropping parts of the type like that can shorten the string, but I worry that sometimes, something being const vs. non-const, or a reference vs. a value, can make the difference between the code compiling vs. not compiling. I feel like we could trigger situations where a user assumes a variable's type is exactly as written in the hint, and then get confused about errors they're getting.

**Comment by kadircet** [comment]
sorry by qualifiers i meant name specifiers. for example `foo::bar<a,b,c>` can be folded into `bar<...>`. `foo` is the qualifier to be dropped. otherwise i agree that dropping cv-qualifiers, attributes, ref-ness and such might be more confusing than useful.

**Comment by HighCommander4** [comment]
Ah, thanks for the clarification! We already drop name specifiers unconditionally, due to the use of `SuppressScope` [here](https://searchfox.org/llvm/rev/ac312a9d7c03f0be53834d3f295f1971aaf54649/clang-tools-extra/clangd/InlayHints.cpp#33).

Perhaps we should relax this, and show name specifiers which are **class names** when they fit into the length limit? (Namespace names seem like noise even if they fit into the length limit.)

**Comment by HighCommander4** [comment]
> Perhaps we should relax this, and show name specifiers which are **class names** when they fit into the length limit? (Namespace names seem like noise even if they fit into the length limit.)

A slightly more sophisticated strategy would be to prefer showing name specifiers for entities that we are not currently inside the scope of (so e.g. `SelectionTree::Node` would show up as just `Node` inside a `SelectionTree` method, but as `SelectionTree::Node` in a consumer of `SelectionTree`).

**Comment by kadircet** [comment]
> Ah, thanks for the clarification! We already drop name specifiers unconditionally, due to the use of SuppressScope here.

Right i forgot about SuppressScope.

> Perhaps we should relax this, and show name specifiers which are class names when they fit into the length limit? (Namespace names seem like noise even if they fit into the length limit.)

I am a little bit hesitant about that, because I think this will also trigger spelling of scopes in template arguments and they might be harder to prune, while making length a lot longer (especially if we decide to keep class names). Maybe we can prepend the class names afterwards, only for the main type and not for the template arguments. I believe this also easier implementation-wise, since we don't really have semantic information after printing the type, but we can still traverse the `NestedNameSpecifier` and extract a prefix from it. But I am not sure if there's enough value (especially for inlay hints, it would be more useful in explicit interactions like hover and such, in which I think we preserve scopes already).

**Comment by HighCommander4** [comment]
> Another idea is, the parameter inlay hints is pretty useful now, how about split the `--inlay-hints` flag into 2 flags, so we could show the parameter inlay hints only.

Enabling parameter hints and type hints independently of each other sounds like a useful configuration option in general. I wrote a [client-side patch](https://github.com/clangd/vscode-clangd/pull/227) to do this, which allows disabling either one by settings `clangd.inlayHints.parameterHints=false` or `clangd.inlayHints.typeHints=false` in the vscode settings.

**Comment by songzhi** [comment]
The parameter inlay hint should be omitted when it meets some rules.

Like:
```cpp
struct Bar {};
void foo(Bar* bar);

// ...
foo(/*inlay hint: bar*/ &bar); // it should be omiited.
```

**Comment by HighCommander4** [comment]
> ```c++
> foo(/*inlay hint: bar*/ &bar); // it should be omiited.
> ```

We do have logic to omit a hint if it matches the argument expression exactly (i.e. if the argument were `bar` here). However, it does not apply to `&bar`.

**Comment by Trass3r** [comment]
>     2. In a future version of the inlay hints protocol, hints may be "expandable", such that the initial hint can be `tuple<...>`, and then you can click on the `...` if you want to fill in its contents.

That sounds like the way to go.
But should also be fine in the meantime since the hover popup gives you the full type.

**Comment by zhangyi1357** [comment]
I'm interested in this issue, and I've downloaded the source code to read through it. 
I understand that the type hint limit is controlled by a static member variable named 'TypeNameLimit' with a default value of 32 in the 'InlayHintVisitor' class. However, I'm not sure how to add it to the configuration. 

Can someone give me some hints? I would also appreciate any other advice, as this is my first time participating in an open-source community. Thank you!

**Comment by HighCommander4** [comment]
I filed follow-up issues for the remaining actionable suggestions discussed in this issue thread: https://github.com/clangd/clangd/issues/2268, https://github.com/clangd/clangd/issues/2269, https://github.com/clangd/clangd/issues/2270.

I'm going to close this one.
