### ISSUE TITLE
Semantic token modifier for reference parameters

### ISSUE THREAD

**Issue by tom-anders** [clangd/clangd#839]
If I have a function 

`void foo(double& refParameter) {...}`

and call it like 

`foo(someLocalVar)` then it would be really cool if the semantic token for `someLocalVar` would somehow indicate that this is a reference parameter. This would allow one to spot places where a function might modify the parameters more easily, since it's not always that obvious on the calling side.

**Comment by HighCommander4** [comment]
I agree, this would be a really neat enhancement.

I actually implemented this in Eclipse CDT a few years ago (see [this release note](https://wiki.eclipse.org/CDT/User/NewIn92#Syntax_coloring_for_variables_passed_by_non-const_reference)), and it's one of the things I've been meaning to implement in clangd.

One complication here is that in general, a function argument can be an arbitrary expression (including in cases where this modifier might apply, for example, `a().b()->c().field`). Eclipse CDT didn't have the notion of token modifiers, so the entire expression was highlighted in this case.

In clangd, if we're using a token modifier, we can either:
  1. Create a new token for the whole expression to house the modifier; or:
  2. Try to deconstruct the epxression and only apply the modifier to the identifier token at the end. (There are still going to be edge cases. For example, a function call expression like `a().b()` can itself return a reference (to, say, an object of some enclosing scope) and be passed as an argument for a reference parameter. In this case, there is no identifier token to apply the modifier to.)

**Comment by tom-anders** [comment]
Cool! How difficult would it be to implement something like this for someone unfamiliar with the code base? If you say this deserves the "good first issue" tag, I'd be happy to help if necessary!

**Comment by HighCommander4** [comment]
I've been thinking about how to implement this in clangd. There are some considerations related to the way clangd computes semantic highlightings that need to be worked through.

First, some background on how clangd computes semantic highlighting:

  * Tokens are computed in two phases:
      1. The [first phase](https://searchfox.org/llvm/rev/012173680f368bff9b4e3db21e1381360422cdc6/clang-tools-extra/clangd/SemanticHighlighting.cpp#697) performs an operation called `findExplicitReferences`, which is not specific to semantic highlighting. This operation takes an AST node, and finds all the places inside that node which are references to some declaration. The results are represented as `ReferenceLoc`, which stores the source range of the reference and the declaration being referred to, but **not** the AST node (e.g. `DeclRefExpr`) that contains the reference. Semantic highlighting invokes this operation on the entire AST as input, and creates highlighting tokens for the returned references, deciding the token kind and modifiers based on the declaration being referenced.
      2. The [second phase](https://searchfox.org/llvm/rev/012173680f368bff9b4e3db21e1381360422cdc6/clang-tools-extra/clangd/SemanticHighlighting.cpp#695), called `CollectExtraHighlightings`, performs an additional AST traversal specific to semantic highlighting, using `RecursiveASTVisitor` (also used in the implementation of `findExplicitReferences`), which provides additional highlighting tokens for dependent names (which are usually skipped by `findExplicitReferences` because we don't know what the target declaration is), and some other edge cases.
  * The tokens (from the two phases combined) go through a de-duplication step, where if there are multiple tokens with the same source range, a [resolveConflict](https://searchfox.org/llvm/rev/012173680f368bff9b4e3db21e1381360422cdc6/clang-tools-extra/clangd/SemanticHighlighting.cpp#318) function is called to determine how to combine them.

So, which phase should contain the logic for adding this modifier?

The vast majority of the tokens to which the modifier would apply are produced during the first phase, so it would be nice to compute the modiifer during the first phase as well. Unfortunately, as mentioned the `ReferenceLoc` that we have available in the first phase contains no information about the context of the reference that would allow us to determine "this is being passed an argument to a function" (and examine that function's parameter type etc.).

In the second phase, we have more flexibility, e.g. we can easily extend our `RecursiveASTVisitor` to process call expressions specifically and look at each argument. However, the modifier we produce needs to be attached to a token, and that token needs to be combined gracefully (during the de-duplication step) with any tokens created during the first phase for the same range.

That leads me to two possible approaches for implementing this:

**Approach 1: logic in second phase**

Extend `CollectExtraHighlightings` to process call expressions (`CallExpr`), and check if their argument expressions are of interest (i.e. the corresponding parameter is a non-const reference). For simplicity, we can start by only handling argument expressions which are identifiers (`DeclRefExpr`). If so, produce a highlighting token with a dummy highlighting kind and the new modifier. Teach `resolveConflict()` to combine this token with the token produced during the first phase in such a way that the highlighting kind from the first phase is used, but the new modifier is combined with any modifiers from the first-phase token.

**Approach 2: logic in the first phase**

Extend `ReferenceLoc` to also store the AST node that contains the reference (represented as `DynTypedNode`), and `findExplicitReferences` to populate it with this information. Use this AST node during the first phase to check whether the node is an argument expression of a function call, and if so add the modifier if appropriate.

**Analysis**

Approach 1 seems simpler to implement, if a bit hacky due to the neeed for the dummy highlighting kind.

Approach 2 is more invasive (it modifies code not specific to semantic highlighting), though it's possible that other consumers of `findExplicitReferences` may find the information added to `ReferenceLoc` useful in the future.

I would lean towards Approach 1.

---

@tom-anders if you're interested in trying to implement this, I would be happy to provide (further) guidance. However, perhaps we should first give @kadircet or @sam-mccall a chance to offer an opinion on Approach 1 vs. Approach 2, so that we don't spend time implementing an approach that wouldn't pass code review.

**Comment by HighCommander4** [comment]
I guess another advantage of Approach 2 would be that it would more easily enable other future enhancements to semantic highlighting where the token kind or a modifier represents a property of the reference itself, not a property of the declaration being referenced.

**Comment by sam-mccall** [comment]
+1 this would be a great feature to have.

> How difficult would it be to implement something like this for someone unfamiliar with the code base?
I think the good news is it's fairly clear which part of the code to change (at least in approach 1). The tricky part for a newcomer I think will be learning about the clang AST classes, working out precisely which AST patterns are relevant and how to efficiently find them.

@HighCommander4 
> So, which phase should contain the logic for adding this modifier?

The analysis makes sense to me. Approach 2 introduces a (fairly elegant) general mechanism, and there are some solid but not overwhelming use cases (SemanticHighlighting as you point out, and also dealing with ObjC method calls where NameLoc isn't sufficient).

But there's a little problem: "passed as lvalue reference" is a property of the parent chain rather than the node itself. We want to find a parent `CallExpr` (or maybe `CXXConstructExpr` or `InitListExpr`). We allow casts/parens between (e.g. DerivedToBase!), but no lvalue->rvalue conversions. And we probably don't allow the callee to be dependent, because then instantiation may insert casts.

All of this is possible to implement based on the node, because we have the parent map and can walk up. But it's not very natural: all the helpers about implicit nodes expect to traverse the other way, you have to be careful not to walk up the callee edge etc.
Starting at the CallExpr and walking down seems like it will be much clearer.

So I'd probably go with approach 1 here too, though I don't think I'd oppose approach 2 if someone can really get it to work and is willing to write the extra tests for the extended API.

> If so, produce a highlighting token with a dummy highlighting kind and the new modifier. Teach resolveConflict() to combine this token

I assume the plan is to simply drop the modifier if no "real" token at that location gets produced? (LSP requires tokens to have a kind).
In that case I think it's marginally simpler/more direct to have a `map<SourceLocation, Modifiers> ExtraModifiers` in HighlightingsBuilder and then have collect() merge them in. But either should work.

**Comment by tom-anders** [comment]
Thanks @HighCommander4 for the detailed introduction and thanks @sam-mccall for your thoughts. So it looks like we're all leaning towards approach 1, right? Should we wait for @kadircet to also give his opinion here?

Anyway, this looks like a fun and interesting task and I'd definitely be interested in trying to implement this.

**Comment by HighCommander4** [comment]
Sam, thanks for the detailed thoughts! Good point about the parent chain.

@tom-anders I think we're good to go to give Approach 1 a try.

A few pointers for getting started:

 * [Instructions for building clangd](https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clangd#building-and-testing-clangd)
 * Docs about [the clang AST](https://clang.llvm.org/docs/IntroductionToTheClangAST.html) and [RecursiveASTVisitor](https://clang.llvm.org/docs/RAVFrontendAction.html)
 * [Here](https://searchfox.org/llvm/rev/012173680f368bff9b4e3db21e1381360422cdc6/clang-tools-extra/clangd/SemanticHighlighting.h#61) is the list of modifiers we'll want to add to.
 * [Here](https://searchfox.org/llvm/rev/012173680f368bff9b4e3db21e1381360422cdc6/clang-tools-extra/clangd/SemanticHighlighting.cpp#494) is the `CollectExtraHighlightings` visitor that we'll want to extend with a `VisitCallExpr` method. (Sam makes a good point that there are a couple of other expression types that can represent calls, such as `CXXConstructExpr` for constructor calls. Feel free to leave those for a second iteration of the patch if you'd like.)
 * [Here](https://searchfox.org/llvm/rev/012173680f368bff9b4e3db21e1381360422cdc6/clang-tools-extra/clangd/unittests/SemanticHighlightingTests.cpp#99) is the test for semantic highlighting that we'll want to extend to check that our new modifier is being assigned correctly. Note that the inputs are pieces of C++ code with annotations that encode the expected token kind and modifiers. For example, `double $Field_decl[[SomeMember]];` means that the token `SomeMember` is expected to have the token kind `Field` and the modifier `decl`. (The code that will actually be parsed is just `double SomeMember;`.)

Feel free to reach out with questions here or in the #clangd channel on [Discord](https://discord.gg/xS7Z362).

**Comment by tom-anders** [comment]
@HighCommander4 Thanks again for the helpful links and explanations! I'll read the documentation, play around with the code a bit and then try to implement approach 1, let's see how it goes :)

**Comment by gislan** [comment]
I'll just mention that a while ago I added a basic version of trying to figure out if the argument is passed by reference or value to the hover code. Take a look at maybeAddCalleeArgInfo() in clang-tools-extra/clangd/Hover.cpp.

**Comment by tom-anders** [comment]
@gislan Thanks!

@HighCommander4 Just a quick heads-up: I think there's a small typo in the [build instructions](https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clangd#building-and-testing-clangd): `-DLLVM_ENABLE_ASSERTS=On` should be `-DLLVM_ENABLE_ASSERTIONS=On`

**Comment by HighCommander4** [comment]
> @HighCommander4 Just a quick heads-up: I think there's a small typo in the [build instructions](https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clangd#building-and-testing-clangd): `-DLLVM_ENABLE_ASSERTS=On` should be `-DLLVM_ENABLE_ASSERTIONS=On`

Good catch! Would you like to submit a small patch to correct it?

**Comment by tom-anders** [comment]
Sure! I haven’t set up the llvm mailing lists and code review tools yet, so I’ll submit it once I have finished working on the new semantic token modifier (making good progress btw, the basic functionality seems to work for both DeclRefExpr and MemberExpr. gonna check now if there are any false positives and will look at the special cases that you and Sam mentioned)

**Comment by HighCommander4** [comment]
Interesting alternative presentation suggested [here](https://github.com/clangd/clangd/issues/313#issuecomment-922744284): a prefix `&:` inlay hint for such arguments.

**Comment by tom-anders** [comment]
That also sounds really cool and I think I like it better than having a highlighting modifier for it. However, not all editors support displaying inlay hints (yet), e.g. neovim currently has [this PR](https://github.com/neovim/neovim/pull/9496) open.

**Comment by HighCommander4** [comment]
Thanks @tom-anders for implementing! I think this issue can be closed, let me know if I overlooked anything. (The suggestion for an inlay hint can be pursued in a separate issue if desired.)
