### ISSUE TITLE
can not goto define at large project(file number > 2000) when vim open header

### ISSUE THREAD

**Issue by haolongzhangm** [clangd/clangd#853]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`:
12 

Editor/LSP plugin:

Operating system:
ubuntu20.04

**Comment by haolongzhangm** [comment]
for example: 
```
1.cc file
#include <1.h>
#include <cstdio>

void test_function() {
    printf("hhhhhhh\n");
}
1.h file
void test_function();

compile_commands.json file
[
{
  "directory": "/home/zhl/tmp/test",
  "command": "/usr/bin/c++  -isystem /home/zhl/tmp/test -std=c++11 -o /home/zhl/tmp/test/1.cc.o -c /home/zhl/tmp/test/1.cc",
  "file": "/home/zhl/tmp/test/1.cc"
},
]

```

when this small project , vim  only open 1.h  ,then clangd can goto define , then auto jump to 1.cc

**Comment by haolongzhangm** [comment]
same vim/ycm/clangd-12 when above env 

if project is so  big when so many file (2000+ ),   clangd  already index all file at background （because:  find .cache/ | wc -l   will not increase ， about 8572 file）

if i only open a header , like 1.h,  then clangd can not go to define in the 1.cc 

BUT, when i open 1.h and 1.c into vim buffer, then clangd can auto goto define at 1.cc



so any config to let goto define work at large project ?

**Comment by haolongzhangm** [comment]
same issue happend at linux kernel source code,    https://github.com/torvalds/linux
1: use bear make linux source code , then will create a compile_commands.json
2: then vim ONLY   open a .h file , clangd will not goto the define  in .c
3: then vim open .h and .c   at same time, which means , will loader file in the vim buffer,   then clangd can easy goto the define in .c  file the .h file

**Comment by HighCommander4** [comment]
The behaviour you describe suggests the .cc file is not indexed on disk (or clangd is not loading its contents from the index). Opening the .cc file causes it to be indexed in clangd's in-memory index, that's why it starts working.

The list of files to index is based on the CDB (compilation database, i.e. the `compile_commands.json` file), and by default the CDB is found by searching the ancestor directories of the file that is opened (in this case, the .h file).

So, the first thing to check: is the .h file located in the directory tree of the directory containing the `compile_commands.json`? If not, clangd will not find the CDB automatically when opening the .h file, and you may need to point it to the CDB explicitly using the `--compile-commands-dir` command line argument.

If that's not the issue, then please share logs as instructed in the issue template.
