### ISSUE TITLE
AST range for nested template instantiations is off by one

### ISSUE THREAD

**Issue by ckandeler** [clangd/clangd#871]
Consider this code:
```
template<typename T> struct S {};
S<S<int>> s;

```
In line 2, there are two nested TemplateSpecialization nodes. The inner one's range has the same end value as the outer one's, i.e. it covers the second '>' and thus extends one character too far.

Output of `clangd --version`:
clangd version 14.0.0 (https://github.com/llvm/llvm-project.git 5685eb950da7c6901c8b264a3c93e8ea63b34d3d)
Features: linux+debug
Platform: x86_64-unknown-linux-gnu

**Comment by ckandeler** [comment]
It may well be that this (mis-)information just comes from lower LLVM levels, but I'm encountering it when using clangd's textDocument/ast request, so I'm reporting it here.

**Comment by HighCommander4** [comment]
Interesting situation :) Here's my analysis of it:

 * Clang tracks source ranges internally at the token level rather than the character level (i.e. start token, end token).
 * The lexer interprets the `>>` as a single greater-than token.
 * When the parser then realizes the first `>` of the `>>` token actually closes a template-argument-list, it rewrites it as `> >`, with a space. To house the rewritten tokens, it allocates a virtual buffer. The end location of the parsed template-id then becomes the first `>` token in the virtual buffer.
 * Clangd then looks at the template-id's source range, and tries to produce a file range to provide in the request. As part of this, the end location in the virtual buffer needs to be translated back to a spelled location in the file.
 * This translates happens at the token level, so its result is the `>>` spelled token in the file.
 * Finally, when producing a character range, we take the last character of the end token, thereby including the second `>` as well.

It's not immediately clear to me how to fix this. I guess we'd need to perform the translation from the internal source range (which is allowed to refer to virtual buffers, inside macro expansions, etc.) to a file range at a character level, but I don't know that we have the infrastructure in place to do that.

Is this causing you an actual problem, or is it more just something you noticed that looks wrong?

**Comment by ckandeler** [comment]
I encountered this when parsing the AST to implement "parentheses highlighting" for angle brackets in templates. I can work around it, so it's not a pressing issue, but I thought it should probably get reported out of principle.

**Comment by ckandeler** [comment]
[Semit-OT: If the list of semantic tokens didn't include just symbols, but also operators etc, I wouldn't need to look at the AST at all there ...]

**Comment by kadircet** [comment]
I am not sure what to do here. I believe this is WAI. as @HighCommander4 also pointed out, this is an unfortunate consequence of not C++ being context-dependent. OTOH, AST actually has enough information to map these back to their proper locations, i.e. SourceManager::getFileLoc will do the right thing.

Hence closing it. If you notice this is not being handled properly in certain clangd features please file bugs about those particular cases though.
