### ISSUE TITLE
Relax the fuzzy matching rules for code completion

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#88]
* Symbol list
1. abc
2. a_bc
3. ab_c

* Expected behavior
Enter `ac`, the code completion should list `abc`, `a_bc`, `ab_c`(`ab_c` is the best match), currently only listed `ab_c`.

**Comment by sam-mccall** [comment]
Currently there's (almost) one set of fuzzy matching rules for everything.

Our experience was that looser fuzzy-matching rules were problematic in cases where the universe of results was large (e.g. all top-level symbols in included headers, or project-wide symbols in a namespace). It was hard to get ranking right, harder to verify you were choosing the right result, it hurt index resource usage and performance.

However it's much less clear these downsides apply to e.g. completion of members (where the total # results are limited by the context) or local variables (where these particular completions probably aren't spammy, although others are).

So one option is to use different rules for matching against different types of symbols. This is #37, which only got as far as a prototype so far. The obvious downside is the inconsistency might be confusing, rather than magic. Do you think this is a good idea? Would it address your concern?

**Comment by lh123** [comment]
Thanks for the quick reply.
I think it's best to add an option to let the user decide whether to use Strict or Lax mode. (Microsoft-vscode-cpptools enables loose fuzzy matching globally)

**Comment by sam-mccall** [comment]
Adding an option helps very few users (most will use whatever the default is), and changing the option would invalidate the index, so it's unlikely we'll do that.

Do you have a realistic example of important completions that are missing?

**Comment by lh123** [comment]
> Can you give a realistic example of important completions that are missing?
1. In some embedded projects, there are many macro definitions with long names. The looser fuzzy matching can help me find the macros we need, if I only remember the partial names and the first letters.
2. Most language servers client use loose fuzzy matching. Use the same match pattern for better consistency.

**Comment by sam-mccall** [comment]
I'm looking for examples from real usage:
 - what's the name of the symbol
 - what's the string you want to type to find it
 - what kind of symbol is it and where is it defined

Macros are handled differently: strict prefixes are required (see fuzzyScore() in CodeComplete.cpp). The reason is that macros are a global namespace that is available in any context, so they tend to be very spammy. You might consider turning that off in the code and using it for a while.

**Comment by lh123** [comment]
Thanks for the quick reply.
> what's the name of the symbol

SVGSolidcolorElement
> what's the string you want to type to find it

color
> what kind of symbol is it and where is it defined

struct, defined in gloable

**Comment by kadircet** [comment]
Closing this as the only actionable conclusion is probably some sort of #37. Feel free to re-open as a discussion if you think there's more to be discussed.

**Comment by sanasl1234** [comment]
It would be handy if typing `i32` shows `int32_t`, and the like.

**Comment by arrio464** [comment]
> I think treating "boundary" of letter and number as "break point" (like `_` or CAPITAL letters) would be very helpful.我认为将字母和数字的“边界”视为“断点”（如 `_` 或大写字母）会非常有帮助。 It would be handy if typing `i32` shows `int32_t`, and the like.如果输入 `i32` 显示 `int32_t` 等，那就很方便了。
> 
> e.g. 例如 `f2b` shows `foo2bar` `f2b` 显示 `foo2bar` `a1` shows `abcd1` `a1` 显示 `abcd1` `v3f` shows `Vector3f` / `Vec3f` ... `v3f` 显示 `Vector3f` / `Vec3f` ... `v3d` shows `Vector3d` / `Vec3d` ... `v3d` 显示 `Vector3d` / `Vec3d` ...
> 
> It enabling more reasonable matching without over relaxing the rule.它可以在不过度放松规则的情况下实现更合理的匹配。

Yes, I think this is necessary.
Maybe at least a configuration file should be provided to decide whether it is turned on or not.
See also: #1236
