### ISSUE TITLE
Wrong semantic tokens on changes around ifdef-ed code near top of a file

### ISSUE THREAD

**Issue by ckandeler** [clangd/clangd#912]
Consider this piece of code at the beginning of a file:
```
#ifdef FOO
#endif
#define BAR
```
The initial semantic tokens are as expected. But after adding a newline at the beginning, clangd will report a semantic token of type "comment" at position 0 (with length 1).
Removing the newline again will result in line 3 being wrongly reported as "comment", plus a token of type "macro" will still be reported in line 4 (which does not exist anymore).
Debugging shows that these are not due to mis-calculations of the delta, but are really reported by ClangdServer::semanticHighlights(). 
It should be noted that these oddities appear to occur only if no actual symbols precede the macros. E.g. after inserting "int x;" at the top of the file, none of this can be reproduced anymore. But of course, C++ sources often start this way, e.g. with conditional includes.

**System information**

Output of `clangd --version`: 
clangd version 14.0.0 (https://github.com/llvm/llvm-project.git e2b7aabb57d50a9b16fe71c1f80b983dd61d3fbd)
Features: linux+debug
Platform: x86_64-unknown-linux-gnu

**Comment by HighCommander4** [comment]
I have not been able to reproduce this issue with vscode.

I do not notice any visual problems while performing the above edits. I also checked what LSP messages clang is sending, and here's what I'm seeing.

On initial file open:

> V[00:51:08.933] <<< {"id":87,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/nr/dev/projects/testing/vscode-test/main.cpp"}}}
> V[00:51:08.991] >>> {"id":87,"jsonrpc":"2.0","result":{"data":[0,0,10,20,0,1,0,6,20,0,1,8,3,19,4097],"resultId":"1"}}

After the edit which adds the newline at the beginning:

> V[00:51:36.819] <<< {"id":96,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"1","textDocument":{"uri":"file:///home/nr/dev/projects/testing/vscode-test/main.cpp"}}}
> V[00:51:36.819] >>> {"id":96,"jsonrpc":"2.0","result":{"edits":[{"data":[1,0,10,20,0],"deleteCount":5,"start":0}],"resultId":"2"}}

After the edit which removes the newline:

> V[00:51:50.548] <<< {"id":102,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"2","textDocument":{"uri":"file:///home/nr/dev/projects/testing/vscode-test/main.cpp"}}}
> V[00:51:50.570] >>> {"id":102,"jsonrpc":"2.0","result":{"edits":[{"data":[0,0,10,20,0],"deleteCount":5,"start":0}],"resultId":"3"}}

The semanticTokens encoding takes a bit of working through, but having done that this looks correct to me.

Perhaps you're using a different client, which is sending different requests, or getting different responses from some reason? In any case, attaching a clangd log (stderr of clangd run with `--log=verbose`) would be very helpful.

**Comment by ckandeler** [comment]
Initial open:
```
{"id":"{c28ed431-cb15-4d1c-9b25-0a9782211616}","jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///tmp/tokens/main.cpp"}}}
{"id": "{c28ed431-cb15-4d1c-9b25-0a9782211616}", "jsonrpc": "2.0", "result": {"data": [0,0,10,20,0,1,0,6,20,0,1,8,3,19,8193],"resultId": "1"}}
```
```
Newline insertion:
{"id":"{49cc72c0-b79b-4759-b998-76dac3a74bea}","jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"1","textDocument":{"uri":"file:///tmp/tokens/main.cpp"}}}
{"id": "{49cc72c0-b79b-4759-b998-76dac3a74bea}","jsonrpc": "2.0","result": {"edits": [{"data": [0,0,0,20,0,1,0,10,20, 0],"deleteCount": 10,"start": 0}],"resultId": "2"}}
```
Newline removal:
```
{"id":"{8b62d489-55cc-46a0-807a-64cb7b7892eb}","jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"2","textDocument":{"uri":"file:///tmp/tokens/main.cpp"}}}
{"id": "{8b62d489-55cc-46a0-807a-64cb7b7892eb}","jsonrpc": "2.0","result": {"edits": [{"data": [1,0,6,20,0,1,0,11,20,0],"deleteCount": 10,"start": 0}],"resultId": "3"}}
```
The client is Qt Creator.

**Comment by ckandeler** [comment]
[log.txt](https://github.com/clangd/clangd/files/7452121/log.txt)
Also attached a complete log of the entire session. (Pretty noisy, also contains client-side debug output.)

**Comment by HighCommander4** [comment]
Very odd. The `didOpen` and `didChange` requests in your log look the same as mine, so our clangd's are seeing the same file contents / changes... and yet the responses to the delta requests are different.

**Comment by HighCommander4** [comment]
For reference, [here](https://github.com/clangd/clangd/files/7455948/issue-912-vscode-log.txt) is a log of the same actions taken in vscode (which produces the expected deltas).

**Comment by ckandeler** [comment]
Perhaps some subtle difference in the clang invocation? Doesn't sound very convincing, but I'll try making the command lines more similar.

**Comment by HighCommander4** [comment]
One different I notice is that the vscode client capabilities include `workspace.semanticTokens.refreshSupport = true`, and accordingly clangd sends `workspace/semanticTokens/refresh` requests. However, I see no difference in the outcome if I disable that behaviour on the clangd side.

**Comment by HighCommander4** [comment]
Ah, I think we're getting warmer!

Order of operations for vscode:

> V[16:11:02.479] Built preamble of size 215540 for file /home/nr/dev/projects/testing/vscode-test/main.cpp version 1
> V[16:11:02.540] ASTWorker running SemanticHighlights on version 1 of /home/nr/dev/projects/testing/vscode-test/main.cpp
> V[16:11:06.014] Built preamble of size 215544 for file /home/nr/dev/projects/testing/vscode-test/main.cpp version 2
> V[16:11:06.053] ASTWorker running SemanticHighlights on version 2 of /home/nr/dev/projects/testing/vscode-test/main.cpp

Order of operations with qt creator:

> qtc.languageclient.messages: V[10:26:24.610] ASTWorker running SemanticHighlights on version 1 of /tmp/tokens/main.cpp
> qtc.languageclient.messages: V[10:26:24.618] Built preamble of size 216436 for file /tmp/tokens/main.cpp version 1
> qtc.languageclient.messages: V[10:26:26.280] ASTWorker running SemanticHighlights on version 2 of /tmp/tokens/main.cpp
> qtc.languageclient.messages: V[10:26:26.288] Built preamble of size 216432 for file /tmp/tokens/main.cpp version 2

With qt creator, we are getting semantic highlighting requests (and responding to them) before the preamble build for the corresponding version of the file completes. This is why we're getting different answers.

**Comment by HighCommander4** [comment]
So I guess it is sort of related to refreshSupport, in that with refreshSupport, vscode asks for semantic tokens (only?) when getting a refresh request, and we send the refresh request when the preamble build completes.

However, as I said, I tested vscode with refreshSupport disabled on the clangd side, and... it still manages to send the semantic tokens requests "late enough" that they arrive after the preamble build completes.

**Comment by ckandeler** [comment]
I see. So I suppose a client-side workaround might be to always wait for the refresh request? Doesn't seem to be right according to the spec, but if we know clangd always sends it as some sort of indicator that it's ready ...

**Comment by HighCommander4** [comment]
Ok, so to try and put the above findings in context:

 * Clangd has an optimization where it splits a file into the "preamble" (roughly, the includes / other preprocessor directives at the top), and the rest of the file. As you edit the main part of the file, the parsed version of the preamble is reused, and only the rest of the file is re-parsed. The idea is that the preamble generally contains many more declarations (transitively included) than the rest of the file, but you mostly edit the rest of the file.
 * If you're editing the preamble itself, the preamble needs to be re-parsed ("rebuilt"), which can take a comparatively long time.
 * So, when responding to semantic tokens, if we have a stale preamble, we just provide tokens based on the stale preamble rather than waiting for the preamble build to complete. This means tokens in the preamble region are accurate, but that's probably worth getting accurate tokens for the rest of the file sooner.
 * Whe the preamble build does complete, we want the client to request semantic tokens again, to get the accurate ones for the preamble, this is accomplished using the refresh support,

So, from the editor's point of view, it's normal that the ordering of (1) when the initial semantic tokens request arrives to clangd, and (2) the preamble build completes, can vary. I.e. in this case, with a trivial preamble, qt creator happens to send it sooner, and vscode a bit later, but I don't think either one is right or wrong.

However, to (also) get the accurate preamble tokens when the preamble build completes, it would be good for qt creator to implement refreshSupport.

Let me know if that makes sense!

**Comment by HighCommander4** [comment]
> So I suppose a client-side workaround might be to always wait for the refresh request?

I think the previous comment covers this, but to address this point directly: no, I think the client should send a semantic tokens request as soon as possible (after the didChange), because a preamble build can take a longer time in general.

However, for best results, it should _also_ send a semantic tokens request in response to a refresh request. In most typical scenarios (involving larger files than this trivial one), that will be a second request for the same file contents, to pick up accurate preamble tokens. Note that this only applies to cases where you're editing the preamble, so it's comparatively rare.

**Comment by ckandeler** [comment]
Yes, I think got it. We receive a temporarily wrong state due to correctness/speed trade-off, which the server then instructs us to correct by issuing another request. Thanks for looking into this.

**Comment by ckandeler** [comment]
Proposed solution works for me.
