### ISSUE TITLE
workspace/symbol only does prefix search for macros

### ISSUE THREAD

**Issue by ckandeler** [clangd/clangd#914]
Consider this piece of code:
```
#define SOMEFOO
#define FOOSOME
#define SOMEFOOOTHER

void func();
void otherFunc();
```
Doing workspace/symbol for FOO returns only one item, "FOOSOME".
But searching for "func" returns both "func" and "otherFunc". It's unexpected that macros are treated differently with regards to matching.

Output of `clangd --version`:
clangd version 14.0.0 (https://github.com/llvm/llvm-project.git e2b7aabb57d50a9b16fe71c1f80b983dd61d3fbd)
Features: linux+debug
Platform: x86_64-unknown-linux-gnu

**Comment by ckandeler** [comment]
I now see in the code that this is on purpose:
`// Macros can be very spammy, so we only support prefix completion.`
However, couldn't it be more pragmatic, e.g. by taking the length of the query into account?

**Comment by HighCommander4** [comment]
cc @sam-mccall 

The patch which introduced this is https://reviews.llvm.org/D47936, but I don't see any context (like a bug report) motivating the change other than "macros are terribly spammy at the moment".

**Comment by sam-mccall** [comment]
Yes, this was probably just an offline discussion (I don't think we had a functioning bug tracker at that time!)
It was around code completion experience though FWIW the same ideas seem to apply to workspace-symbol.

> Doing workspace/symbol for FOO returns only one item, "FOOSOME".
> But searching for "func" returns both "func" and "otherFunc".

For a fair comparison you should name your macros `SOME_FOO` etc: clangd does care about word boundaries. `func` wouldn't match `otherfunc` either...

> It's unexpected that macros are treated differently with regards to matching.

... but it still won't work, because macros *are* treated differently.

---

Macros were showing up in completion a lot in irrelevant contexts.
 - macros are heavily used in the standard library/builtins, so lots are always in scope
 - lack of namespaces meant we got them all for every query
 - the majority were implementation details (again because of lack of namespacing)
 - they tended to have very long multiword names, which caused them to fuzzymatch many short queries

It was very common that a query string that was specific enough to match only one "real" symbol would match several macros as well. Even when we got the ranking right, this was distracting. And ranking was hard: macros are unstructured and lack signals. We couldn't just downrank all macros, because occasionally you really did want one.

Eventually we thought it felt buggy if macros weren't in the list if you specifically looked for them, but we could live without them being suggested. Prefix match felt like a satisfying definition of "looking for them" that was compatible with client-side filtering.

---

> However, couldn't it be more pragmatic, e.g. by taking the length of the query into account?

LSP has this annoying client-side filtering concept: as the user keeps typing an identifier, the editor is allowed to filter down the set of results locally instead of retrieving a new set from the server. Effectively this means that the results for "wxyz" need to be a subset of the results for "wx". Otherwise results end up mysteriously and inconsistently missing in some editors, some of the time.

This means that if we want to return "SOMEFOOOTHER" for a query of "fooother", we also should return it for a query of "f", which is hard to do without attracting spam.

**Comment by ckandeler** [comment]
> For a fair comparison you should name your macros `SOME_FOO` etc: clangd does care about word boundaries. `func` wouldn't match `otherfunc` either...

Indeed. I did not know that; my assumption was that a generic substring search would be done. I'll close this one then.
