### ISSUE TITLE
Cann't find symbols which are in co_await expression

### ISSUE THREAD

**Issue by shuyanzhu** [clangd/clangd#939]
**System information**
Clangd version (from the log, or `clangd --version`): 13.0.0
clangd extension version: v0.1.13
Operating system: Windows frontend & Ubuntu18.04 as remote backend

Like the question, I can't find the symbols which are in co_await expression. Need to say that project can be compiled: 
![image](https://user-images.githubusercontent.com/24547435/143732532-bd2f67df-5b04-4d2c-a905-204ee1fb09f7.png)

Clangd cann't even find the definition of produce_tokens or transfer which are defined in the same file with function proxy. In other expression without operator co_await, clangd works well. I think it's a bug about c++20 support. By the way, C++ intelligence in c/c++ extension works well in this situation.

One more, in above file I used asio which is a complicated header-only library. But in some simple cpp file, clangd work normal with co_await operator like this:
![image](https://user-images.githubusercontent.com/24547435/143732983-ed4bcfff-7266-4b94-a68e-09b579b75a8b.png)
clangd can find the definition of suspend_always()

**Comment by HighCommander4** [comment]
When mapping the cursor position to an AST node, we fail to select anything more specific than the `CompoundStmt`.

To get the result we want, I guess we want to select the `CXXTemporaryObjectExpr`, except that occurs four separate times, I guess because the AST is modelling the re-write of the `co_await` expression rather than the `co_await` expression itself.

**Comment by HighCommander4** [comment]
SelectionTree skips the entire `CoawaitExpr` which gets stuck with an incorrect point (as in single-token) source range.

Digging a bit into `CoawaitExpr` is modelled, it has four subexpression:

  * a "common" expression `c`
  * a "ready" expression, which is `c.await_ready()`
  * a "suspend" expression, which is `c.await_suspend()` (with some argument)
  * a "resume" expression, which is `c.await_resume()`

The ready, suspend, and resume expressions appear in the desugaring of the `co_await`, and the common expression (which is common to the other three) is tracked separately for convenience.

As for what the common expression `c` is, it **may** be the expression `e` which appears directly in the source (i.e. `co_await e`), but more commonly it's something like `p.await_transform(e)`. In such cases, since `c` does not appear directly in the source, it gets assigned a point source range (the location of the `co_await` keyword).

The end location of the `CoawaitExpr` in turn becomes the end location of `c`, making the `CoawaitExpr`'s source range that same point source range.

**Comment by HighCommander4** [comment]
Conceptually, I think a fix is needed along the following lines:

  * `CoawaitExpr` nees to expose its **operand**, i.e. the expression directly written in the source. Currently, `CoawaitExpr::getOperand()` exists but it just returns the common-expr, with a [comment](https://searchfox.org/llvm/rev/168bc7ce7e2ebe6527bf3fdd9262ef5c0deab4fc/clang/include/clang/AST/ExprCXX.h#4786) saying `//FIXME: Dig out the actual operand or store it`
    * As the comment suggests, `CoawaitExpr` does not currently store the operand as a separate subexpression. It would need to start doing so, or "dig it out" from the common-expr like the comment says.
  * `CoawaitExpr::getEndLoc()` should be changed to return `getOperand()->getEndLoc()`
  * `RecursiveASTVisitor` should visit the operand separately (possibly only if `!shouldVisitImplicitCode()`), or alternatively clangd's `SelectionVisitor` should handle `CoawaitExpr` specially and visit its operand

**Comment by HighCommander4** [comment]
> As for what the common expression `c` is, it **may** be the `CoawaitExpr`'s operand (i.e. the `e` in `co_await e`, which appears directly in the source), but more commonly it's something like `p.await_transform(e)` (where `p` is the coroutine promise). In such cases, since `c` does not appear directly in the source, it gets assigned a point source range (the location of the `co_await` keyword).

This, by the way, explains why the `co_await suspend_always()` case works -- that's a case where there is no `await_transform` and the common-expr is just the operand itself.

**Comment by shuyanzhu** [comment]
Impressive! Thanks a lot.

I kind of get it. `e` becomes  `c` and `c` hasn't apear directly in source, so when mapping cursor on `e` the node is neither `e` nor `c` and go-to-def gets nothing. I don't know if I'm getting this right

Another question is when `the actual operand` will get `Dig out`, and clangd would work in `co_await` situation.

**Comment by shuyanzhu** [comment]
I just git-blame that `FIXME`. It turns out "Richard Smith 2015-11-22 02:57:17 +0000 4786".

**Comment by HighCommander4** [comment]
Yeah, it was around the time `await_transform` was added to the coroutine spec. Previously the "operand" and "common-expr" were always the same. Then `await_transform` got added, and I guess no one actually needed the AST to retain the original operand... until now.

**Comment by shuyanzhu** [comment]
I see. When it gets PR please notify me by this issue, I'll compile clangd by myself. Thanks again.

**Comment by shuyanzhu** [comment]
I think I should reopen this issue better. I'm not familiar with the workflow of LLVM or clangd. All in all, I want to close the issue after you guys' PR.

**Comment by sam-mccall** [comment]
Yeah let's leave this open, it's a real bug and we'll need @HighCommander4's great investigation.

PseudoObjectExpr is a precedent for this kind of node that has syntactic and semantic forms, storing both.
As is CXXForRangeStmt I guess. Not sure either of them are *nice*, but...

**Comment by HighCommander4** [comment]
> When it gets PR please notify me by this issue, I'll compile clangd by myself.

I have a WIP fix here: https://reviews.llvm.org/D115187

It's not ready for review yet (it does not have clang tests, and may not be the final approach (I went with "dig out" but it's kind of fragile, I think the "store" option would be more reliable)), but it is enough to make go-to-def work on the `co_await`s in your example project, so if you're building clangd from source @shuyanzhu you could apply it.

**Comment by microcai** [comment]
I have no idea about how to get the [D115187](https://reviews.llvm.org/D115187) patch and apply it on released tarball and re-compile it .

**Comment by HighCommander4** [comment]
The patch has not merged yet (I need to make some fixes to it -- sorry for the slow progress). The issue should remain open until it does.
