### ISSUE TITLE
Generate special members

### ISSUE THREAD

**Issue by hg-zt** [clangd/clangd#973]
Declaring special members is tedious. It would be great if `clangd` could provide code-action (code lens?) or fix-action for generating special members (copy/move constructors and assignment operators) for a class.

For example,

```cpp
class Widget
{
public:
  virtual ~Widget() = default;
};

/*
Class 'Widget' defines a default destructor but does not define 
a copy constructor, a copy assignment operator, 
a move constructor or a move assignment operator
*/
```

After applying the code action, it becomes

```cpp
class Widget {
public:
    virtual ~Widget() = default;
    Widget() = default;
    Widget(const Widget&) = delete;
    Widget& operator=(const Widget&) = delete;
    Widget(Widget&&) = delete;
    Widget& operator=(Widget&&) = delete;
};
```

**Comment by sam-mccall** [comment]
Yeah, this is a good idea.

I dug into it a bit and and I wanted to add a variety of fine-grained actions like "explicitly declare copy-constructor and assignment", "disable move" etc. These could be really useful but are difficult to get right because of the ways the declarations interact.
So I think adding declarations without changing semantics is a good starting point, I think that's what you're suggesting.

I don't think I'd want constructor/destructor necessarily added with the others. Having *all* the copy/move operators is important for clarity, as declaring only some of them can lead to surprising results/interactions. But making `Foo() = delete;` or `~Foo() = default;` explicit doesn't have as much value. So maybe those should be a separate action if they're important.
