### ISSUE TITLE
jump to the definition in c separate c files 

### ISSUE THREAD

**Issue by ayoubelmhamdi** [clangd/clangd#977]
### clangd work fine with one file
I can jump to definition and declaration :+1: 
### but, I can't jump to the definition if I have a separate file like that
just clangd jump to the declaration and open `header file`
```bash
├── sources.c
├── sources.h
└── main.c
```
```c
//  main.c

#include "sources.h"

int main() {
  foo();
  return 0;
}
```
```c
// sources.h

void foo();
```
```c
// sources.c

#include <stdio.h>

void foo() {
  printf("foo");
}
```

**Comment by HighCommander4** [comment]
This is usually an indication of the project not being indexed because it doesn't have a `compile_commands.json`. Please have a look at the [project setup](https://clangd.llvm.org/installation#project-setup) documentation.

If your project has a `compile_commands.json` and it's still not working, please share some [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs).

**Comment by ayoubelmhamdi** [comment]
thanks  
I used this command `bear -- make > compile_commands.json` and it's indexed my project now
