### ISSUE TITLE
coroutines broken when using g++ (due to built in defines?)

### ISSUE THREAD

**Issue by galli-leo** [clangd/clangd#988]
I have a project configured with cmake that makes use of C++20's coroutines. (I use cmake's generated compile_commands.json to help clangd).
When working on the project under macOS clangd worked very well and I could use anything relating to coroutines fine.
However, working on it under Linux is giving me quite a lot of trouble.
A small reproduction case is included at the end.

I think I have traced it back to the builtin defines being "wrong".
It seems that even with compile_commands.json, clangd uses its internal defines instead of the ones given my g++.
For example, when parsing a file with clangd, `__clang__` is defined.

Is this currently the intended behaviour? I saw #533 and was not sure where this exactly applies. I would expect compile_commands.json to "just work", i.e. use everything from the compiler specified there.

Interestingly enough, I also tried compiling clangd from git main and then the repro case below works. However, it still does not work well for my project, since I am using boost.asio there. The following snippet fails there, since `__clang__` is defined, but the header `<experimental/coroutine>` is not found.

```cpp
// Support the co_await keyword on compilers known to allow it.
#if !defined(ASIO_HAS_CO_AWAIT)
# if !defined(ASIO_DISABLE_CO_AWAIT)
#  if defined(ASIO_MSVC)
#   if (_MSC_VER >= 1928) && (_MSVC_LANG >= 201705) && !defined(__clang__)
#    define ASIO_HAS_CO_AWAIT 1
#   elif (_MSC_FULL_VER >= 190023506)
#    if defined(_RESUMABLE_FUNCTIONS_SUPPORTED)
#     define ASIO_HAS_CO_AWAIT 1
#    endif // defined(_RESUMABLE_FUNCTIONS_SUPPORTED)
#   endif // (_MSC_FULL_VER >= 190023506)
#  elif defined(__clang__)
#   if (__cplusplus >= 201703) && (__cpp_coroutines >= 201703)
#    if __has_include(<experimental/coroutine>)
#     define ASIO_HAS_CO_AWAIT 1
#    endif // __has_include(<experimental/coroutine>)
#   endif // (__cplusplus >= 201703) && (__cpp_coroutines >= 201703)
#  elif defined(__GNUC__)
#   if (__cplusplus >= 201709) && (__cpp_impl_coroutine >= 201902)
#    if __has_include(<coroutine>)
#     define ASIO_HAS_CO_AWAIT 1
#    endif // __has_include(<coroutine>)
#   endif // (__cplusplus >= 201709) && (__cpp_impl_coroutine >= 201902)
#  endif // defined(__GNUC__)
# endif // !defined(ASIO_DISABLE_CO_AWAIT)
#endif // !defined(ASIO_HAS_CO_AWAIT)
```

**Logs**

[clangd.log](https://github.com/clangd/clangd/files/7857167/clangd.log)

**System information**

Output of `clangd --version`:

```
clangd version 13.0.0
Features: linux
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin: clangd for vscode

Operating system:
`Linux 5.15.13 (arch)`

**Small repro case**:

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.14)

# set the project name
project(clangd_gcc_coro)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fcoroutines")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# add the executable
add_executable(clangd_gcc_coro main.cpp)
```
main.cpp:
```cpp
/* taken from here: https://www.scs.stanford.edu/~dm/blog/c++-coroutines.html */
#include <concepts>
#include <coroutine>
#include <exception>
#include <iostream>

struct ReturnObject {
  struct promise_type {
    ReturnObject get_return_object() { return {}; }
    std::suspend_never initial_suspend() { return {}; }
    std::suspend_never final_suspend() noexcept { return {}; }
    void unhandled_exception() {}
  };
};

struct Awaiter {
  std::coroutine_handle<> *hp_;
  constexpr bool await_ready() const noexcept { return false; }
  void await_suspend(std::coroutine_handle<> h) { *hp_ = h; }
  constexpr void await_resume() const noexcept {}
};

ReturnObject
counter(std::coroutine_handle<> *continuation_out)
{
  Awaiter a{continuation_out};
  for (unsigned i = 0;; ++i) {
    co_await a;
    std::cout << "counter: " << i << std::endl;
  }
}

int
main()
{
  std::coroutine_handle<> h;
  counter(&h);
  for (int i = 0; i < 3; ++i) {
    std::cout << "In main1 function\n";
    h();
  }
  h.destroy();
  return 0;
}
```
compiles fine here:
```
➜  clangd_gcc_coro uname -a
Linux archer 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux
➜  clangd_gcc_coro g++ --version
g++ (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  clangd_gcc_coro cmake --build . && ./clangd_gcc_coro 
Consolidate compiler generated dependencies of target clangd_gcc_coro
[ 50%] Building CXX object CMakeFiles/clangd_gcc_coro.dir/main.cpp.o
[100%] Linking CXX executable clangd_gcc_coro
[100%] Built target clangd_gcc_coro
In main1 function
counter: 0
In main1 function
counter: 1
In main1 function
counter: 2
```

**Comment by sam-mccall** [comment]
Your original minimal example fails with clangd 13 because coroutines are off by default and clang doesn't support GCC's `-fcoroutines` flag. Clang's flag is `-fcoroutines-ts`. I'm not sure why, clang usually tries to be flag-compatible with gcc, but maybe they're not quite equivalent - maybe worth filing a bug against clang asking for an alias. In any case, it works at head because -std=gnu++20 enables coroutines in clang 14.

Regarding boost and compiler detection:

The short version is that clangd is clang-like rather than gcc-like or msvc-like, and is treated/detected as such. It defines `__clang__`, and only defines gcc/msvc compatibility macros to the extent that clang itself does.

Setting argv0 to gcc/g++/cl.exe is something like "parse flags more like X compiler would, and activate quirks for X compiler" (like -fms-extensions, note that most gcc extensions clang supports are on by default anyway). It doesn't pretend to be that compiler in a deep way. Similarly --query-driver is about extracting implicit `-I` and `-target` implied by the argv0, but doesn't extract built-in macros precisely because that would imply some deep emulation.

If the code can't be parsed by clang, then clangd is going to fail to parse it too. So I'm not sure it makes sense to support evading checks - what do we do when we pretend to be GCC, don't use GCC's parser, and users complain their project doesn't work?

The issue here is that the code is explicitly detecting clang and saying it should use a different header, rather than just detecting `__has_include(<coroutine>)`. I don't know why it's doing that. It could be e.g. because clang has insufficient coroutine support (so evading the check won't help).  In any case, we don't really support second-guessing that, for better or worse user code can detect the parser being used and do arbitrary things.

**Comment by galli-leo** [comment]
Thanks a lot for the quick response!

> Your original minimal example fails with clangd 13 because coroutines are off by default and clang doesn't support GCC's -fcoroutines flag. Clang's flag is -fcoroutines-ts. I'm not sure why, clang usually tries to be flag-compatible with gcc, but maybe they're not quite equivalent - maybe worth filing a bug against clang asking for an alias. In any case, it works at head because -std=gnu++20 enables coroutines in clang 14.

Hmm I will have to double check my actual project, but I don't remember having to set that flag there and it worked fine on macOS. Wondering why that could be the case.

> The short version is that clangd is clang-like rather than gcc-like or msvc-like, and is treated/detected as such. It defines __clang__, and only defines gcc/msvc compatibility macros to the extent that clang itself does.

That's good to know and makes a lot of sense. I guess my initial assumption was that it's compiling fine with gcc and clang normally, so why is it failing with clangd.

> Setting argv0 to gcc/g++/cl.exe is something like "parse flags more like X compiler would, and activate quirks for X compiler" (like -fms-extensions, note that most gcc extensions clang supports are on by default anyway). It doesn't pretend to be that compiler in a deep way. Similarly --query-driver is about extracting implicit -I and -target implied by the argv0, but doesn't extract built-in macros precisely because that would imply some deep emulation.

> If the code can't be parsed by clang, then clangd is going to fail to parse it too. So I'm not sure it makes sense to support evading checks - what do we do when we pretend to be GCC, don't use GCC's parser, and users complain their project doesn't work?

Yeah that also makes a lot of sense. I guess the issue really lies in the boost code explicitly detecting clang, while we are actually using gcc's libstc++. For now I (mostly) solved the issue by also installing clang and configuring with clang just for clangd. (Not fully solved, but I think the remaining issue is entirely with the library).

Maybe it could be worth mentioning this somewhere in the documentation? (Especially since the actually errors I encountered were quite confusing. The library just turned off coroutine support so clangd was just complaining about missing types.) Maybe something along the lines of: For more complex projects it can make sense to have a separate configure target using clang instead of gcc, so clangd can more accurately parse your code.

> The issue here is that the code is explicitly detecting clang and saying it should use a different header, rather than just detecting __has_include(<coroutine>). I don't know why it's doing that. It could be e.g. because clang has insufficient coroutine support (so evading the check won't help). In any case, we don't really support second-guessing that, for better or worse user code can detect the parser being used and do arbitrary things.

Would you say that this is an issue anyways that should be raised with the library? I am not well versed enough in this kind of feature detection to know how one best does this.

**Comment by sam-mccall** [comment]
> Maybe it could be worth mentioning this somewhere in the documentation?

Agree. I'm not sure we can do much about the errors being far away from the problem though - this comes out of the fact that we treat the PP directives are an opaque program that we run, and if they choose not to emit warnings there'll be no warnings. I'm not sure we have great alternatives to this behavior.

> Would you say that this is an issue anyways that should be raised with the library?

Yes - I don't know what the fix is because I don't know the motivation for the detection. But it's really on the library to keep this detection as up-to-date as possible.
But in general when the library chooses to do this there isn't that much we can do - the preprocessor metaprogram is fairly opaque, trying to interpret the code in some other way than running it will misinterpret a lot of real code.
