### ISSUE TITLE
documentHighlight is wrong for variable declared via lambda capture [regression]

### ISSUE THREAD

**Issue by ckandeler** [clangd/clangd#990]
Consider this piece of code:
```
struct S { int m; };
void f(S foo) {
    auto l = [bar = foo] { return bar.m; };
}

```
Doing textDocument/documentHighlight on the first occurrence of bar (in the lambda capture) returns the occurrences of S instead.
This used to work fine until https://reviews.llvm.org/D116630.

**Comment by hokein** [comment]
Thanks for the report, yeah, this is a regression issue of selection tree (particularly, related to removal of the early-claim hack...)

For ` auto l = [b^ar = foo] { return bar.m; };`, the selection debug log: 

```
D[12:34:22.634]  push: FunctionDecl </tmp/t2.cpp:2:1, line:4:1> 
D[12:34:22.634]   push: NestedNameSpecifierLoc <<invalid sloc>> 
D[12:34:22.634]   pop: NestedNameSpecifierLoc <<invalid sloc>> 
D[12:34:22.634]   skip: FunctionProtoTypeLoc </tmp/t2.cpp:2:1, col:13> 
D[12:34:22.634]    skipped range = </tmp/t2.cpp:2:1, col:13>
D[12:34:22.634]   push: CompoundStmt </tmp/t2.cpp:2:15, line:4:1> 
D[12:34:22.634]    push: DeclStmt </tmp/t2.cpp:3:5, col:43> 
D[12:34:22.634]     push: VarDecl </tmp/t2.cpp:3:5, col:42> 
D[12:34:22.634]      push: NestedNameSpecifierLoc <<invalid sloc>> 
D[12:34:22.634]      pop: NestedNameSpecifierLoc <<invalid sloc>> 
D[12:34:22.634]      skip: AutoTypeLoc </tmp/t2.cpp:3:5> 
D[12:34:22.634]       skipped range = </tmp/t2.cpp:3:5>
D[12:34:22.634]      push: LambdaExpr </tmp/t2.cpp:3:14, col:42> 
D[12:34:22.634]       push: VarDecl </tmp/t2.cpp:3:15, col:21> 
D[12:34:22.634]        push: NestedNameSpecifierLoc <<invalid sloc>> 
D[12:34:22.634]        pop: NestedNameSpecifierLoc <<invalid sloc>> 
D[12:34:22.634]        push: AutoTypeLoc </tmp/t2.cpp:3:15> 
D[12:34:22.634]        pop: AutoTypeLoc </tmp/t2.cpp:3:15> 
D[12:34:22.634]         hit selection: </tmp/t2.cpp:3:15>
D[12:34:22.634]        skip: CXXConstructExpr </tmp/t2.cpp:3:21> 
D[12:34:22.634]         skipped range = </tmp/t2.cpp:3:21>
D[12:34:22.634]       pop: VarDecl </tmp/t2.cpp:3:15, col:21> 
D[12:34:22.634]       skip: CompoundStmt </tmp/t2.cpp:3:26, col:42> 
D[12:34:22.634]        skipped range = </tmp/t2.cpp:3:26, col:42>
D[12:34:22.634]      pop: LambdaExpr </tmp/t2.cpp:3:14, col:42> 
D[12:34:22.634]     pop: VarDecl </tmp/t2.cpp:3:5, col:42> 
D[12:34:22.634]    pop: DeclStmt </tmp/t2.cpp:3:5, col:43> 
D[12:34:22.634]   pop: CompoundStmt </tmp/t2.cpp:2:15, line:4:1> 
D[12:34:22.634]  pop: FunctionDecl </tmp/t2.cpp:2:1, line:4:1> 
D[12:34:22.634] Built selection tree
 TranslationUnitDecl 
   FunctionDecl void f(S foo)
     CompoundStmt { …
       DeclStmt auto l = [bar = foo] {};
         VarDecl auto l = [bar = foo] {}
           LambdaExpr [bar = foo] {}
             VarDecl auto S bar = foo
              *AutoTypeLoc S
```

The trick is that the lambda captured bar `VarDecl` doesn't have a written `auto` in the source code, and the source location of `AutoTypeLoc` points to the `bar` token (which is not corresponding to the written source code), so the VarDecl's child node `AutoTypeLoc` claims the `bar` token, rather than leaving the `bar` token to be claimed by the parent node (`bar` `VarDecl`).

One fix is to make the source location of `AutoTypeLoc` AST node invalid for this case, it seems risky and invasive, probably will break something. Another safer fix is to bring back the early-claim hack in clangd. As we're close to 14 release, I'd prefer the early-claim approach.

**Comment by sam-mccall** [comment]
> One fix is to make the source location of AutoTypeLoc AST node invalid for this case, it seems risky and invasive, probably will break something

Yeah, I guess it would degrade diagnostics attached to that typeloc.

Seems sad to bring the early claim hack back, but I don't see a great alternative. Even overriding TraverseVarDecl isn't obvious: I don't see how to detect this case without exactly checking nameloc == autotypeloc, and the early-claim hack seems more principled.
